### ISSUE TITLE
Oracle_fdw.dll :  The specified procedure could not be found.

### ISSUE THREAD

**Issue by i-techsolutions** [laurenz/oracle_fdw#117]
I have installed postgresql 9.5 and oracle 11g on my windows 10 64 bit os.

I have set the path for oracle as well as for postgresql.

I have downloaded the zip and moved the .dll file to postgres lib folder & 2 .sql file and 1 .control file to shared & shared/extension

When I login to the psql and fire

postgres=# create extension oracle_fdw;

I am getting following error.

ERROR:  could not load library "D:/postgresdb/lib/oracle_fdw.dll": The specified procedure could not be found.

But when I fire an command

postgres=# SELECT name, default_version, installed_version, left( comment, 30) As comment FROM pg_available_extensions;

I am getting output

 oracle_fdw         | 1.1             |                   | foreign data wrapper for Oracl

So what is the exact issue?
And how could I solve the same?

**Comment by laurenz** [comment]
If you see the extension in `pg_available_extensions` it just means that the `*.control` file (and maybe the `*.sql` files; I am not sure) has been found in the correct place.

The error is from the Windows operating system and means that PostgreSQL fails to dynamically load `oracle_fdw.dll`. A web search turns up varying advice (ranging from *reboot the computer* to *adapt your Path so that only one Oracle client installation can be found on it*).

If you actually have more than one Oracle installation on the machine, that is indeed often a reason for trouble. Can you find more than one `oci.dll` on your system?

**Comment by i-techsolutions** [comment]
Hi laurenz,
I dint find more than one oci.dll
Also all the paths are set properly.
Can you guide me exactly how should I do the same?
Or can you upload a installation video on youtube?

**Comment by laurenz** [comment]
Must be some setup problem with Oracle on Windows; unfortunately I am not very knowledgable with Windows, and the error message is not really meaningful.

Maybe `oci.dll` is not in the PATH of the PostgreSQL server process? If yes, did you try to reboot?

**Comment by i-techsolutions** [comment]
Hi laurenz,
I have installed the same on ubuntu and I am getting following error while making command.

create extension oracle_fdw;
ERROR : coul dnot access file "$libdir/oracle_fdw" : No such file or directory.

All the paths are set for postgres as well as oracle

**Comment by laurenz** [comment]
You forgot to install `oracle_fdw.so` in the PostgreSQL library directory.

Please follow the installation instructions in the README.

**Comment by PaarthHim** [comment]
For your problem in Windows

> postgres=# create extension oracle_fdw;
> 
> I am getting following error.
> 
> ERROR: could not load library "D:/postgresdb/lib/oracle_fdw.dll": The specified procedure could not be found.

Follow Instruction as given below:
Download correct Oracle_fdw binary package
![image](https://cloud.githubusercontent.com/assets/21073722/17803589/062ccec8-6615-11e6-8bd7-5213eb088aea.png)

Put the .dll file to postgres lib folder & 2 .sql file and 1 .control file in shared/extension.

Set the path for oracle as well as for postgresql.

Now you can try to create Extention.

**Comment by lorenati** [comment]
I'm using oracle_fdw in windows as well, have you checked the dll dependencies? when I compile my dll in my machine the extension works good, but when I put the dll in another machine the extension throws an error (don't remember your same message) because that machine does not have this dll: MSVCR120D.dll

(A similar scenario is described here: http://stackoverflow.com/questions/23114427/vs2012-msvcr120d-dll-is-missing)

**Comment by laurenz** [comment]
`MSVCR120D.dll` is the Microsoft Visual C runtime, which is also needed by the PostgreSQL server and included with the binary package, so it should never be missing.

**Comment by chrullrich** [comment]
@lorenati, the solution to your problem is also on that SO thread: msvcr120D is the debug version of the runtime, which is not included in either the Postgres or VC++ redist packages, because it is actually not redistributable. To get around that, build for release and you will get the expected dependency on msvcr120 (no "d") instead.

This does not help with the OP's issue, though. From the error message, I think there must be some really unusual thing going on. Either the Oracle client is the wrong (old?) version, or there is some wrong DLL early in the PATH that shadows the correct one.

**Comment by i-techsolutions** [comment]
Hi everyone,
with 1.5.0 I am able to create extension.

Now I have my oracle database on next machine with IP 192.168.1.16 & port on which it listens is 1521.

When I create foreign table it works fine.

```
postgres=# create server oraserver foreign data wrapper oracle_fdw options (dbserver'@//192.168.1.16:1521/orcl');
CREATE SERVER

postgres=# create user mapping for current_user server oraserver options (user 'sh',password 'sh');
CREATE USER MAPPING

postgres=# create foreign table finalforecast (
postgres(# data TEXT,
postgres(# week1 NUMERIC,
postgres(# week2 NUMERIC,
postgres(# week3 NUMERIC,
postgres(# week4 NUMERIC,
postgres(# vendor TEXT)
postgres-# SERVER oraserver
postgres-# OPTIONS (schema 'orcl', table 'FINALFORECAST');
CREATE FOREIGN TABLE
```


But at the time of selecting data it gives following error.


```
postgres=# select * from finalforecast;
ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle
```

**Comment by laurenz** [comment]
That is progress, whatever the problem was.

There is one error in what you did: you should remove the `@` from `@//192.168.1.16:1521/orcl`, but  that is not what is causing the error.

That error is unfortunately a very general Oracle error that means &ldquo;something is wrong with your Oracle setup&rdquo;.

Can you connect to Oracle with `sqlplus` when you are logged on as PostgreSQL operating system user?
Do you have any environment variables defined like `TNS_ADMIN`, `TWO_TASK` or variables that start with `ORACLE_` or `NLS_`?

**Comment by i-techsolutions** [comment]
Hi laurenz,

I am able to access the oracle database with sqlplus using same username and password.

Also on ubuntu i am getting the same error and have followed the installation manual,


create extension oracle_fdw;
ERROR : coul dnot access file "$libdir/oracle_fdw" : No such file or directory.

All the paths are set for postgres as well as oracle

**Comment by laurenz** [comment]
Sorry, but it is very hard to say what you did wrong just from the error message

    OCIEnvCreate failed to create environment handle

It could be anything from a mismatch of Oracle libraries from different versions (which could also cause the original problem you encountered, hence my question if there is more than one `oci.dll`) to bad environment variables.

About your problem on Linux, is there an `oracle_fdw.so` in your PostgreSQL library directory?

**Comment by i-techsolutions** [comment]
Can you tell from where I can download the .so?

or I need to create it using make command?

**Comment by i-techsolutions** [comment]
Hi laurenz,

Please check attached screenshot for ubuntu where all paths are set and oracle_fdw.so is also in lib folder of postgres with rights as 777
![error oracle_fdw](https://cloud.githubusercontent.com/assets/13335595/18201491/208348f6-7128-11e6-984e-ec050f24b72f.PNG)

![accesscontrol](https://cloud.githubusercontent.com/assets/13335595/18201482/18143306-7128-11e6-91ea-26d278b5129d.PNG)

**Comment by laurenz** [comment]
You cannot download it; you have to build it.

Read and apply chapter __6. Installation__ from the README.

**Comment by Nashev** [comment]
see https://github.com/laurenz/oracle_fdw/releases for binary downloads

**Comment by laurenz** [comment]
The latest error @i-techsolutions encountered means that the shared library path is not configured so that it contains the Oracle client shared library. Either set `LD_LIBRARY_PATH` in the environment of the PostgreSQL server or use `/etc/ld.so.conf` and `ldconfig` to add the directory. The second technique is better.

**Comment by pcrex** [comment]
I got an "ERROR : could not access file "$libdir/oracle_fdw": No such file or directory." when I put "oracle_fdw.dll" into "C:\Program Files\PostgreSQL\pg96\lib", but not into "C:\Program Files\PostgreSQL\pg96\lib\postgresql".

**Comment by laurenz** [comment]
You can run `pg_config --libdir` to get the library directory for your installation.

Please don't hijack an existing issue for your question, rather open a new issue.

**Comment by adrianboangiu** [comment]
Hi laurenz,
I have installed the version 2.0 of the oracle_fdw on Windows 10 Professional with Postgres 10.1 and 
Oracle 12.1.
I got exactly the same error: ERROR:  could not access file "$libdir/oracle_fdw": No such file or directory
when trying to create extension.
I have the following value for libdir variable
C:\Users\abu>pg_config --libdir
C:/siv718/PostgreSQL/pg10/lib

I confirm pcrex findings. As soon as I copied oracle_fdw.dll also into C:\siv718\PostgreSQL\pg10\lib\postgresql I was able to create the extension.
I can also confirm that the error is not due to some system variables since I am able to create the extension without any Oracle variable defined into the system (ORACLE_HOME, TNS_ADMIN, LD_LIBRARY_PATH). I only have Oracle and Postgres in the path variable.
