### ISSUE TITLE
what happen in this error"ERROR:  invalid byte sequence for encoding "UTF8": 0x00"

### ISSUE THREAD

**Issue by sangli00** [laurenz/oracle_fdw#120]
@laurenz  maybe oracle table encoding is error.
how to fixed this problem.thanks.

**Comment by laurenz** [comment]
This is the same problem as #114: while a null byte is allowed in a character string in Oracle, it is not allowed in PostgreSQL. You might want to fix the data on the Oracle side.

**Comment by sangli00** [comment]
if I can't permission  modify  oracle data,so this problem is not fix?  
maybe invalid  character

**Comment by laurenz** [comment]
There's no way to allow a zero character in PostgreSQL, and oracle_fdw does not have any provisions for modifying the data it gets from Oracle.

Is the zero byte in the character string in the Oracle database intentional?  
If not, maybe they would even be interested in fixing it; zero bytes in strings cause all sort of trouble.

**Comment by sangli00** [comment]
ERROR:  no primary key column specified for foreign Oracle table

old release is can't PK ?why need PK column?

**Comment by laurenz** [comment]
For `UPDATE` or `DELETE`. See the description of the `key` option in the README.

**Comment by volkmarbuehringer** [comment]
use select translate( column, chr(0),' ' ) 

in select to convert the invalid byte sequenzes in oracle to something else in oracle
(during selection or update the tables in oracle to remove them )

pg gives you the column names and the invalid codes

before loading into pg I have to do a lot of updates, because the oracledb is infested with this crap,
especially email data
