### ISSUE TITLE
IMPORT FOREIGN SCHEMA and public synonym

### ISSUE THREAD

**Issue by alexign** [laurenz/oracle_fdw#123]
Why using public synonyms is not available while  import say synonym object in IMPORT FOREIGN SCHEMA?
I have some public synonyms and want to import  into PG structure of objects(views) to which this synonym refers to.

**Comment by laurenz** [comment]
`IMPORT FOREIGN SCHEMA` will only import objects found in the Oracle system catalog `ALL_TAB_COLUMNS`, and this view does not contain synonyms.

But `IMPORT FOREIGN SCHEMA` cannot work for public synonyms even without that restriction, because public synonyms don't belong to a certain schema.

You can use `CREATE FOREIGN TABLE` to define foreign tables based on public synonyms &ndash; just make sure you don't use the `schema` option.
