### ISSUE TITLE
PG_9.5+:JSONB and ORA_12c:JSONB

### ISSUE THREAD

**Issue by massimiliano-della-rovere** [laurenz/oracle_fdw#127]
Not really an issue but a question: are there any plans to support JSONB (PostgreSQL 9.5+ and Oracle 12.c) datatype and operators?

**Comment by laurenz** [comment]
Hm, I wasn't aware that Oracle has followed suit and implemented PostgreSQL's `json` type. Interesting.

Since Oracle stores JSON as `CLOB`, `BLOB` or `VARCHAR2` according to [the documentation](http://docs.oracle.com/database/121/ADXDB/json.htm#ADXDB6251), it should not be difficult to allow mapping it to PostgreSQL `json`.

The real question is if it is worth the effort &ndash; you might as well map it to `text` or `bytea` and cast the result to `json` (throwing in a `convert_from()` for a `bytea`), that would do the same thing.
