### ISSUE TITLE
9.4 on Windows 64 - "Specified module could not be found"

### ISSUE THREAD

**Issue by tmathewsNN** [laurenz/oracle_fdw#15]
Hi,

Thanks for the work on this extension. 

I'm running PostgreSQL 9.4 on Windows 64-bit.  I've downloaded the binary package and copied all of the files to their respective folder locations. When I try to run CREATE EXTENSION oracle_fdw, I get the following error: "ERROR: could not load library "C:/Program Files/PostgreSQL/9.4/lib/oracle_fdw.dll": The specified module could not be found.
SQL state: XX000". Any thoughts on why I'm encountering this issue?

![capture](https://cloud.githubusercontent.com/assets/10425955/5636080/704bcf62-95b4-11e4-87b8-4d9609f99375.JPG)

When I execute "SELECT name, default_version, installed_version, left( comment, 30) As comment FROM pg_available_extensions" your extension does appear as available. Just can't get it to install.

Thanks.

**Comment by laurenz** [comment]
I can think of two possibilities:

One is that the PostgreSQL server process does not have the permission to read or execute oracle_fdw.dll. Can you verify that this is not the case?

The other, more likely option is that the PostgreSQL server process cannot find the Oracle client library oci.dll or one of its dependent libraries.
Did you set the PATH environment variable of the PostgreSQL server process so that it contains oci.dll and then restart the PostgreSQL server?

**Comment by tmathewsNN** [comment]
Hi Laurenz,

Option number two was the fix. I did not change the PATH variable to point at the oracle instant client directory. Thanks so much for the help!

**Comment by PaarthHim** [comment]
> Did you set the PATH environment variable of the PostgreSQL server process so that it contains oci.dll and then restart the PostgreSQL server?

How to set ` PATH environment variable of the PostgreSQL server process ` to access oci.dll.

Because I am facing same issue.
Thanks in advance.

**Comment by JoaquinDLT** [comment]
I am having the same issue. The strange thing about this, is that postgresql knows the absolute path to the file, so in theory there would be no need to add it to the path variable of windows...
