### ISSUE TITLE
srid.map file problems

### ISSUE THREAD

**Issue by pauldzy** [laurenz/oracle_fdw#150]
Hi Laurenz,

I think this is some kind of small issue but I cannot get my srid.map file to work.  I have created the file via
echo "8265 4269" >  /usr/share/postgresql/9.6/srid.map
echo "8307 4326" >> /usr/share/postgresql/9.6/srid.map

However when I attempt to move over a geometry with SRID 8265 I just get

ERROR:  error reading from file "srid.map": %m
CONTEXT:  converting column "shape" for foreign table scan of "storet_indexing_source", row 1

I tried changing permissions to 777.  I am a bit stumped.

Thanks,
Paul

oracle_fdw 1.5.1devel, PostgreSQL 9.6.2, Oracle client 12.1.0.2.0, Oracle server 11.2.0.4.0

**Comment by laurenz** [comment]
The `%m` should be replaced by a system error message&hellip;
I have just pushed cc303c6ff2f2b9bd8a6736c301b9a5b64a17257b which should fix that.

Can you try again and see if you get a system error message that sheds light on the problem?

**Comment by pauldzy** [comment]
Thanks for the fast response,

So the error now says

**ERROR:  error reading from file "srid.map": No such file or directory
CONTEXT:  converting column "shape" for foreign table scan of "storet_indexing_source", row 1**

Which is odd as of course if I don't create this file everything works fine.  I've tried setting permissions to 777 even without any effect.

Cheers,
Paul

**Comment by laurenz** [comment]
Looks like a bug in my code.

Could you post the output of `od -c srid.map` so I can reproduce the problem?
I hope the file is not too large.

**Comment by pauldzy** [comment]
Hi Laurenz, 

Nope its just these two SRIDs.  I tried removing the final line feed but that did not correct the matter.

```
root@d788d01069e9:/usr/share/postgresql/9.6# od -w10 -t x1 -c srid.map
0000000  38  32  36  35  20  34  32  36  39  0a
          8   2   6   5       4   2   6   9  \n
0000012  38  33  30  37  20  34  33  32  36  0a
          8   3   0   7       4   3   2   6  \n
0000024
```

Thanks!
Paul

**Comment by laurenz** [comment]
I cannot find the problem &ndash; somehow it looks like a &ldquo;false positive&rdquo; caused by bad error handling.

What is your operating system?

I pushed two more patches that should improve error handling; can you try again with the latest HEAD?

**Comment by chrullrich** [comment]
Pardon the quite possibly stupid question, but are you sure the file is in the correct place?

What does `SELECT setting FROM pg_config WHERE name = 'SHAREDIR'` return?
Is there a file named `postgres.bki` in the same directory?

**Comment by laurenz** [comment]
If it were not in the correct place, oracle_fw would not be able to open it.
That error message is thrown *after* the file has been opened successfully.
Thanks for the help though!

**Comment by chrullrich** [comment]
OK, how about this one: The code seems to assume that `ferror()` returns a valid errno value. Both POSIX and its current Linux and FreeBSD man pages disagree: 

> The function ferror() tests the error indicator for the stream pointed to by stream, returning nonzero if it is set. 

```
/* check for errors */
save_errno = ferror(mapFile);
(void)fclose(mapFile);
errno = save_errno;

if (errno)
{
	free(srid_map);
	srid_map = NULL;
	oracleError(FDW_ERROR, "error reading from file \"" SRID_MAP_FILE "\": %m");
}

```

That explains at least the unexpected ENOENT, if this ferror() can return 2.

**Comment by laurenz** [comment]
You are looking at code that I wrote *after* this problem was reported, in the hope that this would improve matters.

In the [code as it was before][1] I

1. didn't initialize `errno` to 0 before I opened the file.

2. used `errno` to detect problems with `fgetc`, which seems to be wrong. The Linux man page doesn't say anything about it, but I found many references that `ferror` is the correct way to detect an error with `fgetc`.

My main problem is that both points, while problems with the code, don't explain the error:
It cannot be number one, because otherwise the error message would have been `cannot open file "srid.map"`.
But it cannot be the second problem either, because if `fopen` succeeded and `fgetc` doesn't set `errno`, how can `errno` end up non-zero to cause the error?

I'm quite confused.

[1]: https://github.com/laurenz/oracle_fdw/blob/68a570b79fb79180f08d3ba9cc8bcdf4a0ca30ba/oracle_gis.c#L196

**Comment by chrullrich** [comment]
No, I was not referring to the original problem at all. What I meant is that in 65721ba, while trying to fix the bug that caused the unconverted "%m" in the original report, you introduced a new bug that is responsible for the confusing error message.

The result of `ferror()` is not suitable for assigning to `errno`, because it is a boolean. @pauldzy's system can apparently return a nonzero value from `ferror()` that happens to equal ENOENT, so after you clobber errno with this random number, the "%m" produces the misleading message.

Also, `fgetc()` definitely _does_ set `errno`. The references to `ferror()` are about using that and `feof()` to distinguish between EOF (at which point `errno` might still contain some stale value) and an actual error. See the lengthy list of possible error codes at http://pubs.opengroup.org/onlinepubs/9699919799/functions/fgetc.html, for example. The FreeBSD man page also clearly says that 

> If an error occurs, the global variable errno is set to indicate the error.

**Comment by pauldzy** [comment]
Hi Laurenz and Chrullrich,

Okay so 65721ba2a5a2b4feed944900cedafed9010a396f fixed it!

All works swell now as I see Oracle SDO with 8265 coming across as PostGIS geometry with 4269.

So to respond to your earlier questions, this is on the official "postgres:9.6" docker image so it's jessie debian.

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

Thanks!
Paul

**Comment by laurenz** [comment]
Fix a bug, introduce a bug :^(

Thanks for the analysis, @chrullrich!
I hope this last commit sets things right.

So what must have happened is this:
- Initially, `errno` is zero, and opening the file succeeds, so it remains zero.
- Then `fgetc` reads bytes until EOF, which somehow changes `errno` but does not set the error indicator on the file (is that possible?).
- I check `errno` to determine if there was an error and get a false positive result.

Weird that it does not happen on my RedHat Linux.

@pauldzy, could you try again with the latest commit and see if it still works for you?

**Comment by chrullrich** [comment]
My theory is that `errno` was _not_ zero, but – in this case – ENOENT. That value stayed through opening the file, because a) `fopen()` does not modify it in case of success, and b) the error check over `fopen()` only looks at its result, not `errno` at all. From that point on, everything worked as designed, until at the very end, the stale ENOENT struck.

deb22d0 fixed this by clearing `errno` at the top, and 65721ba and 97a1997 were unnecessary. The `clearerr()` has nothing to clear right after opening the file, and the final check would work just as well based on `errno` as before.

> Then fgetc reads bytes until EOF, which somehow changes errno but does not set the error indicator on the file (is that possible?).

No, it's not, it sets the EOF indicator and, like `fopen()` earlier, leaves `errno` alone. Hence `ferror()` returns zero, clobbers `errno` (before 97a1997) (but _to_ zero, not away from it as I thought) and the function was successful by one accident nested in another accident that would have had it fail. With the latest commit, it looks good to me.

Of course, I may be wrong.

**Comment by pauldzy** [comment]
Hi Laurenz,

Yes, everything is good with 97a1997e18e2325e8cf493cb9eaaca60eea88833.

Thanks!

Paul

**Comment by laurenz** [comment]
After looking at it again, I'm certain that you are right.
Thanks again!
