### ISSUE TITLE
Optimistic SDO Mapping Problem

### ISSUE THREAD

**Issue by jonrmayer** [laurenz/oracle_fdw#157]
SDO Mapping works fine when the underlying dataset contains no data issues - ie no invalid or non simple geometries. This is a reasonably rare occurence especially with datasets that you don't own/have any control over. There will always be issues.

When performing a select on a dataset with issues such as non supported geometries - the wrapper will throw an error and stop any further processing of the data.

I would prefer a gentler approach such as returning a null geometry, or even better, a postgresql composite type for all returned values with a geometry and a potential error message which can be handled /analysed further.

Other than this, this is a great tool which I expect to use in the future

**Comment by laurenz** [comment]
I understand your pain.

I'll tell you the reasons why I don't want to add such a feature.
I try to stay in line with PostgreSQL's philosophy as much as I can, so that oracle_fdw behaves as expected for people who are familiar with PostgreSQL.

Now PostgreSQL is quite strict about data integrity. For example, it won't tolerate bytes in a string that make no sense in the string's encoding, which keeps the data clean, but annoys many people (perform a web search for &raquo;invalid byte sequence for encoding “UTF8”&laquo;).
So it would be quite out of line to just convert &ldquo;invalid&rdquo; geometries to something else.

One possibility would be an option to make a table &ldquo;fault tolerant&rdquo; in the sense you propose. It's not trivial &ndash; right now the code just throws an error if it encounters something bad, and all these places would have to be modified. I don't really feel motivated, because I don't like such a feature very much.

Maybe you could work around the problem by writing a PL/pgSQL function that first selects the primary keys of the foreign table, loops through those and selects the geometries one by one, each call surrounded by a `BEGIN ... EXCEPTION ... END` block that allows you to catch errors.
It will be slower, but it might at least help to identify the problematic geometries.

**Comment by jonrmayer** [comment]
Hi Laurenz,

I did try your suggestion - a plpgsql function that loops over individual geometries -  but received an aborted transaction error. You are right - even if I got it to work, it would be very slow.

Obviously, the Code could be extended to support more geometry types such as GeometryCollections, Curves etc but PostGIS will always be "slightly" behind Oracle SDO so I don't think that this is the only solution.

Currently, the wrapper return nothing if PostGIS is not installed. I am just wondering whether it could return a string representation of the SDO geometry - ordinate_array, elem_info etc. It would be relatively trivial to parse & analyse this data with a plpgsql function. How hard would this be to implement?

So my hybrid solution would be to use the SDO-Geometry Mapping if the data is perfect and if not - use oracle_fdw in a non-PostGIS environment and link the data via postgresql_fdw into a PostGIS instance.

A little bit awkward but it would align with your philosophy above

Jonathan

**Comment by laurenz** [comment]
You avoid the &ldquo;aborted transaction&rdquo; with the `EXCEPTION` clause in the PL/pgSQL block:

    FOR i IN SELECT id FROM geom_data LOOP
       BEGIN
          SELECT geom INTO g FROM geom_data WHERE id = i;
          RETURN NEXT ROW(i, g)::geom_data;
       EXCEPTION
          WHEN OTHERS THEN
             RETURN NEXT NULL::geom_data;
       END;
    END LOOP;

About the GIS-related enhancements:
I don't know how hard that would be, but it would certainly not be trivial.
The GIS code was contributed by [Oslandia](http://www.oslandia.com/), so you might want to ask them what they think of it and if they would want to code that for you for money.
