### ISSUE TITLE
Crash with now(), current_date, etc in WHERE Clause

### ISSUE THREAD

**Issue by dreckard** [laurenz/oracle_fdw#17]
Executing any query with now() or current_date in the WHERE clause crashes Postgre in my environment.  For example, the following query:

*SELECT 1 FROM FOREIGN_TABLE WHERE current_date=current_date*
**Error:** server process (PID 2404) was terminated by exception 0xC0000005

**EXPLAIN VERBOSE:**
Output: 1
One-Time Filter: (('now'::cstring)::date = ('now'::cstring)::date)
->  Foreign Scan on public.foreign_table  (cost=10000.00..10000.00 rows=1000 width=0)
    Oracle query: SELECT /*27044e1d4cb9a9ea5fb63948080dbec3*/ '1' FROM "SCOTT"."EMP" WHERE (TRUNC(CAST (:now AS DATE)) = TRUNC(CAST (:now AS DATE)))
    Oracle plan: SELECT STATEMENT
    Oracle plan:   FILTER    (filter TRUNC(CAST(:NOW AS DATE))=TRUNC(CAST(:NOW AS DATE)))
    Oracle plan:     INDEX FULL SCAN EMP_PK

**Server OS:** Windows
**oracle_diag()**: oracle_fdw 1.1.0, PostgreSQL 9.4.0, Oracle client 10.2.0.5.0, Oracle server 10.2.0.4.0

Some problem with binding for :now perhaps?  The relevant code seems to be [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L3032).

**Comment by laurenz** [comment]
The problem was most likely [here](https://github.com/laurenz/oracle_fdw/blob/afcc9afc14b56afe244e83680940db24892c58ed/oracle_utils.c#L1912 "code before commit 80260cc3230ddd8c68193abb07a701f635e8c723").

I have committed 80260cc3230ddd8c68193abb07a701f635e8c723 which should fix the problem.

Can you build oracle_fdw yourself or do you need a binary?
If you need a binary, tell me whether you run on 32-bit or 64-bit Windows and let me know to which e-mail address I should send it.

**Comment by dreckard** [comment]
I just set up the build and with the latest revision it works fine.  Thanks!
