### ISSUE TITLE
By using Oracle_fdw, tried to select data of a table from oracle in postgres, it successfully gets executed for few datatypes but when a column is of xmltype in oracle, I am not able to get its data in foreign table in Postgres

### ISSUE THREAD

**Issue by AnandNicky** [laurenz/oracle_fdw#172]
Table in oracle:

    create table detail.test
    (
      user_id NUMBER not null,
      person_id      INTEGER not null,
      user_info      XMLTYPE
    );

`Select * from detail.test;` gives the below output:

    USER_ID	PERSON_ID	USER_INFO
    141	8738	<XMLTYPE>
    150	8738	<XMLTYPE>
    159	112268	<XMLTYPE>
    172	8738	<XMLTYPE>
where in `user_info` data exist like:

    <user-info><current-dttm>2012-01-11 13:09:41</current-dttm></user-info>

Now while I am trying to create a foreign table in postgres with the following syntax:
    CREATE FOREIGN TABLE tst_psql(
       user_id INTEGER OPTIONS (key 'true') NOT NULL,
       person_id INTEGER not null,
       user_info xml
    ) SERVER oradb1 OPTIONS ( schema 'detail', table 'test');

Table successfully gets created, but while accessing user_info column it says :

    ERROR: column "user_info" of foreign table "tst_psql" cannot be converted to or from Oracle data type
    SQL state: HV004

Kindly help to figure out the solution.

Thanks

**Comment by laurenz** [comment]
This is working as designed.

If you look at the [README][1], you'll see that `XMLType` is not among the list of Oracle types that can be transated.

You have four options:

1. Omit the column from the `SELECT` list.

2. Omit the XML column in the foreign table definition. This only works if it is the last column.

3. Define a view in Oracle that produces a text representation of the XML.

4. Instead of the Oracle view, you can define the foreign table based on an Oracle `SELECT` statement that converts the column: `OPTIONS (table '(SELECT ... FROM oratable)')`.

 [1]: https://github.com/laurenz/oracle_fdw#data-types

**Comment by AnandNicky** [comment]
Thanks for the response, Laurenz!
Could you please share any doc or any example on the point 4. As it is mandatory for me to fetch content of a column which has xml data to Postgres and hence I can't omit it.
Regards,

**Comment by laurenz** [comment]
There is no need to handle JSON specially, because Oracle does not have a JSON data type. It can be retrieved as the `BLOB`, `CLOB` or `VARCHAR2` that it is.

I see in #174 that you solved the problem by using the `XMLTYPE.GETCLOBVAL()` function, so I'll mark this issue as closed.
