### ISSUE TITLE
foreign table issue when used with inherits

### ISSUE THREAD

**Issue by zskr** [laurenz/oracle_fdw#181]
Hi, 
  I am trying to use the below sql statements to migrate data from oracle to postgres. i have setup the extension, server and user mapping.

    CREATE TABLE TABLEONE (
       FIELDONE INT NOT NULL,
       FIELDTWO VARCHAR(255) NOT NULL,
       FIELDTHREE integer default '0'  not null,
       PRIMARY KEY (FIELDONE), 
       CONSTRAINT TABLEONE_TABLEZERO_FK
          FOREIGN KEY (FIELDONE) REFERENCES TABLEZERO(FIELDONE)
    );
    CREATE FOREIGN TABLE FT_TABLEONE()
       INHERITS (TABLEONE)
       SERVER ORA_PROD_DMP_SERVER
       OPTIONS (SCHEMA :PROD_SCHEMA, TABLE 'TABLEONE');
    INSERT INTO TABLEONE SELECT * FROM FT_TABLEONE;
    DROP FOREIGN TABLE FT_TABLEONE;

I have the following queries
1. Is this a correct approach?
2. `FIELDTHREE` doesnt exist in the source table. Then the `INSERT` script fails with

       ERROR:  null value in column "FIELDTHREE " violates not-null constraint".  

I didnt face this issue when I used the below statements. Is this because `CREATE TABLE` behaves differently from `INSERT INTO`?

    CREATE FOREIGN TABLE TABLEONE (
       FIELDONE INT NOT NULL,
       FIELDTWO VARCHAR(255) NOT NULL,
       FIELDTHREE integer default '0'  not null,
       PRIMARY KEY (FIELDONE)
    )
       SERVER ORA_PROD_DMP_SERVER
       OPTIONS (schema :PROD_SCHEMA, TABLE 'TICKET_DATA');
    CREATE TABLE TEMP_TABLEONE AS (SELECT * FROM TABLEONE);
    DROP FOREIGN TABLE TABLEONE;
    ALTER TABLE TEMP_TABLEONE RENAME TO TABLEONE; 
    ALTER TABLE TABLEONE
       ADD CONSTRAINT TABLEONE_TABLEZERO_FK
       FOREIGN KEY (FIELDONE) REFERENCES TABLEZERO(FIELDONE);

3. Autocommit is set to true. But if I dont drop the foreign table, another user cant read from the table `TABLEONE`. Why is that?

**Comment by laurenz** [comment]
Both approaches are fine, I guess there are only small problems with what you tried.

The first approach has two problems:

1. The table inheritance is unnecessary and will produce strange results when you select values from `tableone` after you have migrated the table &ndash; it will show the values from *both* tables.

2. You get the error because you try to insert a NULL value into `fieldthree`. This would work:

       INSERT INTO tableone (fieldone, fieldtwo)
          SELECT fieldone, fieldtwo FROM ft_tableone;

For your second approach, this statement has a syntax error:

    CREATE FOREIGN TABLE TABLEONE (
       FIELDONE INT NOT NULL,
       FIELDTWO VARCHAR(255) NOT NULL,
       FIELDTHREE integer default '0'  not null,
       PRIMARY KEY (FIELDONE)
    )
       SERVER ORA_PROD_DMP_SERVER
       OPTIONS (schema :PROD_SCHEMA, TABLE 'TICKET_DATA');

You cannot define a primary key constraint on a foreign table!

Apart from that, the second approach should work fine.

Can you specify what you mean if you say that another user cannot read from `tableone`?
Is there an error message?
Which table `tableone` are you talking about? The foreign table or the local table after renaming?

**Comment by zskr** [comment]
Thanks Laurenz.
I would like to proceed with the first approach as we run the create table script independent of the data migration process. 
1. The problem that you mentioned "it will show the values from both tables." doesn't happen after I drop the foreign table. Hope that is the only problem with this approach.
3. The auto commit issue I have mentioned is on the first approach. Reworded the question below.
 Autocommit is set to true. But if I dont drop the foreign table FT_TABLEONE, another user cant read from the table TABLEONE using pgAdmin. There is no error message.

**Comment by laurenz** [comment]
Ad 1: Yes, if you drop the foreign table, the inheritance relationship is also gone. If you use inheritance only as a means to copy the column definitions, I see no problem with your approach.

Ad 2: If autocommit is turned on, each statement is committed immediately. If you run

    CREATE TABLE TABLEONE (...);
    CREATE FOREIGN TABLE FT_TABLEONE ()
       INHERITS (TABLEONE) ...;
    INSERT INTO tableone (fieldone, fieldtwo)
       SELECT fieldone, fieldtwo FROM ft_tableone;

and then don't drop `FT_TABLEONE`, each query to `TABLEONE` will read results from *both* tables because of the inheritance relationship.

That should work just fine, and it did when I tried it. If you can't see any results with pgAdmin, and there is no error message, I can think of two immediate reasons:

1. There are locks on either of the tables held by another database session. Try

       SELECT * FROM pg_locks WHERE NOT granted;

   from a different database session and see if you get any results.

2. The amount of data read from Oracle is so great that pgAdmin has to work a long time to display it. It is known that pgAdmin is not particularly good at handling big result sets.

   Check if pgAdmin consumes CPU time.

**Comment by zskr** [comment]
Thanks Laurenz.
