### ISSUE TITLE
strange  ORA-06413: Connection not open.    from phpPgAdmin

### ISSUE THREAD

**Issue by oracle10gr2** [laurenz/oracle_fdw#19]
Hi !
i've  recently install fdw 1.1.0 , created oradb link and I can  from psql prompt  select data from remote table , for example:  
```
psql --username=lalala  --dbname=${database} 
psql (9.4.0)
Type "help" for help.
irzdbbkp=> select count(*) from rem.rem_irz_log;
 count  
--------
 162867
(1 row)
irzdbbkp=> 
```
at the same time, i can't execute SELECT  from phpPgAdmin SQL 
i ve got an error:
``` 
ERROR:  cannot connect to foreign Oracle server
DETAIL:  ORA-06413: Connection not open.
```
the same error i've got when run psql in TCP mode
psql  --host=1.2.3.4.5 --username=postgres  --dbname=${database}

That because i compile oracle_fdw with oracle 10R2 XE server.
When i recompile it with  oracle instant client 11.2  - the error gone away
  
 
( Ubuntu 10.10 , Oracle 10.0.2 XE RDBMS , OracleInstantClient 11.2  PostgreSQL 9.4.0  )

Max.

**Comment by laurenz** [comment]
This is the third report I get of such a problem, see [here](http://pgfoundry.org/forum/forum.php?thread_id=11444&forum_id=1847) and [here](http://lists.pgfoundry.org/pipermail/oracle-fdw-general/2012q3/000026.html).
In both cases the problem "went away" after upgrading from Oracle Client 10.2 to 11.2.

Since you are using Oracle 10.2 as well, I'd say that you are hitting a bug in Oracle 10.2 that has been solved in 11.2.  Unfortunately I don't know which bug that is, I'd really like to find out more.

Is it possible for you to take an SQL Net trace with TRACE_LEVEL=SUPPORT and send it to me per e-mail? Maybe I can see something.

**Comment by laurenz** [comment]
Hmm, actually you are using Oracle client 11.2, so maybe the problem is somewhere else...
As stated, an Oracle Net trace would be helpful.

**Comment by laurenz** [comment]
Did you solve the problem?
Were you able to generate an Oracle Net trace?

**Comment by oracle10gr2** [comment]
Sorry for the delay, Yes i did. I  moved to Instant client 11.2 from RDBMS XE client 10.2. the problem was with 10.2 client

**Comment by laurenz** [comment]
Thanks for the update, good to have a confirmation.
I wish I knew which Oracle bug that is.
But since Oracle 10.2 is probably getting used less and less, this problem will die eventually.
