### ISSUE TITLE
prefetch foreign table

### ISSUE THREAD

**Issue by marielcherkassky** [laurenz/oracle_fdw#195]
Hi,
I saw that there is an option for prefetching number of rows from 200 to more. I tried doing so but I got an error :
 
dbch=# ALTER FOREIGN TABLE tc_sub_rate_ver_prod OPTIONS ( SET prefetch 10240 );
ERROR:  syntax error at or near "10240"
LINE 1: ...N TABLE tc_sub_rate_ver_prod OPTIONS ( SET prefetch 10240 );

dbch=#  alter foreign table tc_sub_rate_ver_prod OPTIONS (SET prefetch '10240');
ERROR:  option "prefetch" not found
 
I have 16G of ram on my server and those  are my parameters :
effective_cache_size = 12GB
work_mem = 128MB
maintenance_work_mem = 4GB
shared_buffers = 4000MB
 
To what size do you recommend to set the value prefetch ? I saw that there is also an option to set PREFETCH_MEMORY/ROWS in the oracle_utils.c file but I didn’t find where.
 
Please advice if you can, Thanks, Mariel

**Comment by laurenz** [comment]
As you have found out, the value of an option must be a string, so `'10240'` is correct.

The second statement fails because `SET` can only be used if the option is already used. To add a new option, use `ADD`:

    ALTER FOREIGN TABLE tc_sub_rate_ver_prod OPTIONS (ADD prefetch '10240');

In older versions of oracle_fdw there used to be options to set both `OCI_ATTR_PREFETCH_ROWS` and `OCI_ATTR_PREFETCH_MEMORY`, but I decided that was too complicated and also triggered an Oracle bug in some versions, so now you can only set the former. You must have been looking at an old version of `oracle_utils.c`.

**Comment by marielcherkassky** [comment]
This option should increase number of rows ferched in one time isnt it ? So
its seems that it will improve selects from foreign tables. Am I wrong?

בתאריך 1 בספט׳ 2017 08:05,‏ "Laurenz Albe" <notifications@github.com> כתב:

**Comment by laurenz** [comment]
Yes, that's the idea.

However, `SELECT` performance will not increase beyond a certain &ldquo;optimal&rdquo; value.
If you set the parameter too high, buffering the rows will consume a lot of memory on the client, and performance will degrade.

So try and experiment to find the value that is best for your table.
