### ISSUE TITLE
Converting uuid and jsonb Types

### ISSUE THREAD

**Issue by bsislow** [laurenz/oracle_fdw#199]
Hello,

We are not able to convert the following data types from PG to Oracle - jsonb and uuid.

We get the following type of error:
ERROR:  column "xxxx" of foreign table "test" cannot be converted to or from Oracle data type

The following conversion types were tested:

PG source: jsonb
Oracle target: clob

PG source: uuid
Oracle target: char, varchar, long/raw

Do you have any recommendations for this?

PG version - 9.6.2
Oracle version - 12.1 (soon to be 12.2 which will support JSON data types...)

**Comment by laurenz** [comment]
You can map an Oracle `RAW` column to a PostgreSQL `uuid` column already.
I chose that data type because the Oracle function [`SYS_GUID()`](http://docs.oracle.com/database/122/SQLRF/SYS_GUID.htm#SQLRF06120) produces `RAW`, so I assumed that UUID values would usually be stored in `RAW` columns (which is also most efficient as far as storage is concerned).

I don't see much value in directly supporting other Oracle data types; you can always use `text` in PostgreSQL if you want to map a UUID column that is `VARCHAR2` or `CHAR` in Oracle and not lose anything.

As far as Oracle's JSON support is concerned, Oracle stores JSON as `VARCHAR2`, `CLOB` or `BLOB`, so it should not be too hard to map at least the first two to PostgreSQL `json`. Maybe I should do that. I don't know if `jsonb` would cause problems.

But again, you could work around the lack of `json` support by using `text` in PostgreSQL, right?

**Comment by bsislow** [comment]
Thanks!

We cannot change the source PG data types so the last comment is not applicable.

How hard would it be for you to produce a new release that handles jsonb to Oracle? This is preventing us moving forward.

**Comment by bsislow** [comment]
Thank you. Can you provide an example of the type cast as we do not have extensive experience with this?

**Comment by laurenz** [comment]
Sure. First, the table definition in Oracle:

    CREATE TABLE jsontest(
       id NUMBER(5) CONSTRAINT jsontest_pkey PRIMARY KEY,
       doc CLOB CONSTRAINT jsontest_doc_check CHECK (doc IS JSON)
    );
    INSERT INTO jsontest VALUES (1, '{ "a": 100, "b": 200 }');
    COMMIT;

Then the foreign table in PostgreSQL:

    CREATE FOREIGN TABLE jsontest (
       id integer OPTIONS (key 'true') NOT NULL,
       doc text
    ) SERVER oracle OPTIONS (table 'JSONTEST');

Now I insert a row with a `jsonb` value:

    INSERT INTO jsontest VALUES (2, '{ "a": 10, "b": 20 }'::jsonb);

Select from the foreign table to check that all is well:

    SELECT * FROM jsontest;

     id |          doc
    ----+------------------------
      2 | { "a": 10, "b": 20 }
      1 | { "a": 100, "b": 200 }
    (2 rows)

**Comment by bsislow** [comment]
Thanks! We've modeled our setup in a similar fashion. You may close this case.

**Comment by laurenz** [comment]
I have added support for `json` and `jsonb` in commit 7723dbeb20e83c8e532227e2faff94f28eb60a21.

**Comment by bsislow** [comment]
Thank you!
