### ISSUE TITLE
Problems installing on Oracle Linux

### ISSUE THREAD

**Issue by GustNan** [laurenz/oracle_fdw#205]
Hello.
First of all, thank you for your work, we really love oracle_fdw here.
We utilize oracle_fdw on two different instalations, Ubuntu 14.04 Postgresql 9.3 and Ubuntu 16.04 Postgresql 9.5, both working perfectly.
Because of a specific software requirement, we are needing to run Postgresql on an Oracle Linux Server release 7.3 Server, but when we try to execute the "CREATE EXTENSION oracle_fdw;" command we are receiving the message: ERROR: could't load library ""/usr/pgsql-9.3/lib/oracle_fdw.so": /usr/pgsql-9.3/lib/oracle_fdw.so: undefined symbol: errcontext" .
Could this be something related with the OS?
Thank you in advance.

**Comment by laurenz** [comment]
This suggests that `oracle_fdw.so` was built against PostgreSQL 9.2 or earlier.
Since 9.3 (more precisely, since commit https://github.com/postgres/postgres/commit/dbdf9679d7d61b03a3bf73af9b095831b7010eb5) `errcontext` is a macro rather than a function.

You should build oracle_fdw on the machine and against the PostgreSQL version where you plan to install it.

**Comment by laurenz** [comment]
I assume that this fixes the problem, so I'll close the issue. Reopen it if the problem persists!

**Comment by rnicolae69** [comment]
Hello. 
Thank you for your job and support.
I found some days ago this wrapper and tried to install, but somethgin went wrong.
I'm stucked in this error:
"oracle_fdw.c:8:22: fatal error: postgres.h: File o directory non esistente" 
Anyone can help?
Should I open another thread?
Thank you very much for helping.
