### ISSUE TITLE
Oracle growing SQLArea causes server to performance drop down

### ISSUE THREAD

**Issue by realyota** [laurenz/oracle_fdw#206]
I make a tons of little sql queries for foreign table like:

`select * from fdw_ora_table where category = 1`

Every query makes a new record in v$sqlarea which is a problem when I need to process 1 milion categories. I can parametrized a const in where clause by making this change:

`select * from fdw_ora_table where category = (select 1)`

But I don't want to rewrite all my sql queries involving oracle fdw tables.  I make some changes to the code making `T_Const` to be seen as `T_Var` treaten like a parameter in `deparseExpr`  but I'm wondering if it's the way I should solve this problem?

**Comment by laurenz** [comment]
This is an Oracle problem caused by their design choice to retain parsed statements in a shared memory area.

There are two options:

1. Rewrite your statements to use parameters. Then the statements oracle_fdw sends to Oracle will also contain parameters (at least after the sixth execution), and Oracle can reuse its cursors. This is what Oracle recommends in [its documentation][1].

2. Set [`CURSOR_SHARING`][2] to `FORCE`. [Oracle thinks that this is not a good idea][3], but if you are not willing to change your code, it might be a possible solution.

[1]: https://docs.oracle.com/database/121/TGSQL/tgsql_cursor.htm#GUID-3C4E8893-02F2-40C3-A485-4BE066A67921
[2]: http://docs.oracle.com/cd/E11882_01/server.112/e40402/initparams044.htm
[3]: https://docs.oracle.com/database/121/TGSQL/tgsql_cursor.htm#GUID-7FF4E133-06A7-401E-9BFC-3B0B9C902346

**Comment by realyota** [comment]
Yes, I thought so. Thank you for sharing, I think the best way will be rewriting my statements after all.
