### ISSUE TITLE
Windows 10, PostgreSQL 10, oracle 12c2, oraclefdw 2 : postgres crash with exception 0xC0000005 when select on Foreign Tables 

### ISSUE THREAD

**Issue by omistler** [laurenz/oracle_fdw#212]
When executing sql request on foreign tables, 

- When executing the request after the connection on a new table it might crash
- If it didn't crash the first time the table has been requested it seems that it won't crash afterward when doing the same request on the same table
- But, if trying to request a new table, it might crash.

I didn't find any deterministic execution sequence to reproduce the error.
It generally crashes after 2 to 5 requests executed:

Below a list of requests that triggered the error
```
C:\Users\GM>psql -U adm -d HST
psql (10.0)
Attention : l'encodage console (850) diffère de l'encodage Windows (1252).
            Les caractères 8 bits peuvent ne pas fonctionner correctement.
            Voir la section « Notes aux utilisateurs de Windows » de la page
            référence de psql pour les détails.
Saisissez « help » pour l'aide.

HST=#
HST=# select count(*) from cfg.CFG_SEMAINE_TYP_TRAMWAY;
 count
-------
     0
(1 ligne)


HST=# select count(*) from CFG.CFG_LIGNE_TRAMWAY;
 count
-------
     0
(1 ligne)


HST=# select count(*) from CFG.CFG_CALEND_TYPE_TRAMWAY;
la connexion au serveur a été coupée de façon inattendue
        Le serveur s'est peut-être arrêté anormalement avant ou durant le
        traitement de la requête.
La connexion au serveur a été perdue. Tentative de réinitialisation : Échec.
!> select count(*) from cfg.CFG_TYP_SYNT_ETAT_CAR;
```

Here is the configuration

```
HST=# SELECT oracle_diag('cfg');
                                        oracle_diag
--------------------------------------------------------------------------------------------
 oracle_fdw 2.0.0devel, PostgreSQL 10.0, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
(1 ligne)

```

```
HST=# SELECT oracle_diag();
                                                                                    oracle_diag
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 oracle_fdw 2.0.0devel, PostgreSQL 10.0, Oracle client 12.2.0.1.0, ORACLE_HOME=C:\app\ORACLE\product\12.2.0\dbhome_1, TNS_ADMIN=C:\app\ORACLE\product\12.2.0\dbhome_1\network\admin
(1 ligne)
```

:: Server logs 
```
2017-11-09 10:53:16.460 GMT [2616] LOG:  database system is ready to accept connections
2017-11-09 10:57:38.718 GMT [2616] LOG:  server process (PID 10908) was terminated by exception 0xC0000005
2017-11-09 10:57:38.718 GMT [2616] DETAIL:  Failed process was running: select count(*) from CFG.CFG_CALEND_TYPE_TRAMWAY;
2017-11-09 10:57:38.718 GMT [2616] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2017-11-09 10:57:38.718 GMT [2616] LOG:  terminating any other active server processes
2017-11-09 10:57:38.721 GMT [9668] WARNING:  terminating connection because of crash of another server process
2017-11-09 10:57:38.721 GMT [9668] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-11-09 10:57:38.721 GMT [9668] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-11-09 10:57:38.737 GMT [2616] LOG:  all server processes terminated; reinitializing
2017-11-09 10:57:38.761 GMT [10132] LOG:  database system was interrupted; last known up at 2017-11-09 10:53:16 GMT
2017-11-09 10:57:41.385 GMT [10132] LOG:  database system was not properly shut down; automatic recovery in progress
2017-11-09 10:57:41.393 GMT [10132] LOG:  redo starts at 0/4BC26BC0
2017-11-09 10:57:41.393 GMT [10132] LOG:  invalid record length at 0/4BC26BF8: wanted 24, got 0
2017-11-09 10:57:41.393 GMT [10132] LOG:  redo done at 0/4BC26BC0
2017-11-09 10:57:41.451 GMT [2616] LOG:  database system is ready to accept connections
```
Thanks for your help.

**Comment by laurenz** [comment]
If you use a development version of oracle_fdw, please use the latest one.

If that still causes the crash, maybe you can get a stack trace as [described in the PostgreSQL Wiki][1].

Unfortunately I don't have any Windows system in reach...

[1]: https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Windows

**Comment by omistler** [comment]
Hi I thought I had the latest one. I'll download it again and test again.

**Comment by omistler** [comment]
Well I downloaded the last windows 64bit binary version and installed it and I get the same result.
log:
```
2017-11-09 11:27:53.147 GMT [13340] LOG:  server process (PID 10420) was terminated by exception 0xC0000005
2017-11-09 11:27:53.147 GMT [13340] DETAIL:  Failed process was running: select count(*) from cfg.CFG_TYP_SYNT_ETAT_CAR;
2017-11-09 11:27:53.147 GMT [13340] HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2017-11-09 11:27:53.147 GMT [13340] LOG:  terminating any other active server processes
2017-11-09 11:27:53.162 GMT [10548] WARNING:  terminating connection because of crash of another server process
2017-11-09 11:27:53.162 GMT [10548] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-11-09 11:27:53.162 GMT [10548] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-11-09 11:27:53.162 GMT [3148] WARNING:  terminating connection because of crash of another server process
2017-11-09 11:27:53.162 GMT [3148] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2017-11-09 11:27:53.162 GMT [3148] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2017-11-09 11:27:53.202 GMT [13340] LOG:  all server processes terminated; reinitializing
2017-11-09 11:27:53.226 GMT [7324] LOG:  database system was interrupted; last known up at 2017-11-09 11:24:54 GMT
2017-11-09 11:27:56.241 GMT [7324] LOG:  database system was not properly shut down; automatic recovery in progress
2017-11-09 11:27:56.249 GMT [7324] LOG:  redo starts at 0/4BC27090
2017-11-09 11:27:56.366 GMT [7324] LOG:  invalid record length at 0/4C263AC8: wanted 24, got 0
2017-11-09 11:27:56.366 GMT [7324] LOG:  redo done at 0/4C263A90
2017-11-09 11:27:56.366 GMT [7324] LOG:  last completed transaction was at log time 2017-11-09 11:26:27.566419+00
2017-11-09 11:27:56.771 GMT [13340] LOG:  database system is ready to accept connections
```

I will get the stack trace.
Thanks

**Comment by HipDragon** [comment]
I'm also using Windows 64 bit, Postgres 10, and am getting the same crash. The below is more information, hoping this helps. I'm looking into how to get a stack trace from the server.

oracle_diag returns "oracle_fdw 2.0.0, PostgreSQL 10.0, Oracle client 12.1.0.2.0"
oracle_diag('oracle') returns "oracle_fdw 2.0.0, PostgreSQL 10.0, Oracle client 12.1.0.2.0, Oracle server 11.2.0.3.0"

Server log
2017-11-09 11:59:36 CST [4172]: [444-1] user=,db=,app=,client= LOG:  server process (PID 8680) was terminated by exception 0xC0000005
2017-11-09 11:59:36 CST [4172]: [445-1] user=,db=,app=,client= DETAIL:  Failed process was running: select * from co_software;
2017-11-09 11:59:36 CST [4172]: [446-1] user=,db=,app=,client= HINT:  See C include file "ntstatus.h" for a description of the hexadecimal value.
2017-11-09 11:59:36 CST [4172]: [447-1] user=,db=,app=,client= LOG:  terminating any other active server processes

**Comment by omistler** [comment]
Hi Laurenz, 
I reinstalled PostgreSQL, now version 10.1 and same oracle_fdw 2.0, 
I created everything to get the trace dump, but can't find the symbols for PostgreSQL 10.1. 
Would you have any idea where I could find it?
Thanks for your help.

**Comment by omistler** [comment]
And for information the oracle diag is now as follow;
```
HST=# SELECT oracle_diag('cfg');
                                      oracle_diag
---------------------------------------------------------------------------------------
 oracle_fdw 2.0.0, PostgreSQL 10.1, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
```

**Comment by laurenz** [comment]
Thanks.

About the symbols: it depends how you installed PostgreSQL.
If you used the installer from EnterpriseDB, they are in the *.PDB files.

If you built PG yourself, you have to build `--with-debug`.

**Comment by omistler** [comment]
Hi, 

This is the call stack:

![image](https://user-images.githubusercontent.com/14960383/32726061-d7d670b2-c877-11e7-9fcc-ad62c2cbe97d.png)

Would you need other information?
I can provide the zipped VisualStudio dump 70MB.

**Comment by omistler** [comment]
Hi, 

First thing, I just tested it on :
```
HST=# SELECT oracle_diag('cfg');
                                      oracle_diag
----------------------------------------------------------------------------------------
 oracle_fdw 2.0.0, PostgreSQL 9.6.6, Oracle client 11.2.0.3.0, Oracle server 12.2.0.1.0
```
 and didn't reproduce it.
I'll continue the investigation.

**Comment by omistler** [comment]
and with :
```
HST=# SELECT oracle_diag('cfg');
                                      oracle_diag
----------------------------------------------------------------------------------------
 oracle_fdw 2.0.0, PostgreSQL 9.6.6, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
(1 ligne)
```
no error.

**Comment by omistler** [comment]
I have no other extension, everything else is standard.

**Comment by laurenz** [comment]
Ok, that is already very good. I don't think that the Oracle version comes into play (but you never know).

In my opinion, your observation means that it is either a bug in core PostgreSQL or a bug in oracle_fdw that is triggered by PG v10 (or a bug that is in code that is only active in v10).

Can you try with oracle_fdw at commit c015b7b341e841a78cf38302bb055edc9593e889 (that should still build with V10). You can download that [here](https://github.com/laurenz/oracle_fdw/archive/c015b7b341e841a78cf38302bb055edc9593e889.zip).

**Comment by omistler** [comment]
Thanks for the link, 

I'm sorry, but I don't know how to build that on a Windows environment.
I'm using Visual Studio.
Would you have any instructions.

Thanks.

**Comment by laurenz** [comment]
I always did it with `cl` and don't know how to do it with the GUI...

Maybe [this](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_Microsoft_Visual_Studio) information from the Wiki and the links referenced there can help.

This is the script I used to build oracle_fdw on 64 bit Windows with PostgreSQL v10:

    REM needs Visual Studio 2013

    set ORACLE_HOME=C:\MinGW\msys\1.0\home\lanadvall\instantclient64_10_2
    set CODE_DIR=C:\MinGW\msys\1.0\home\lanadvall\oracle_fdw
    set PGSQL_DIR=C:\MinGW\msys\1.0\home\lanadvall\pg64_10

    cl /Ox /GL /Zi /LD /MD /W4 /wd4200 /wd4244 /wd4267 /wd4389 /wd4018 /wd4996 /wd4100 /wd4127 /D_CRT_SECURE_NO_WARNINGS /I %ORACLE_HOME%\sdk\include /I %CODE_DIR% /I %PGSQL_DIR%\include\server\port\win32_msvc /I %PGSQL_DIR%\include\server\port\win32 /I %PGSQL_DIR%\include /I %PGSQL_DIR%\include\server /I %PGSQL_DIR%\include\internal %CODE_DIR%\oracle_fdw.c %CODE_DIR%\oracle_utils.c %CODE_DIR%\oracle_gis.c %PGSQL_DIR%\lib\postgres.lib %ORACLE_HOME%\sdk\lib\msvc\oci.lib

Obviously you have to adapt the paths.

Visual Studio 2013 was used to build the EnterpriseDB binaries, so it is the best choice to avoid problems.

**Comment by omistler** [comment]
Hi, I rebuilt in debug-cassert mode, and it didn't change the error.

**Comment by omistler** [comment]
one more information. since I compiled postgreSql 10.1 from the source in debug mode, the error is now deterministic. I could not execute any request using the fdw.

**Comment by laurenz** [comment]
That's of course good news.

If you can attach a debugger to the backend, it would be interesting to follow the execution of the query and see when `fdwroutine->ShutdownForeignScan` changes value.

Maybe you can set breakpoints at `ExecutorStart()`, `ExecutorRun()`, `ExecutorFinish()` and `ExecutorEnd()` and see when things start getting out of whack.

**Comment by yamatattsu** [comment]
Hi Laurenz, omistler,

I may be wrong but I suppose that following bug is similar to it.
And this postgres.exe's bug was fixed at 13 Nov.
Therefore, it might better to use the source code of head.
 (I mean you can "git clone https://github.com/postgres/postgres.git" and
compile it).

If you want to know more details of bug, you can read below thread on
-hackers:

https://www.postgresql.org/message-id/flat/0A3221C70F24FB45833433255569204D1F80CD13%40G01JPEXMBYT05#0A3221C70F24FB45833433255569204D1F80CD13@G01JPEXMBYT05

I hope it will help you.

-------- Forwarded Message --------
Subject: [HACKERS] [bug fix] postgres.exe crashes with access violation on
Windows while starting up
Date: Fri, 27 Oct 2017 02:10:21 +0000
From: Tsunakawa, Takayuki <tsunakawa.takay@jp.fujitsu.com>
To: pgsql-hackers@postgresql.org <pgsql-hackers@postgresql.org>

Hello,

We encountered a rare and hard-to-investigate problem on Windows, which one
of our customers reported.  Please find the attached patch to fix that.
I'll add this to the next CF.


PROBLEM
==============================

PostgreSQL sometimes crashes with the following messages.  This is
infrequent (but frequent for the customer); it occurred about 10 times in
the past 5 months.

LOG:  server process (PID 2712) was terminated by exception 0xC0000005
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal
value.
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the
current transaction and exit, because another server process exited
abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and
repeat your command.
LOG:  all server processes terminated; reinitializing

"server process" shows that an client backend crashed.  The above messages
indicate that the process was not running an SQL command.

PostgreSQL runs as a Windows service.

No crash dump was produced anywhere, despite the facts:
- <PGDATA>/crashdumps folder exists and is writable by the PostgreSQL user
account (which is the user postgres.exe runs as)
- The Windows registry configuration allows dumping the crash dump


CAUSE
==============================

We believe WSAStartup() in main.c failed.  The only conceivable error is:

WSAEPROCLIM
10067
Too many processes.
A Windows Sockets implementation may have a limit on the number of
applications that can use it simultaneously. WSAStartup may fail with this
error if the limit has been reached.

But I couldn't find what the limit is and whether we can tune it.  We
couldn't reproduce the problem.

When I pretend that WSAStartup() failed while a client backend is starting
up, I could see the same phenomenon as the customer.  This problem only
occurs when PostgreSQL runs as a Windows service.

The bug is in write_eventlog().  It calls pgwin32_message_to_utf16() which
in turn calls palloc(), which requires the memory management system to be
set up (CurrentMemoryContext != NULL).


FIX
==============================

Add the check "CurrentMemoryContext != NULL" in write_eventlog() as in
write_console().


NOTE
==============================

The reason is for not outputing the crash dump is a) the crash occurred
before installing the Windows exception handler
(pgwin32_install_crashdump_handler() call) and b) the effect of the
following call in postmaster is inherited in the child process.

/* In case of general protection fault, don't show GUI popup box */
SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX);

But I'm not sure in what order we should do
pgwin32_install_crashdump_handler(), startup_hacks() and steps therein,
MemoryContextInit().  I think that's another patch.

Regards
Takayuki Tsunakawa





2017-11-14 4:30 GMT+09:00 Laurenz Albe <notifications@github.com>:

**Comment by laurenz** [comment]
Thanks for chiming in, Tatsuro.

You are talking about [this commit][1], right?

I don't think that's related, because it is a problem during startup.
What we're facing here is very likely a smashed heap later in the game, during query execution.

It could be a PostgreSQL bug, but also one of oracle_fdw...

[1]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=e02571b73f2d8124fe75d7408f9b63d4c5fe03b0

**Comment by omistler** [comment]
Ok, I built the c015b7b commit and I didn't reproduce the error.

```
HST=# SELECT oracle_diag('cfg');
                                        oracle_diag
--------------------------------------------------------------------------------------------
 oracle_fdw 2.0.0devel, PostgreSQL 10.1, Oracle client 12.2.0.1.0, Oracle server 12.2.0.1.0
```

**Comment by omistler** [comment]
NB for Tatsuro,  I didn't manage to build the last version of PostgreSQL.
```
"C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\pgsql.sln" (cible par défaut) (1) ->
"C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\plpgsql.vcxproj" (cible par défaut) (2) ->
"C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj" (cible par défaut) (3) ->
(ClCompile cible) ->
  c1 : fatal error C1083: Impossible d'ouvrir le fichier source : 'src/backend/bootstrap/bootparse.c' : No such file or direct
ory [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  c1 : fatal error C1083: Impossible d'ouvrir le fichier source : 'src/backend/parser/gram.c' : No such file or directory [C:\
Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  c1 : fatal error C1083: Impossible d'ouvrir le fichier source : 'src/backend/parser/scan.c' : No such file or directory [C:\
Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\src\include\parser/gramparse.h(29): fatal error C1083: Im
possible d'ouvrir le fichier include : 'parser/gram.h' : No such file or directory (compilation du fichier source src/backend/
parser/parser.c) [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  c1 : fatal error C1083: Impossible d'ouvrir le fichier source : 'src/backend/replication/repl_gram.c' : No such file or dire
ctory [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  c1 : fatal error C1083: Impossible d'ouvrir le fichier source : 'src/backend/replication/syncrep_gram.c' : No such file or d
irectory [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  src/backend/utils/misc/guc.c(10506): fatal error C1083: Impossible d'ouvrir le fichier include : 'guc-file.c' : No such file
 or directory [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]
  C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\src\include\parser/gramparse.h(29): fatal error C1083: Im
possible d'ouvrir le fichier include : 'parser/gram.h' : No such file or directory (compilation du fichier source src/common/k
eywords.c) [C:\Users\Gregory Mistler\Downloads\postgres-master\postgres-master\postgres.vcxproj]

...
```

**Comment by yamatattsu** [comment]
Hi Laurenz,

> Thanks for chiming in, Tatsuro.
>

My pleasure.


> You are talking about this commit
> <https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=e02571b73f2d8124fe75d7408f9b63d4c5fe03b0>,
> right?
>

Right!

I don't think that's related, because it is a problem during startup.
> What we're facing here is very likely a smashed heap later in the game,
> during query execution.
>
> It could be a PostgreSQL bug, but also one of oracle_fdw...
>
Hmm.... I see.
I seem to have jumped to the conclusion because these message looks like
same.
I guess that the cause is related in memory context (?), however I'm not
sure how to investigate it.

#Reported by omistler
LOG:  server process (PID 10908) was terminated by exception 0xC0000005
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal
value.
LOG:  terminating any other active server processes

#Reported by Tsunakawa
LOG:  server process (PID 2712) was terminated by exception 0xC0000005
HINT:  See C include file "ntstatus.h" for a description of the hexadecimal
value.
LOG:  terminating any other active server processes

**Comment by yamatattsu** [comment]
Ooops.
I have no experiece to build on winedows, however, How about to use "clean.bat"
before build the source code?

17.1.4. Cleaning and Installing

https://www.postgresql.org/docs/10/static/install-windows-full.html#idm46428701451760


2017-11-14 18:04 GMT+09:00 omistler <notifications@github.com>:

**Comment by chrullrich** [comment]
No, these build errors are caused by missing bison and flex. The missing files are exactly the lexers/parsers.

**Comment by laurenz** [comment]
> Ok, I built the c015b7b commit and I didn't reproduce the error.

That's great news!
But it means more work for you :^(
Can you figure out which commit is to blame?
The easiest way to do this is to install git, clone the repository and use "git bisect".
You start with a commit you know to be good and one that you know to be bad.
git then automatically chooses a commit in the middle and checks that out.
Then you get to build and run oracle_fdw and tell git if the commit was good or bad.
In the end, you know which commit broke the code.

If that's too hard, you can also try the most likely culprits: 899e48b91c4a35cbaa7ea67f957022e51c259a7c and 330979f85bcaff7a78a02f266449173aaa590b10 (no blame on you Tatsuro, those are just the biggest changes). If it works right before the commit, but breaks afterwards, we have found it.

Sorry to bother you with this, but the better we can narrow it down, the more chance we have to find the bug. Memory smashing bugs are notoriously hard to find.

**Comment by omistler** [comment]
I already tested dd5bd53 and no error

**Comment by omistler** [comment]
Ok,
what I found is that, I built the current version of oracle_fdw, and I don't reproduce the error with my own built dll.

**Comment by yamatattsu** [comment]
Hi chrullrich,

Thanks!

2017-11-14 18:42 GMT+09:00 chrullrich <notifications@github.com>:

**Comment by omistler** [comment]
For your information, the library I generated is quite smaller than the release you provided.
as you can see below. 
the  oracle_fdw.

- dll is the one I downloaded,
- the oracle_fdw.dll.current is the one I built with the current version of the source
- the oracle_fdw.dll.nonDebug is the one I built without the /Zi flag

```
18/09/2017  11:11           371 499 oracle_fdw.dll
14/11/2017  10:59           182 784 oracle_fdw.dll.current
14/11/2017  11:26           179 712 oracle_fdw.dll.nonDebug
```

**Comment by laurenz** [comment]
Hmm. I have no idea why that is so, because I know so little about MSVC.

I told you the command I used to build the binary using Visual Studio Express Edition, maybe you can spot the difference.

The facts that

1. My `oracle_fdw.dll` always crashes with your custom built PostgreSQL.

2. Your 'oracle_fdw.dll` always works with your PostgreSQL.

makes me think that maybe there is a problem with the MSVC version.
What version of Visual Studio are you using?
2013? If not, that *might* explain the facts 1. and 2. above.
I don't think it is good to build PostgreSQL and an extension with different MSVC versions.

If that is indeed the problem, it might be a secondary problem that masks the original problem you reported.

Questions:

- For the original case that occasionally failed, did you use EnterpriseDBs binaries (they are built with MSVC 2013).

- Are all the crashes that you see always at the same point in the code?

**Comment by omistler** [comment]
- I used MSVC 2015 to build either PostgreSQL and the library.
- for the oracle_fdw, I used the command you gave me.
- Crashes that I witnessed in debug mode are always at the same place and the value for the shutdownForeignScan pointer is the same as in the captured screen I provided . But I have been able to get the information of the crash **only** from the PostgreSQL version I built in debug mode. And in this version, the crash is deterministic. first foreign SQL request is crashing PostgreSQL,
- When I used the EDB PostgreSQL with the oracle_fdw.dll you provided, it was not deterministic and was happening between the 2nd and 5th execution. but I couldn't have the debug information.

**Comment by chrullrich** [comment]
I just looked at the screenshot for the first time, and there is something interesting about the invalid value of `fdwroutine->ShutdownForeignScan` (0xcdcdcdcdcdcdcdcd). This pattern (0xcd) is what the Microsoft CRT (the debug variant) uses to fill newly allocated blocks [1]. 

So a debug build reproducibly crashes and a release build (where the CRT allocator itself does not initialize anything) does not. As unlikely as it may be in such well-tested code, I think this indicates that the PostgreSQL `memset()` implementation does not initialize the whole of the structure. If the problematic pointer then happens to be `NULL` where it happens, it works regardless.

If this value is always there when the combination of EDB PostgreSQL and the "official" oracle_fdw build crashes, then it indicates that part of the structure is not being initialized, or that something is allocated on top of it. Since we can see from the screenshot that the unassigned structure elements are _not_ 0xcd, and the `makeNode` macro looks bulletproof as to zeroing the whole allocation, the "allocated on top" case is more likely, as unlikely as it is in absolute terms.

@omistler, could you try a PostgreSQL debug build with the original oracle_fdw and set a conditional breakpoint on the line in `src/include/nodes/nodes.h`, in the `newNode()` macro (the non-gcc version) that breaks when an FdwRoutine node is being created (no idea what the tag value is)? Just after the call to `palloc0fast()`. When that gets hit, check whether the ShutdownForeignScan pointer is actually zeroed out by that point. If it is, then try the original PostgreSQL release build with a debug build of oracle_fdw (using /Od /Zi instead of /Ox), put a break point in `oracle_fdw_handler()` and check the same there.

[1] https://msdn.microsoft.com/en-us/library/974tc9t1.aspx

**Comment by laurenz** [comment]
Thanks for your &ndash; as always &ndash; valuable insight.

I didn't dare suspect that `palloc0fast` might be buggy.
Looking at `struct FdwRoutine`, one sees that `ShutdownForeignScan` is defined close to the end, so if there were "to few" bytes zeroed, the result would indeed be like what we see here.

In HEAD, `sizeof(FdwRoutine)` is 296 on 64-bit Linux (probably similar on Windows). If only the first 256 bytes were zeroed, that would leave the last 4 pointers uninitialized, and `ShutdownForeignScan` is among these. That's just idle dreaming at this point, or do you see how `palloc0fast` might behave that way?

**Comment by omistler** [comment]
I tried, to add a breakpoint in :
![image](https://user-images.githubusercontent.com/14960383/32785813-b533da8c-c952-11e7-9c83-45721731900d.png)

but I never reach this breakpoint.  
Visual gives a warning once I've linked the project to the process that  no code would reach this line.

**Comment by laurenz** [comment]
Does it work if you set the breakpoint at `oracle_fdw_handler` and step into `makeNode`?

That will only be executed once per session, the first time you use a foreign table.

I don't know if you can set breakpoints on code that is dynamically loaded...

**Comment by chrullrich** [comment]
As long as the code file matches what the dynamically loaded module was built from, it will be enabled as soon as the DLL is loaded.

**Comment by laurenz** [comment]
After more meditation, I wonder how this can be a problem of incomplete zeroing of `FdwRoutine`. If that were so, how could it work a couple of times and then suddenly fail? The value should not change.

I still believe that there is a bug *somewhere* that inadvertedly scribbles on the `FdwRoutine` struct (buffer overrun?), but where the bug is is a mystery.

**Comment by omistler** [comment]
Is it possible that the struct has been redefined in PostgreSQL and you
didn't build oracle_fdw with the right PostgreSQL includes?

**Comment by laurenz** [comment]
Each PostgreSQL module like oracle_fdw has a "magic number", and it wouldn't load if it were built for a different PostgreSQL version...
I don't see how I could have messed that up.

**Comment by chrullrich** [comment]
The layout of struct FdwRoutine has been unchanged since a commit on 2017-08-30, 16 days before the release of oracle_fdw 2.0.0. PG_MODULE_MAGIC includes (PG_VERSION_NUM / 100), and that value has not changed since HEAD became 10.0devel in August 2016.

So if you built 2.0.0 against includes that were more than 16 days old, you missed a change that inserted `ReInitializeDSMForeignScan` four places from the end of the struct.

However, there would probably be way more reports of crashes on 10 if that was the reason.

**Comment by omistler** [comment]
That seems coherent to me. It would mean that there are just no bug. Could you have a go at rebuilding the library and I can test it against my environment?

**Comment by laurenz** [comment]
Good theory.

Unfortunately I cannot check against which exact version I built the binaries. I have changed job since.
All I know is that it was before 10.0. If I built against Beta4, we would have the explanation, since that commit went in later.

Unfortunately I don't have Windows at my new job and can't rebuild the library.
I'll see what I can do about getting a Windows build environment, but it won't be real soon now.

Can you live with building your own binary in the mean time?

I can well imagie that you are just the first to notice that &ndash; PostgreSQL v10 is still pretty new, and a lot of people don't bother to report bugs.

**Comment by chrullrich** [comment]
I'm probably out of my mind, but ...

... believe it or not, it looks like that is exactly what happened. However, it is not the reason for @omistler's problems because it also happens when rebuilding from current sources.

Disassembly of oracle_fdw.dll, release 2.0.0:

    oracle_fdw_handler:
      000000018000E0B0: 48 83 EC 28        sub         rsp,28h
      000000018000E0B4: 48 8B 0D E5 05 01  mov         rcx,qword ptr [__imp_CurrentMemoryContext]
                        00
      000000018000E0BB: BA 18 01 00 00     mov         edx,118h
      000000018000E0C0: 48 8B 09           mov         rcx,qword ptr [rcx]
      000000018000E0C3: FF 15 D7 03 01 00  call        qword ptr [__imp_MemoryContextAllocZeroAligned]
 
Note the allocation size at ...E0BB: 0x118 = 280. 280 / 8 = 35, the number of elements the struct is expected to hold, with four bytes padding after the NodeTag.

Definition of struct FdwRoutine as of 2017-09-15, the state after the commit on 2017-08-30:

	typedef struct FdwRoutine
	{
	1	NodeTag		type;

		/* Functions for scanning foreign tables */
	2	GetForeignRelSize_function GetForeignRelSize;
	3	GetForeignPaths_function GetForeignPaths;
	4	GetForeignPlan_function GetForeignPlan;
	5	BeginForeignScan_function BeginForeignScan;
	6	IterateForeignScan_function IterateForeignScan;
	7	ReScanForeignScan_function ReScanForeignScan;
	8	EndForeignScan_function EndForeignScan;

		/*
		 * Remaining functions are optional.  Set the pointer to NULL for any that
		 * are not provided.
		 */

		/* Functions for remote-join planning */
	9	GetForeignJoinPaths_function GetForeignJoinPaths;

		/* Functions for remote upper-relation (post scan/join) planning */
	10	GetForeignUpperPaths_function GetForeignUpperPaths;

		/* Functions for updating foreign tables */
	11	AddForeignUpdateTargets_function AddForeignUpdateTargets;
	12	PlanForeignModify_function PlanForeignModify;
	13	BeginForeignModify_function BeginForeignModify;
	14	ExecForeignInsert_function ExecForeignInsert;
	15	ExecForeignUpdate_function ExecForeignUpdate;
	16	ExecForeignDelete_function ExecForeignDelete;
	17	EndForeignModify_function EndForeignModify;
	18	IsForeignRelUpdatable_function IsForeignRelUpdatable;
	19	PlanDirectModify_function PlanDirectModify;
	20	BeginDirectModify_function BeginDirectModify;
	21	IterateDirectModify_function IterateDirectModify;
	22	EndDirectModify_function EndDirectModify;

		/* Functions for SELECT FOR UPDATE/SHARE row locking */
	23	GetForeignRowMarkType_function GetForeignRowMarkType;
	24	RefetchForeignRow_function RefetchForeignRow;
	25	RecheckForeignScan_function RecheckForeignScan;

		/* Support functions for EXPLAIN */
	26	ExplainForeignScan_function ExplainForeignScan;
	27	ExplainForeignModify_function ExplainForeignModify;
	28	ExplainDirectModify_function ExplainDirectModify;

		/* Support functions for ANALYZE */
	29	AnalyzeForeignTable_function AnalyzeForeignTable;

		/* Support functions for IMPORT FOREIGN SCHEMA */
	30	ImportForeignSchema_function ImportForeignSchema;

		/* Support functions for parallelism under Gather node */
	31	IsForeignScanParallelSafe_function IsForeignScanParallelSafe;
	32	EstimateDSMForeignScan_function EstimateDSMForeignScan;
	33	InitializeDSMForeignScan_function InitializeDSMForeignScan;
	34	ReInitializeDSMForeignScan_function ReInitializeDSMForeignScan;
	35	InitializeWorkerForeignScan_function InitializeWorkerForeignScan;
	36	ShutdownForeignScan_function ShutdownForeignScan;
	} FdwRoutine;

36 elements, by my count. Using the debug CRT allocator, the memory layout would have four sentinel bytes (0xcd) after the struct, most likely followed by another four at the start of the next allocation, giving us a nice 64-bit pointer consisting entirely of 0xcd.

Unfortunately, if it were that simple, then the observed behavior where it always crashes with *newly* built binaries could not occur.

@omistler, can you please run this:

    set _NT_SYMBOL_PATH=(wherever the .pdb file for your debug build of oracle_fdw.dll is)
    dumpbin /disasm oracle_fdw.dll > oracle_fdw.i

Then look in oracle_fdw.i for the block starting `oracle_fdw_handler:` like I quoted above, and check whether there is a 0x118 or 0x120 operand just after that.

**Comment by omistler** [comment]
@chrullrich, when I rebuilt oracle_fdw, it stopped crashing.
It is always crashing when I kept the provided oracle_fdw and rebuilt in debug mode PostgreSQL. This is when in debug mode the initialised variables are set as CDCDCD. and because the memory is not allocated for the FdwRoutine struct, it is, I think used for something else.

**Comment by omistler** [comment]
I can live for the time with my own built version of oracle_fdw,  but I would need a proper version that I can include in my project without having to build it from source to have a proven stable environment.

Thanks guys.

**Comment by laurenz** [comment]
I'll put it on my agenda to get a Windows build environment.

Any chance that somebody with Visual Studio 2013 could build binaries for PostgreSQL v10 for me? Then I could replace the buggy binaries.

In the mean time I should remove them, so that nobody downloads the buggy binaries.

@chrullrich, thanks again for your invaluable contribution, without which we wouldn't have got to the bottom of this.
Not only oracle_fdw, but the whole PostgreSQL projects profits immensely from having a Windows hacker like you.  It seems to be a rare species!

**Comment by laurenz** [comment]
I have published new binaries that @chrullrich provided. Thanks!
