### ISSUE TITLE
DATE / TIMESTAMP conversion in oracle

### ISSUE THREAD

**Issue by josser** [laurenz/oracle_fdw#222]
Hi!
I'm trying to optimize some queries and found something which I can't understand. 

I have found that oracle_fdw set NSL_DATE_FORMAT to 'YYYY-MM-DD HH24:MI:SS BC';
So, resulting query may looks like: 
```WHERE (r1.“created_at” >= CAST(‘2017-12-12 08:15:59.000000 AD’ AS TIMESTAMP));```
explain for this query told me that no indexes is used for this query. 
However I have it and when I changed query to something like: 
```WHERE (r1.“ created_at” >= TO_DATE(‘2017-12-12 08:15:59.000000 AD’, ‘YYYY-MM-DD HH24:MI:SS BC’))```  
index started to work. 

So, the question is: is there any difference between CAST and TO_DATE? 
I'm not a big expert in oracle, maybe if to_date can be used by indexes it would be better to use it instead of cast?

**Comment by josser** [comment]
Ok! I figure out that TIMESTAMP and DATE types are not same thing in oracle.
So, oracle_fdw translate everything with 'time' to timestamp. 
But our db is using DATE and it looks like this is the reason why oracle can't use index.

**Comment by josser** [comment]
So, If I can't modify oracle DB than I have to have somehow to force oracle_fdw cast to DATE instead of TIMESTAMP. Is this possible?

**Comment by laurenz** [comment]
If you use `EXPLAIN (VERBOSE)`, you probably see a plan like

    SELECT STATEMENT
      TABLE ACCESS FULL DATETEST  (filter INTERNAL_FUNCTION("R1"."CREATED_AT")=CAST(TIMESTAMP' 2017-12-12 08:15:59.000000000' AS TIMESTAMP))

The problem occurs because you are comparing with a PostgreSQL `timestamp` value.
You cannot avoid that because you need the "time" part, but if you compared with a `date`, you would get:

    SELECT STATEMENT
      TABLE ACCESS BY INDEX ROWID DATETEST
        INDEX RANGE SCAN DATETEST_IDX (condition "R1"."CREATED_AT"=CAST(TO_DATE(' 2017-12-12 00:00:00', 'syyyy-mm-dd hh24:mi:ss') AS DATE))

What is crippling here is that `INTERNAL_FUNCTION`. it is Oracle's representation of a type conversion.

Normally I'd recommend that you create a function based index in Oracle, but as far as I can tell there is no way in Oracle to index such an expression.

Looks like quite a tight spot you're in.
PostgreSQL cannot have times in a `date`, and oracle_fdw has no way to tell that the timestamp you give it is to be converted to a `DATE` in Oracle...

Not really a great help, but what if you change the condition to

    WHERE created_at = '2017-12-12 08:15:59.000000 AD'::timestamp
      AND created_at BETWEEN '2017-12-12'::date AND '2017-12-13'::date

Then an index can be used, and you would avoid a sequential scan.

**Comment by josser** [comment]
Cool, this last trick with dates may did the job. Will try this
Thank you!
