### ISSUE TITLE
Does this extension work with Postgres 10 yet?

### ISSUE THREAD

**Issue by gchaika** [laurenz/oracle_fdw#225]
I'm trying to install this on postgres 10 but I'm getting the following:

ERROR: incompatible library "/usr/pgsql-10/lib/oracle_fdw.so": version mismatch
DETAIL: Server is version 10, library is version 9.6.

**Comment by laurenz** [comment]
oracle_fdw works with PostgreSQL v10.

You'll have to build the extension with PostgreSQL v10 to get it to work &ndash; your oracle_fdw is obviously built with PostgreSQL 9.6.

There is a safeguard to keep libraries from loading into a PostgreSQL server with a different major version than the one they were built with, because this would lead to all kinds of trouble with possible non-obvious symptoms.
