### ISSUE TITLE
What is 'key column option'

### ISSUE THREAD

**Issue by dollarklavs** [laurenz/oracle_fdw#228]
Hi Laurenz
In your documentation you say this about INSERTS:
_For UPDATE and DELETE to work, the columns corresponding to the primary key columns of the Oracle table must have the key column option set. These columns are used to identify a foreign table row, so make sure that the option is set on all columns that belong to the primary key._

Does this mean that there is a  special option on the foreign table definition that has to be defined (on the postgres side)?

I can't get INSERTS to work with a column thats defined as:
`OBJECTID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 ORDER NOCACHE) PRIMARY KEY,
` on the oracle side and `objectid numeric NOT NULL` on the postgres side.

**Comment by laurenz** [comment]
The `key` column option is necessary fur `DELETE` and `UPDATE`, but not for `INSERT`.

You define it like this:

    CREATE TABLE ... (
       objectid integer OPTIONS (key 'true') NOT NULL,
       ...
    );

Oracle columns defined as `GENERATED ALWAYS AS IDENTITY` will cause a problem with oracle_fdw, because oracle_fdw will always try to insert a value into the column, which will lead to an error message.

You could either define a view in Oracle that excludes the identity column and use that to insert rows from PostgreSQL, or you could define a foreign table based on an SQL query that excludes the identity column:

    CREATE FOREIGN TABLE tab_insert (...) SERVER ...
       OPTIONS (table '(SELECT <all columns except "objectid"> FROM tab)');

This foreign table would be used only for inserts from PostgreSQL, for all other purposes you'd use a regular foreign table that includes all columns.

**Comment by dollarklavs** [comment]
Thanks Laurenz.
I see now that I read the documentation wrong. But thanks for providing a solution anyways.
