### ISSUE TITLE
[Question] Can we update oracle client version without uninstall oracle_fdw?

### ISSUE THREAD

**Issue by taka-miyagishi** [laurenz/oracle_fdw#232]
Hi Laurenz,

I planning to update oracle client to connect currently unsupported oracle server, and I want to do that without uninstall oracle_fdw if I can.
If there is a way to update oracle client version without uninstall oracle_fdw, could you please tell me the way?

Thanks.

**Comment by laurenz** [comment]
It is absolutely no problem to upgrade Oracle client without modifying or uninstalling oracle_fdw, since Oracle claims binary backward compatibility since at least version 10.1, the minimum required for oracle_fdw.

Make sure that the new Oracle client is either installed in the same location, or you configure the shared library path to point to the new location.

**Comment by taka-miyagishi** [comment]
Thank you for your quick reply.
It is good news for me! I'll try it soon. :)

Regards,

**Comment by laurenz** [comment]
Actually, come to think of it, on Linux the Oracle shared library contains the version name, e,g, `libclntsh.so.11.1`.

So you would have to create a symbolic link from the old library name to the new one.

But rebuilding oracle_fdw should be easy too; why are you trying to avoid that?
