### ISSUE TITLE
Can the extension be created in Postgres-XL?

### ISSUE THREAD

**Issue by MyqueWooMiddo** [laurenz/oracle_fdw#233]
Hello

I have already "make && make install " successfully. And the I can find right LD_LIBRARY_PATH and ORACLE_HOME in the env. I also copy all the oracle so and jar into the extension path.

But when I execute "create extension oracle_fdw;" , it told me --- could not load library "/usr/pgxl-9.5/lib/postgresql/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

when I "ldd oracle_fdw.so" ,  there was not any "not found ".

So I'm curious about whether oracle_fdw was adapted to PG-XL?

**Comment by laurenz** [comment]
I have not adapted oracle_fdw to Postgres-XL, nor have I tested that.

I suspect, however, that your problem is a different one.
You'd have to put `LD_LIBRARY_PATH` into the environment *of the PostgreSQL server process*.
If you start PostgreSQL with `pg_ctl start -D ...`, it should pick up the current setting in your shell, but if you start it in a different fashion (e.g., with a startup script during boot), it won't do that.

Therefore, and bacause [`LD_LIBRARY_PATH` is evil][1], it is better to add the directory with the Oracle shared library to `/etc/ld.so.conf` and run `ldconfig`.

 [1]: http://xahlee.info/UnixResource_dir/_/ldpath.html

**Comment by jerome-peng** [comment]
i am use pg10.4(installed by root) on centos6.9.

# yum install oracle-instantclient11.2-basic-11.2.0.4.0-1.x86_64.rpm 
# yum install oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm 

then in the /etc/profile i define the LD_LIBRARY_PATH

I execute "create extension oracle_fdw;" , it told me --- cERROR:  could not load library "/opt/PostgreSQL/10/lib/postgresql/oracle_fdw.so": libclntsh.so.11.1: cannot open shared object file: No such file or directory

when I "ldd oracle_fdw.so" , there was not any "not found ".

so i use 👍 
cat /proc/2617/environ | xargs -0 -n 1 echo | sort

LD_LIBRARY_PATH=/opt/PostgreSQL/10/lib::

so i know where is the problem.

i edit the below file, add "/usr/lib/oracle/11.2/client64/lib " to the pg script.
/etc/rc.d/rc3.d/S85postgresql-10

then i restart pg server, it's ok
