### ISSUE TITLE
Is there a way to query the Foreign Table constants (relationships)?

### ISSUE THREAD

**Issue by WadeBarnes** [laurenz/oracle_fdw#236]
For example, if you run the following query on a database you get a list of the constrains and the table relationships.

```
SELECT
    tc.constraint_name, tc.table_name, kcu.column_name,
    ccu.table_name AS foreign_table_name,
    ccu.column_name AS foreign_column_name
FROM
    information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name;
```

However doing the same on an imported schema produces no results, even though I can list the foreign tables and even query data from them.  The `information_schema.table_constraints` table is empty.

Am I missing something?

**Comment by laurenz** [comment]
That is because there are no constraints on foreign tables (though they can have triggers from 9.4 on).

It wouldn't make sense to have constraints on foreign tables, because PostgreSQL cannot guarantee that these constraints would be satisfied.

But maybe you want to query the *Oracle* constraints and not the PostgreSQL constraints.
These cannot be found in PostgreSQL's catalogs, you'd have to consult the Oracle catalogs for that.
One thing you can do is define a foreign table on Oracle's catalog tables, then you can get this information from PostgreSQL.

**Comment by WadeBarnes** [comment]
Thanks for the information.
