### ISSUE TITLE
GUI Name Issue

### ISSUE THREAD

**Issue by pppedant** [laurenz/oracle_fdw#243]
I am trying to connect to a oracle database which is behind a firewall and I have to make the connection GUI name constant. However, for every query fdw sends a different name with a number at the end like ..XXX..(51).  Guessing that this is the query number.
Is there a way to change this to a constant value so that I can configure at the oracle side to pass firewall.
thank you.

**Comment by laurenz** [comment]
The number is actually the process ID of the PostgreSQL backend process, and since connections are cached for the life time of a database session, that implies that you use a new connection for every query. Maybe you should use a connection pool, but that is off topic and irrelevant for your question.

You can change the behavior of oracle_fdw by patching the code.
The relevant code is in `oracle_utils.c`:

    /* set MODULE for the Oracle session */
    sprintf(pid, "%lu", (unsigned long)getpid());
    pid[29] = '\0';

    if (checkerr(
        OCIAttrSet(userhp, OCI_HTYPE_SESSION, "postgres", (ub4)8,
            OCI_ATTR_MODULE, errhp),
        (dvoid *)errhp, OCI_HTYPE_ERROR) != OCI_SUCCESS)
    {
        oracleError_d(FDW_UNABLE_TO_ESTABLISH_CONNECTION,
            "error connecting to Oracle: OCIAttrSet failed to set module in session handle",
            oraMessage);
    }

    /* set ACTION for the Oracle session */
    if (checkerr(
        OCIAttrSet(userhp, OCI_HTYPE_SESSION, pid, (ub4)strlen(pid),
            OCI_ATTR_ACTION, errhp),
        (dvoid *)errhp, OCI_HTYPE_ERROR) != OCI_SUCCESS)
    {
        oracleError_d(FDW_UNABLE_TO_ESTABLISH_CONNECTION,
            "error connecting to Oracle: OCIAttrSet failed to set action in session handle",
            oraMessage);
    }

Just put something else into `pid`.
