### ISSUE TITLE
Foreign table not refreshing

### ISSUE THREAD

**Issue by mrizzato** [laurenz/oracle_fdw#252]
Hello,
 I have created a foreign table, based on an Oracle view, which worked perfectly at the beginning.
Now I keep getting always the same result set, although if I run the view in Oracle I can verify that the result set in Oracle has changed.
What can I do to force a foreign table refresh?

Regards

**Comment by laurenz** [comment]
There is no such thing as a refresh; you will *always* see the current data in PostgreSQL.

One possibility that comes to my mind is that you did an `INSERT`, `UPDATE` or `DELETE` in Oracle, but forgot to `COMMIT`, so that the change is not visible outside of your transaction.

If that is not the problem, I need more information:

- Is there an error message?
- Can you modify the foreign table via oracle_fdw?

**Comment by mrizzato** [comment]
Hi Laurenz,

Issue solved: missing COMMIT. 
Thank you, and sorry for raising a stupid question.

**Comment by laurenz** [comment]
Never mind, you are not the first one to fall into this trap.
