### ISSUE TITLE
foreign-data wrapper handler function 16616 did not return an FdwRoutine struct

### ISSUE THREAD

**Issue by michailnm** [laurenz/oracle_fdw#261]
Oracle server 12.2.0.1.0 win64
PostgreSQL 10.4 win64
Oracle client 18.1.0.0.0 win64
oracle_fdw 2.0.0 pg10 win64

- install
`CREATE EXTENSION oracle_fdw;`

- setup
```
CREATE SERVER vm_220_oradb_12
FOREIGN DATA WRAPPER oracle_fdw
OPTIONS (dbserver 'vm-220-oradb-tst:1522/orcl12');
GRANT USAGE ON FOREIGN SERVER vm_220_oradb_12 TO postgres;
CREATE USER MAPPING FOR postgres
SERVER vm_220_oradb_12
OPTIONS (user 'devsys', password 'devsys');
```

- verify
`SELECT oracle_diag('vm_220_oradb_12');`
> oracle_fdw 2.0.0, PostgreSQL 10.4, Oracle client 18.1.0.0.0, Oracle server 12.2.0.1.0

- use
```
CREATE FOREIGN TABLE test1 (
NAME VARCHAR(100) NOT NULL
) SERVER vm_220_oradb_12
--OPTIONS (schema 'DEVSYS', table 'TEST1') ;
OPTIONS (table 'TEST1');
select * from test1 ;
```
>foreign-data wrapper handler function 16616 did not return an FdwRoutine struct
```
CREATE SCHEMA ora_devsys;
IMPORT FOREIGN SCHEMA "DEVSYS" from SERVER vm_220_oradb_12 INTO ora_devsys;
```
>foreign-data wrapper handler function 16616 did not return an FdwRoutine struct

how to fix ?

ps from http://www.sql.ru/forum/1298858/iz-postgresql-v-oracle-problemy-s-oracle-fdw
it does not comply with the API requirements for implementing the FDW interface:
https://github.com/postgres/postgres/blob/REL_10_STABLE/src/backend/foreign/foreign.c#L296

**Comment by laurenz** [comment]
oracle_fdw *does* return a `FdwRoutine`, see [the code][1].

There must be something weird going on.

What do you get in `psql` for

    \dew oracle_fdw

Did you build PostgreSQL and oracle_fdw from source?
If no, from where exactly did you get the binaries?
Is this standard PostgreSQL or a fork?

I have never heard of this problem, but if `(((const Node*)(routine))->type)` (which is what `IsA` expands to) does not return the correct value, something must be pretty off. Since `type` is the first member of `struct Node`, it can hardly be an alignment problem.

One suspicion: If oracle_fdw was built against a PostgreSQL with a different `include/server/nodes/nodes.h`, it could be that `enum NodeTag` is different, and the numerical values for the `enum` values differ.

This is all guesswork; maybe things will become clearer if I know how your PostgreSQL and oracle_fdw were built.

I know this is Windows, so debugging is difficult, but it would be valuable to attach a debugger and figure out what exactly the numerical value for the node type in `GetFdwRoutine` is.

 [1]: https://github.com/laurenz/oracle_fdw/blob/master/oracle_fdw.c#L379

**Comment by michailnm** [comment]
oracle_fdw from 
https://github.com/laurenz/oracle_fdw/releases/download/ORACLE_FDW_2_0_0/oracle_fdw-2.0.0-pg10-win64.zip
PostgreSQL  from 
https://repo.postgrespro.ru/win/64/PostgreSQL_10.4_64bit_Setup.exe

maybe a problem in the fresh Oracle client 18.1.0.0.0 win64

I'll try on a clean machine (Win2016) to install the original PostgreSQL
and 12.2.0.1-win-x64-client

PS can in oracle_fdv possibility of debugging logs / information about the error ?

**Comment by michailnm** [comment]
oracle_fdw from 
https://github.com/laurenz/oracle_fdw/releases/download/ORACLE_FDW_2_0_0/oracle_fdw-2.0.0-pg10-win64.zip
PostgreSQL  from 
https://repo.postgrespro.ru/win/64/PostgreSQL_10.4_64bit_Setup.exe

maybe a problem in the fresh Oracle client 18.1.0.0.0 win64

I'll try on a clean machine (Win2016) to install the original PostgreSQL
and 12.2.0.1-win-x64-client

PS can in oracle_fdv possibility of debugging logs / information about the error ?

**Comment by laurenz** [comment]
Ok, that makes it clear.

PostgresPro is not plain PostgreSQL, but a fork. The code was changed so that it is not binary compatible.

You'll have to build oracle_fdw against PostgresPro to have a chance. I hope it will build but cannot give any guarantees since I didn't know how far their modifications go.

Comparison with issue #217 might be instructive, although this is a different problem.
