### ISSUE TITLE
connection problem ORA-21561 OID Generation Failed

### ISSUE THREAD

**Issue by rwer81** [laurenz/oracle_fdw#264]
Hi,
I can connect with sqlplus(client 12)to ora db(oracle 12c) on my Postgresql 9.6(on windows) server with same connection config.
I created extension, server, mapping and foreign table,
But when I select my table it return message:

Error: connection for foreign table 'test' cannot be authenticated
Detail : ORA-21561 : OID Generation Failed.

What can be problem?
Thanks.

**Comment by laurenz** [comment]
Interesting; a new connection error.

A web search has given me [this][link1], [that][link2] and [the other][link3] link that all suggest that the problem has to do with name resolution: either hack the `/etc/hosts` file or make sure then the PostgreSQL process has read access.

Now you are on Windows, so your mileage may vary considerably. The `hosts` file is said to be on `C:\WINDOWS\system32\drivers\etc` on Windows, so you could try out the hacks there.

But since you can connect with sqlplus, I'd rather think that it is a permission problem, and that sqlplus from the command line can access a file that PostgreSQL cannot (it is started as a service, right?).

One interesting thing would be an Oracle SQL*NET trace from the failing connection attempt as described for example [here][trace].

The other thing you can do to shed light on this is to install [Process Monitor][procmon] and trace the problem with it. That will show if files cannot be accessed etc.

 [link1]: https://stackoverflow.com/q/31338916/6464308
 [link2]: https://oracle-admin.com/2014/02/04/oracle-ora-21561-oid-generation-failed/
 [link3]: https://sourceforge.net/p/tora/discussion/52737/thread/f68b89ad/
 [trace]: https://github.com/laurenz/oracle_fdw/issues/139#issuecomment-263266267
 [procmon]: https://download.sysinternals.com/files/ProcessMonitor.zip

**Comment by rwer81** [comment]
I now it is very interesting but my case : 
I can query in a pg sql editor  but another editors fails with above error.
I think it is about session parameters/variables

**Comment by rwer81** [comment]
I think oracle_pwd cannot read machine name 
because in trace file 'auth_machine' is null. 
I tried every combination of hostname in hosts file.

**Comment by laurenz** [comment]
Can you explain in more detail what a &ldquo;pg sql editor&rdquo; is? To me, an &ldquo;editor&rdquo; is a program that is used to modify text files by hand.

If we know when it works and when not, that would certainly help!

`auth_machine` being NULL sounds like that is exactly the problem. This Oracle error message should get the price for the most misleading Oracle error message.

Does the PostgreSQL server process have permissions to read the `hosts` file? Tha's what I'd look for in the process monitor output: Files where access is denied, in particular the `hosts` file.

**Comment by rwer81** [comment]
pg sql editor is "PGADMIN 3 query tool" . postgres.exe services are running with 'SYSTEM' user. And hosts file owner is 'SYSTEM'. I tracked my process and there is no deny for hosts file.

**Comment by laurenz** [comment]
Oh, interesting. So it works with pgAdmin III.

I have seen several cases where people have reported that things work or don't work depending on which client is used. So far, there has never been an explanation why.

I recommend that you run an SQL*Net trace of the case where it works and one where it doesn't.
Comparing these might shed light on the problem.
I'm happy to help you read the trace files.

At any rate, it seems to be a setup problem. Have you considered asking Oracle support how to deal with that error?

**Comment by rwer81** [comment]
I compare working and not working sqlNet trace files row by row.  But everything is same. 
In not working trace file ends before password validation step. 
My Oracle database working with another applications. And there is not any connection problem.

**Comment by laurenz** [comment]
Hmm, weird. I'd have expected some differences in a `SUPPORT` level trace.

If you do the same thing in the working and the bad case are there any observable differences in the Process Monitor trace?

After that, I am out of ideas...

**Comment by laurenz** [comment]
I'll close this for inactivity. Don't hesitate to reopen it if you have new information.
