### ISSUE TITLE
Question: is it possible to specify a schema when use a SELECT for the table?

### ISSUE THREAD

**Issue by mrship** [laurenz/oracle_fdw#297]
I note that when using a `SELECT` query to specify your table, you need to omit the schema. Is it not possible to use SELECT with a different schema to the schema user connecting to the Oracle server?

We have a large table on a different schema that we'd like to reduce using a select, e.g:

```sql
      CREATE FOREIGN TABLE IF NOT EXISTS colleagues (
                id                      character varying(2000) OPTIONS (key 'true')  NOT NULL,
                display_name            character varying(2000),
                title                   character varying(2000)
            ) SERVER admin OPTIONS (
                schema 'BONSAI', 
                table '(SELECT ID, DISPLAYNAME AS DISPLAY_NAME, TITLE FROM ACTIVE_DIRECTORY WHERE GWESTATUS=''active'')', 
                prefetch '5000'
            );
```

**Comment by laurenz** [comment]
Yes, this can easily be done, just qualify the tables in the query with the proper schema name:

    OPTIONS (table '(SELECT ID, DISPLAYNAME AS DISPLAY_NAME, TITLE FROM BONSAI.ACTIVE_DIRECTORY WHERE GWESTATUS=''active'')')

That shouldn't be any more complicated than what you had in mind, and the implementation is much simpler (I don't have to send an extra `ALTER SESSION SET CURRENT_SCHEMA` statement).

If I misunderstood you, and you mean that you want to connect to Oracle as user `BONSAI` rather than just use the tables in that schema (and such a misunderstanding can easily happen, because it is natural for Oracle users to confuse users and schemas), then you would have to use a different user mapping for that. Or grant some privileges in Oracle.

**Comment by mrship** [comment]
Of course! Now I feel a little silly. That works a treat; thanks for the help.
