### ISSUE TITLE
Float to Float4 Issue

### ISSUE THREAD

**Issue by tmathewsNN** [laurenz/oracle_fdw#31]
Hello,

A field in our source is a FLOAT. The field that we've chosen for the foreign table in postgres is a FLOAT4. When pulling back data, the values are slightly off in most cases.

For instance here are 10 examples

COLUMN (FDW)	COLUMN (Oracle)	DIFF
32935140	32935141	1
37645816	37645818	2
33514182	33514182	0
33615264	33615264	0
31862788	31862787	-1
33149166	33149166	0
31849372	31849373	1
33106476	33106475	-1
36868032	36868031	-1

We surmised that the issue was with the type conversion. We tried to use bigint in the foreign table instead and it worked like a charm.

Any thoughts on why it's not converting appropriately?

Thanks!

Oracle - Oracle Database 12c Enterprise Edition Release 12.1.0.1.0 - 64bit Production
PostGres - PostgreSQL 9.4.0, compiled by Visual C++ build 1800, 64-bit
FDW  - Version 1.1

**Comment by laurenz** [comment]
Yes, the problem is obvious and has to do with type names and their difference.
FLOAT in Oracle is the same as NUMBER, which is a "binary coded decimal" and can represent numbers with many significant digits fairly accurately.
FLOAT(n) limits the number of significant (binary) digits, while FLOAT doesn't.

FLOAT4 in PostgreSQL is a 4-byte floating point number in binary representation, and that means that the number of significant digits is quite limited. That explains the "rounding errors" you observe.

You would be much better off using FLOAT8 in PostgreSQL, or NUMERIC, if more precision is required.

The PostgreSQL data type that is most like Oracle FLOAT is NUMERIC, which is also a binary coded decimal.

**Comment by tmathewsNN** [comment]
Ahh, guess we should not have assumed that because of name similarity the data types are the same. Thanks for the great explanation. The FDW has been a great asset for our organization. Thank you.
