### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by monumatik** [laurenz/oracle_fdw#316]
Hi,
I'am trying to install oracle_fdw, but I stuck on installation process.

DEBIAN 9
What i did in steps (every steps on root account):
1) Download and unpack oracle_fdw
2) Download and unpack instantclient-sdk-linux.x64-12.1.0.2.0.zip
3) export $ORACLE_HOME = /home/pratajczak/Pobrane/instantclient_12_2 (inside this folder i see "sdk" folder)
4) Go to oracle_fdw folder and "make"

root@debian:/home/pratajczak/Pobrane/oracle_fdw# make
gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -I/home/pratajczak/instantclient_12_2/sdk/include -I/home/pratajczak/instantclient_12_2/oci/include -I/home/pratajczak/instantclient_12_2/rdbms/public -I/usr/include/oracle/18.5/client -I/usr/include/oracle/18.3/client -I/usr/include/oracle/18.5/client64 -I/usr/include/oracle/18.3/client64 -I/usr/include/oracle/12.2/client -I/usr/include/oracle/12.2/client64 -I/usr/include/oracle/12.1/client -I/usr/include/oracle/12.1/client64 -I/usr/include/oracle/11.2/client -I/usr/include/oracle/11.2/client64 -I/usr/include/oracle/11.1/client -I/usr/include/oracle/11.1/client64 -I/usr/include/oracle/10.2.0.5/client -I/usr/include/oracle/10.2.0.5/client64 -I/usr/include/oracle/10.2.0.4/client -I/usr/include/oracle/10.2.0.4/client64 -I/usr/include/oracle/10.2.0.3/client -I/usr/include/oracle/10.2.0.3/client64 -I. -I. -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o oracle_utils.o oracle_utils.c
oracle_utils.c:22:17: fatal error: oci.h: Nie ma takiego pliku ani katalogu
 #include <oci.h>

**Comment by laurenz** [comment]
I see some errors at first glance:

1. You run as `root`.
   This is not the reason for the problem, but it is something you should never do when building software - any bug in the `Makefile` can potentially destroy your system then.

2. You run

       export $ORACLE_HOME = /home/pratajczak/Pobrane/instantclient_12_2

   instead of

       export ORACLE_HOME=/home/pratajczak/Pobrane/instantclient_12_2

   (having no spaces is important).

3. You need not only the Instant Client &ldquo;SDK&rdquo; files, but also &ldquo;Instant Client basic&rdquo;. Installing &ldquo;sqlplus&rdquo; is also a good idea for debugging the installation process.

Once you have build oracle_fdw, the next challenge will be to get the directory with the Oracle client shared library into the library path for PostgreSQL. Read up in the README and the estimated 10000 issues concerning related problems.

**Comment by monumatik** [comment]
Thanks for response :)

My ORACLE_HOME is now correct.
I installed Instant Client SDK and Client basic to the same folder.
Oracle_fdw is now installed.
"...the next challenge will be to get the directory with the Oracle client shared library into the library path for PostgreSQL."
So, i did this command: export LD_LIBRARY_PATH=/home/pratajczak/Pobrane/instantclient_12_2
and then i ran PostgreSQL.

CRAETE EXTANSION oracld_fdw;
After this command my PostgreSQL is logging:
The connection to the server was lost. Attempting reset: LOG:  server process (PID 1545) was terminated by signal 11: Segmentation fault
DETAIL:  Failed process was running: CREATE EXTENSION oracle_fdw;
LOG:  terminating any other active server processes
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
FATAL:  the database system is in recovery mode
Failed.
!> LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2019-04-30 08:28:04 CEST
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/17B5F70
LOG:  redo is not required
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started

**Comment by laurenz** [comment]
This is unusual.

I won't be able to help you debug this, because you just typed your actions from memory (e.g., there is no `CRAETE EXTENSION` command).

I don't want to sound dismissive, but could you please copy and paste everything you did, beginning with downloading and unpacking oracle_fdw and Instant Client?

That way I have a chance to spot where you went wrong.

**Comment by monumatik** [comment]
0. Logged as root
1. Downloading and unpacking oracle_fdw - /home/pratajczak/Pobrane/oracle_fdw
2. Downloading and unpacking instantclient-basic-linux.x64-12.1.0.2.0.zip, instantclient-sdk-linux.x64-12.1.0.2.0.zip I have unpacked it to the same folder "instantclient_12_1" (home/pratajczak/Pobrane/instantclient_12_1).
3. I have created symlink by command: ln -s libclntsh.so.12.1 libclntsh.so (inside home/pratajczak/Pobrane/instantclient_12_1)
4. I have set environment variable ORACLE_HOME by command: export ORACLE_HOME=/home/pratajczak/Pobrane/instantclient_12_1
5. Inside /home/pratajczak/Pobrane/oracle_fdw:
  a) make
  b) make install
6. Logged as postgres
7. I have set environment variable LD_LIBRARY_PATH by command: export LD_LIBRARY_PATH=/home/pratajczak/Pobrane/instantclient_12_1
8. I have set environment variable ORACLE_HOME by command: export ORACLE_HOME=/home/pratajczak/Pobrane/instantclient_12_1
9. Starting my PostgreSQL
10. My PostgreSQL crash after command: CREATE EXTENSION oracle_fdw;

**Comment by laurenz** [comment]
Thank you.

In the case of a crash, you should [collect a stack trace][stacktrace]. This requires that you have the debugging symbols for PostgreSQL installed and the `ulimit` of the PostgreSQL server set so that it writes core dumps.

There are three things I'd like to know for clarification:

1. How exactly do you start PostgreSQL.

2. Is there only a single version of PostgreSQL installed?

3. Are you using regular PostgreSQL as downloaded from postgresql.org or are you using some fork of PostgreSQL?


 [stacktrace]: https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD

**Comment by monumatik** [comment]
1. I start PostgreSQL manually, e.g. pg_ctl -h localhost -p xxxx -U xxxx start, from postgres linux account.
2. Yes, there is only one PostgreSQL version on my virtual machine.
3. I used postgresql-9.3.10 source https://www.postgresql.org/ftp/source/v9.3.10/
I will try to make a stack trace.
 ;)

**Comment by laurenz** [comment]
It looks like you are doing everything correctly.
I have never had it crash during `CREATE EXTENSION`.
I'm curious for the stack trace.

**Comment by monumatik** [comment]
Please give me a few days to do it. I'am from Poland and now we have a short holidays :)
I'll text to you on Monday.

**Comment by laurenz** [comment]
I'll close this as inactive.
Don't hesitate to reopen it if you got new data.
