### ISSUE TITLE
could not access file "$libdir/oracle_fdw": No such file or directory

### ISSUE THREAD

**Issue by AlexDevLer** [laurenz/oracle_fdw#346]
Hello.

I have a database based on PG11, installed all necessary details, from sqlplus i have access to database, but I don't know how to fix this problem. I can't find where this library is created and located. "echo $libdir" didn't help to me. It shoes nothing. I don't have an possibility to change version of PG, so what can i do to install oracle_fdw successfully? System: CENTOS 7

**Comment by laurenz** [comment]
By &ldquo;based on PG11&rdquo;, do you mean that you are using PostgreSQL v11 or some fork of PostgreSQL?

Can you please tell me the exact installation procedure you used?

Is `oracle_fdw.so` in the list returned by

    ls $(pg_config --pkglibdir)

**Comment by AlexDevLer** [comment]
Yes, im using PostgreSQL v11. At the beginning, i installed all oracle packages v19.3 like a sqlplus and so on. After this, i checked connection to oracle database via ./sqlplus.... Im using PG v11.3, psql 9.2.24. Later I downloaded oracle_fdw package to home directory and unzipped it. After that, I installed it by makefile, entered as postgres user, wrote "create extension oracle_fdw" and catck the this error. I have solved this problem by copying the file "oracle_fdw.so" to usr/pgsql-11/bin. But, i catch the next error "ERROR:  could not load library "/usr/pgsql-11/lib/oracle_fdw.so": libclntsh.so.19.1: cannot open shared object file: No such file or directory". Yes, it returned in the list by this command.

**Comment by AlexDevLer** [comment]
I have found the directory to which i should include this file, /usr/lib64. I included libclntsh.so, libnnz19.so and libclntshcore.so.19.1, after that i have an error "ERROR:  could not load library "/usr/pgsql-11/lib/oracle_fdw.so": /usr/pgsql-11/lib/oracle_fdw.so: undefined symbol: errcontext
". I think that something is going wrong, but i dont know what.

**Comment by AlexDevLer** [comment]
Now i did all as decribed on https://github.com/laurenz/oracle_fdw/issues/62, but i copied pgxs directory from /usr/pgsql-11/bin/ to /usr/bin and server directory from /usr/include/pgsql to /usr/include because of appearing of mistakes and did it by algorithm. make installation goes perfect, but in the moment of  extension's creation i obtain the error 'ERROR:  could not load library "/usr/pgsql-11/lib/oracle_fdw.so": /usr/pgsql-11/lib/oracle_fdw.so: undefined symbol: errcontext'. totally I don't know how to solve it.

**Comment by laurenz** [comment]
Yes, it must be a problem similar to the one you are referring to. It is probably caused by different PostgreSQL installations on the same machine and my manually copying files around.

You should never copy any part of the PostgreSQL installation anywhere else, it is unnecessary and may cause confusion.

Also you shouldn't manually move `oracle_fdw.so` anywhere, `make install` will automatically place it in the correct directory.

Could you remove all the files you manually copied around, then build and install oracle_fdw again from scratch and copy and paste what you did here?

Also, what PostgreSQL installations are there on the machine?

**Comment by AlexDevLer** [comment]
All actions:
1) yum list 'postgres*'
![image](https://user-images.githubusercontent.com/55701276/65484679-79800c00-dec1-11e9-9935-a5ab2d34d81a.png)
2) Other steps to make
![image](https://user-images.githubusercontent.com/55701276/65485314-5c4c3d00-dec3-11e9-9f77-93f243fea03d.png)
3) make install
4) psql postgres postgres
5) create extension oracle_fdw
6) error with libdir
![image](https://user-images.githubusercontent.com/55701276/65485383-90bff900-dec3-11e9-906e-7183b83c5d01.png)


> Also, what PostgreSQL installations are there on the machine?
Just a PostgreSQL, nothing else.

**Comment by AlexDevLer** [comment]
pg_config
![image](https://user-images.githubusercontent.com/55701276/65486178-9cacba80-dec5-11e9-80f3-effd0aad78e8.png)

**Comment by laurenz** [comment]
Thank you for the detailed diagnosis.

The problem is even though you set the variable `PG_CONFIG`, you don't export it.

My `Makefile` knowledge is not sufficient that I know without checking if that would be enough; the safe way to build oracle_fdw with PostgreSLQ 11 is

    make PG_CONFIG=/usr/pgsql-11/bin/pg_config

So your build process used `pg_config` from the 9.2 installation, and oracle_fdw was build and installed with PostgreSQL 9.2. That's what caused the problem.

If you don't need the 9.2 installation, the best thing would be to uninstall it so that this cannot happen again.

**Comment by AlexDevLer** [comment]
Thanks a lot. We have created new other server and there it works.
