### ISSUE TITLE
Access to oracle partitioned tables returns wrong result

### ISSUE THREAD

**Issue by qinghuiguo** [laurenz/oracle_fdw#357]
Hello!
When I query the Oracle partition table in the PG using oracle_fdw, I returned the wrong result.

In PG ,it returned the data of the full table.

> select count(*) from TS_QUICK_INCREASE partition(SYS_P902);

In fact, it returned the full table data, I expect to return the data of the partition。

**Comment by qinghuiguo** [comment]
Additional
>select oracle_diag();
> oracle_fdw 2.2.0, PostgreSQL 11.1, Oracle client 11.2.0.4.0, ORACLE_HOME=/usr/local/oracle/instantclient_11_2

**Comment by laurenz** [comment]
You are trying to run an Oracle query in PostgreSQL, which won't have the desired result.

The `partition(SYS_P902)` does not specify a partition (PostgreSQL knows nothing about Oracle partitions).
It just happens to work because it is correct syntax for an alias.

If you want to get only the data from a single partition, you'll have to specify a `WHERE` condition that identifies the partition. Simple `WHERE` conditions are pushed down to Oracle, and Oracle can do partition pruning, so that will do what you want.

**Comment by qinghuiguo** [comment]
Thanks a lot!
