### ISSUE TITLE
foreign-data wrapper handler function 81410 did not return an FdwRoutine struct

### ISSUE THREAD

**Issue by ashaiqing** [laurenz/oracle_fdw#367]
select * from oracle_test_fdw_foreign_table;
ERROR:  XX000: foreign-data wrapper handler function 81410 did not return an FdwRoutine struct

**Comment by laurenz** [comment]
That points towards a version mismatch or some other basic misunderstanding.

Can you give me details:

- If you get it to run,

       SELECT oracle_diag();

  Otherwise, please tell me the version of oracle_fdw, PostgreSQL and Oracle client involved.

- Which operating system are you using, and what is the version?

- Are you using standard PostgreSQL or a fork of some kind?

- From where did you download PostgreSQL and how did you install it?
  Give me the gory details.

- How exactly did you install oracle_fdw?
  Did you build oracle_fdw with the PostgreSQL with which you are running it, or with some other installation (perhaps with another version)?

- Given the error, this is the question I am most interested in:
  How did you define the foreign data wrapper in the database?
  Are you using the foreign data wrapper that got created by `CREATE EXTENSION` or did you use `CREATE FOREIGN DATA WRAPPER` to create it?
  If the latter, what exact statement did you use?

Please tell me anything that stands out, and thank you for your patience.

**Comment by ashaiqing** [comment]
First of all, thank you very much for your patience！
```
highgo=# select oracle_diag();
 oracle_fdw 2.2.0, PostgreSQL 10.6, Oracle client 19.3.0.0.0
(1 行记录)
```
I got the  [oracle_fdw-2.2.0-pg10-win64](https://github.com/laurenz/oracle_fdw/releases)  from here .
Frist I copy the  .control  and  .sql  file to \share and .dll to \bin
then 
```
highgo=# create extension oracle_fdw;
CREATE EXTENSION
highgo=# create server oradb foreign data wrapper oracle_fdw options(dbserver  '//192.168.33.146:1521/ORCL');
CREATE SERVER
highgo=# grant usage on foreign server oradb to highgo;
GRANT
highgo=# create user mapping for highgo server oradb options(user 'highgo',password 'XXXXXX');
CREATE USER MAPPING
highgo=# create foreign table oracle_test_fdw_foreign_table(id int options(key 'true') not null,name varchar(255)) server oradb options(schema 'HIGHGO ',table 'ORACLE_TEST_FDW_FOREIGN_TABLE');
CREATE FOREIGN TABLE
highgo=# select * from oracle_test_fdw_foreign_table;
ERROR:  XX000: foreign-data wrapper handler function 81410 did not return an FdwRoutine struct
```
above.
thanks again!

**Comment by laurenz** [comment]
That looks fine.

Is this the PostgreSQL downloaded from the EnterpriseDB site?

Could you run the following two queries for me:

    SELECT * FROM pg_foreign_data_wrapper;

    SELECT * FROM pg_proc WHERE oid = 81410;

**Comment by ashaiqing** [comment]
I'm sorry I forgot a very important question just now.
it is not from EnterpriseDB actually, it is HGDB from china and  based on PostgreSQL，I don't know if it's critical.
however.
```
highgo=# SELECT * FROM pg_foreign_data_wrapper;
  fdwname   | fdwowner | fdwhandler | fdwvalidator | fdwacl | fdwoptions
------------+----------+------------+--------------+--------+------------
 oracle_fdw |       10 |      81410 |        81411 |        |
(1 行记录)


highgo=#
highgo=# SELECT * FROM pg_proc WHERE oid = 81410;
      proname       | pronamespace | proowner | prolang | procost | prorows | provariadic | protransform | proisagg | proiswindow | prosecdef | proleakproof | proisstrict | proretset | provolatile | proparallel | pronargs | pronargdefaults | prorettype | proargtypes | proallargtypes | proargmodes | proargnames | proargdefaults | protrftypes |       prosrc       |       probin       | proconfig | proacl
--------------------+--------------+----------+---------+---------+---------+-------------+--------------+----------+-------------+-----------+--------------+-------------+-----------+-------------+-------------+----------+-----------------+------------+-------------+----------------+-------------+-------------+----------------+-------------+--------------------+--------------------+-----------+--------
 oracle_fdw_handler |        16432 |       10 |      13 |       1 |       0 |           0 | -            | f        | f           | f         | f            | t           | f         | v           | u           |        0 |               0 |       3115 |             |                |             |             |                |             | oracle_fdw_handler | $libdir/oracle_fdw |           |
(1 行记录)
```
Finally, thank you very much for your reply！

**Comment by laurenz** [comment]
The query results look just fine. so it must be HGDB.
It looks like they are not binary compatible with PostgreSQL.

There are two options:
- try building oracle_fdw with HGDB yourself and see how far you get
- get oracle_fdw binaries from HGDB

I'd ask the vendor about this.

**Comment by laurenz** [comment]
Can I close the ticket or can I help you any further?

**Comment by wangshisan** [comment]
I encountered the same error. And resolved by rebuild PostgresSQL and FDW.
