### ISSUE TITLE
PGXN oracle_fdw 2.2.0 package is incorrect

### ISSUE THREAD

**Issue by jhgoodwin** [laurenz/oracle_fdw#374]
Hi, thanks for making this package, but I noticed that the pgxn package is incorrect.

https://pgxn.org/dist/oracle_fdw/2.2.0/

If you go there and download the package using the green arrow in the upper right, you will notice the zipfile's Makefile references a README.oracle_fdw, which appears to have been renamed to README.md

When attempting to use pgxn to install, it will not work without this file as far as I can tell.

Would it be possible to correct this zip and re-upload it?

Thanks, John

**Comment by laurenz** [comment]
You are right. I tried to replace the package, but PGXN refused to do that.

I have sent e-mail to the site maintainers, maybe they can help.

**Comment by jhgoodwin** [comment]
Would it be possible to version this package up and deprecate the 2.2.0 version?

**Comment by laurenz** [comment]
Sorry for the delay.
David has replaced the package once, but something must have gone wrong, since the required file still wasn't there.

This is not worth a new release, which would mean that I have to build Windows binaries, but I have just re-released it as 2.2.1 (which will never be an official release; the next one will be 2.3.0 or 3.0.0), but it should fix your problem.

You may have to wait a few minutes for the new release to become available.

**Comment by jhgoodwin** [comment]
I will try it. Thank you for looking into this!
