### ISSUE TITLE
2.2.1 is not available here

### ISSUE THREAD

**Issue by devrimgunduz** [laurenz/oracle_fdw#378]
Hi,

I noticed 2.2.1 on PGXN, but not in here. Can you please also do a release from here?

Regards, Devrim

**Comment by laurenz** [comment]
There is not really a release 2.2.1.

I just artificially created one on PGXN because #374 complained that the `README.oracle_fdw` file was missing from the PGXN distribution.

So it was a packaging error that only affects the PGXN package.

Is that a problem for you or were you just wondering what's going on?

**Comment by devrimgunduz** [comment]
Hi,

Oh, ok. Just wanted to make sure that if there is a new release, I need to build the RPMs. FWIW, oracle_fdw is now included in the community non-free repo:

https://yum.postgresql.org/non-free/

Cheers, Devrim

**Comment by laurenz** [comment]
Good news, thanks.

If I may abuse this issue, I haven't heard back from you about [this problem](https://www.postgresql.org/message-id/flat/1226ad210e03047be438146428704f1611c99f82.camel%40cybertec.at).
I still cannot install debuginfo packages with `dnf`; something seems to be wrong with the repository.
