### ISSUE TITLE
New option to use READ COMMITTED instead of SERIALIZABLE  for Oracle transactions.

### ISSUE THREAD

**Issue by ThinkJ001** [laurenz/oracle_fdw#382]
Hi Laurenz,

I just implemented the option of using READ COMMITTED instead of SERIALIZABLE for Oracle transactions.

I done this by adding a new SERVER option "translevel", so you can set the transaction isolation level when creating the foreign server:
CREATE SERVER oracle1 FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '', translevel 'readcommitted');

This is an optional. The default is still serializable.

Could you do a code review? And can I join your project? 

Thank you,
Jet

**Comment by ThinkJ001** [comment]
[oracle_fdw.tar.gz](https://github.com/laurenz/oracle_fdw/files/4330161/oracle_fdw.tar.gz)

**Comment by laurenz** [comment]
You have already joined the project :^)

Please do that as a pull request.
If you send it as a tarball, I'd have to figure out the diff myself.

As long as you do that, could you also introduce a setting `read_only` to make the transaction read-only? That would in many cases be more useful than `READ COMMITTED`: it gives you repeatable read.

I'd somehow prefer the name `isolation_level` for the option, and perhaps you could call the value `read_committed`. I don't know if you did that, since I didn't read the patch yet, but there should also be an value `serializable` to explicitly set the default value.

Thanks in advance!

**Comment by ThinkJ001** [comment]
Yes, isolation_level seems more appropriate, I'll changed the option name. And currently, the option's value can be serializable, readcommitted, readwrite, and readonly.

I'll pull a new request as you suggested.

Thanks.
