### ISSUE TITLE
oracle_fdw ORA-01795: maximum number of expressions in a list is 1000

### ISSUE THREAD

**Issue by datablackhole** [laurenz/oracle_fdw#387]
Hello There,

I'd like to thank you for this wonderful module.
I've been using this to fetch data from oracle for models in Odoo. In Odoo framework while debugging what shows in the sql log is that it fetches the unique ids of any given table and passes these ids as args in IN clause. In PostgreSQL there is no hard limit on no of args in IN clause. But in oracle it restricts to 1000 args. Is it possible to configure the module to overcome this limit?
There's a workaround on stackoverflow.
https://stackoverflow.com/a/17844383

**Comment by laurenz** [comment]
You are welcome, and I see your problem.
I don't feel like implementing anything like that - having `IN` lists like that is a bad pattern anyway that you should avoid. Perform a normal join rather than fetching a list of keys and querying another table with it. I have little mercy for tools that make this hard or impossible.
