### ISSUE TITLE
Getting error while running make & make install command

### ISSUE THREAD

**Issue by puli06** [laurenz/oracle_fdw#415]
I am trying to install oracle_fdw i am getting the error while running the make command
![err](https://user-images.githubusercontent.com/41475541/89506224-6f6cb080-d7e8-11ea-8a91-179f353e4e60.PNG)

**Comment by yamatattsu** [comment]
Hi puli06,

You need to install "Oracle Instant Client". "SDK package" is especially
important since it includes the header file.
Also you can check the manual. See below:

5 Installation Requirements

Oracle client version 11.2 or better is required.
oracle_fdw can be built and used with Oracle Instant Client as well as with
Oracle Client and Server installations installed with Universal Installer.
Binaries compiled with Oracle Client 11 can be used with later client
versions
without recompilation or relink.

The supported Oracle server versions depend on the used client version (see
the
Oracle Client/Server Interoperability Matrix in Oracle Support document
207303.1).  PostgreSQL and Oracle need to have the same architecture.
For example, you cannot have 32-bit software for the one and 64-bit software
for the other.


Regards,
Tatsuro Yamada


2020年8月6日(木) 16:56 puli06 <notifications@github.com>:

**Comment by puli06** [comment]
![Error](https://user-images.githubusercontent.com/41475541/89639970-3148bd00-d8cc-11ea-8460-c3f08831dfd0.PNG)
Thank you @yamatattsu , it got resolved. After that we ran the command "create extension oracle_fdw" bu it is giving this error

**Comment by yamatattsu** [comment]
Hi puli06,

No problem.
Ah.. It is easy to solve the problem.
The solution is written in the manual. Please check: "Installing the
extension" section on it. :-D
Probably, you can find the answer.

Thanks,
Tatsuro Yamada


2020年8月7日(金) 20:07 puli06 <notifications@github.com>:

**Comment by Saurabh-704** [comment]
Hello @yamatattsu I have checked all the things. I have all the things in that expect one thing.
In this link - https://www.postgresql.org/message-id/A737B7A37273E048B164557ADEF4A58B53A4D8A3%40ntex2010i.host.magwien.gv.at
one command is there - cat /proc/1234/environ | xargs -n 1 -0 echo.
After running this I am not able to get "LD_LIBRARY_PATH"
<img width="402" alt="fdw" src="https://user-images.githubusercontent.com/47383623/89736237-82e87780-da85-11ea-8779-f07d0fe0facf.png">
So how to set that path in that file.
When I am editing the environ file and trying to add path manually it is not saving, it is saying "invalid argument" something.
Can you please help me with this?!

**Comment by yamatattsu** [comment]
Hi saurabh,

>So how to set that path in that file.
>When I am editing the environ file and trying to add path manually it is
not saving, it is saying "invalid argument" something.
>Can you please help me with this?!

If you use pg_ctl command to start PostgreSQL, You can write
"export LD_LIBRARY_PATH= ..."  in these files of postgres user.

  ~/.bash_profile
  ~/.bash_rc
  or something like that

I'm not sure regarding systemd, but the thread which you mentioned would be
useful, I suppose.

Thanks,
Tatsuro Yamada


2020年8月10日(月) 0:48 saurabh Gupta <notifications@github.com>:

**Comment by Saurabh-704** [comment]
Hello @yamatattsu thank you for your response. I login to postgresql user using - su - postgres
after that exported oracle lib path in ~/.bash_profile and then after saving I ran source ~/.bash_profile, and restarted the postgresql service. But still getting the same error after running "create extension oracle_fdw".
Am I lagging something or what ?
can you please help me with this?

**Comment by laurenz** [comment]
How is PostgreSQL started? Using `systemd`?

**Comment by Saurabh-704** [comment]
What I am doing I am login to postgres user -
"su - postgress"
And login as a Postgres user I am  running - "pgsql" 
This is how I am going inside Postgres.
Is this what u r looking for @laurenz

**Comment by laurenz** [comment]
So you are using systemd, and the problem is like in issue #305.
You should write a custom systemd service file like in [my comment there](305#issuecomment-474488009) that sets the required environment variables.

Environment variables from the shell are ignored if you start a service with `systemctl`.

**Comment by Saurabh-704** [comment]
Hello @laurenz thank you for your response. 
I have gone inside the this path - "cd /etc/systemd/system/postgresql-12.service.d/"
In this path I am having - "override.conf" file.
In that conf file I am having - 
[Service]
Environment="LD_LIBRARY_PATH=/usr/lib/oracle/19.8/client64/lib"
SO do I need to add here something or should I create new file and add lib and home path there?

**Comment by Saurabh-704** [comment]
Hello @laurenz I create a file under /etc/systemd/system/ with name  - "postgresql-12.service"
In that file I have added -
[Service]
Environment=LD_LIBRARY_PATH=/usr/lib/oracle/19.8/client64/lib
And then I did - "systemctl daemon-reload"
But when I did postgres restart using - "systemctl restart postgresql-12"
It is showing as - 
<img width="524" alt="li1" src="https://user-images.githubusercontent.com/47383623/89879987-50ec2800-dbe1-11ea-9886-81a1ddfae45a.png">

And when I am running - "systemctl status postgresql-12.service"
It is showing -
<img width="458" alt="li2" src="https://user-images.githubusercontent.com/47383623/89880222-a32d4900-dbe1-11ea-9e62-e501f44bb6d5.png">

And at last line it is showing -
<img width="878" alt="li3" src="https://user-images.githubusercontent.com/47383623/89880321-b9d3a000-dbe1-11ea-9a98-01129e892c2a.png">

**Comment by laurenz** [comment]
You forgot the `.include` line.

**Comment by Saurabh-704** [comment]
Thank you @laurenz for you help. I am able to run "create extension oracle_fdw" without any error.
Thank you

**Comment by yamatattsu** [comment]
Sounds good! :-D



2020年8月12日(水) 0:50 saurabh Gupta <notifications@github.com>:
