### ISSUE TITLE
Question on the "oradiag_postgres" directory

### ISSUE THREAD

**Issue by snaga** [laurenz/oracle_fdw#42]
Hi,

While I was struggling with oracle_fdw to get worked, I found the "oradiag_postgres" directory (/var/lib/pgsql/oradiag_postgres) which contains a trace file (sqlnet.log) and a log file (log.xml). Which process or component is storing information in this directory?

This information looks to be useful for troubleshooting, but not mentioned in README yet. So, I would like to know more details about this in order to add some explanation to the README.

Regards,

**Comment by laurenz** [comment]
That is the _Advanced Diagnostic Repository_ introduced in Oracle 11.1.
All kinds of log and trace files are generated there.
You can find documentation about it [here](http://docs.oracle.com/cd/E11882_01/appdev.112/e10646/oci10new.htm#LNOCI1020); the <tt>sqlnet.ora</tt> parameters governing it can be found [here](http://docs.oracle.com/cd/E11882_01/network.112/e10835/sqlnet.htm#NETRF397).
While I find this feature useful to collect all the log files on an Oracle server in a single place, I find it pretty useless on the client side, and the first thing I usually do is turn it off by setting <tt>DIAG_ADR_ENABLED = OFF</tt>.

About mentioning it in the README:
I understand and appreciate that people want to improve the documentation.
I have received several requests to mention certain Oracle bugs that caused problems for users, but unless it is a problem that specifically affects oracle_fdw I am reluctant to do so, since I am afraid of having the README end up being a copy of Oracle's bug database &mdash; there are just so many of them.
For the same reason I am reluctant to include anything from the Oracle documentation that is not specifically relevant to oracle_fdw.

**Comment by snaga** [comment]
Thanks for such quick reply and information about the feature.

> I am afraid of having the README end up being a copy of Oracle's bug database
> For the same reason I am reluctant to include anything from the Oracle documentation that is not specifically relevant to oracle_fdw.

I understand your concerns.
I agree that non-oracle_fdw specific information should not be in for the README
to avoid in terms of duplicated documentation and its maintenability.

The reason why I asked is I've not been familiar with Oracle OCI and oracle_fdw
configuration yet, but your information is enough for me so far.

Thanks!
