### ISSUE TITLE
Question: Oracle varible keeped in session?

### ISSUE THREAD

**Issue by nikolaysu** [laurenz/oracle_fdw#432]
In the request, set the oracle variable using **oracle_execute** function:
DBMS_APPLICATION_INFO.SET_MODULE ('' postgres for MOZILLA / Explorer 3.0.2.2202 '', NULL);

Is it possible to guarantee that until the session is closed on the postgres side, this variable will be set on all relevant session on Oracle side?

**Comment by laurenz** [comment]
Each PostgreSQL session will open an Oracle session for each foreign Oracle server used, and these sessons will be kept open until the PostgreSQL sessions end or you close those cached connections explicitly with the `oracle_close_connections()` function.

So that should normally work. An exception would be if something unexpectedly closes the Oracle connection, for example a firewall between PostgreSQL and Oracle. In this case, oracle_fdw will try to re-establish the connections, but of course the new connection won't have the module information any more.

Is that good enough for you?

**Comment by nikolaysu** [comment]
Yes, thanks a lot.
I did a number of experiments and they confirm what you wrote.
