### ISSUE TITLE
Fatal error: can't create oracle_fdw.o: Permission denied oracle_fdw.c:8:22: fatal error: postgres.h: No such file or directory  #include "postgres.h"  ^ compilation terminated. 

### ISSUE THREAD

**Issue by Aliya55** [laurenz/oracle_fdw#436]
Hi.
This error comes even after setting the right path for pg_config and installing all the development packages needed for postgresql. Am I missing anything ?

**Comment by Aliya55** [comment]
That error was fixed after I installed postgresql12-devel and when giving the make command it threw this error.
Assembler messages:
Fatal error: can't create oracle_fdw.o: Permission denied
make: *** [oracle_fdw.o] Error 2
And when run as root I got this.

oracle_utils.c:22:17: fatal error: oci.h: No such file or directory
 #include <oci.h>
                 ^
compilation terminated.
make: *** [oracle_utils.o] Error 1

**Comment by laurenz** [comment]
It looks like user who is trying to build oracle_fdw doesn't have "write" permission on the directory where you unpacked the software, so it cannot create the file in that directory.

Give the user permission.

Never build software as `root`.

**Comment by Aliya55** [comment]
Yeah I assigned the permissions to the user and it worked. When giving make install I get this error now. I do have set the correct permissions on this directory.
/usr/bin/install: cannot remove ‘/usr/pgsql-12/share/extension/oracle_fdw.control’: Permission denied

**Comment by Aliya55** [comment]
When I'm creating the extension this error comes. The file does exist in the location.

ERROR:  could not load library "/usr/pgsql-12/lib/oracle_fdw.so": libclntsh.so.19.1: cannot open shared object file: No such file or directory

**Comment by laurenz** [comment]
You didn't run

    make install

To anticipate the next question: you have to put the Oracle client shared library on the library path.

The documentation covers the installation process in some detail.

**Comment by Aliya55** [comment]
I did set the path and getting the same error. 
export LD_LIBRARY_PATH=/data/oracle/19.0/lib:$LD_LIBRARY_PATH

Also I get two locations when I find the lib file. I tried setting the path with both locations but it didn't work.
/data/oracle/19.0/instantclient/libclntsh.so.19.1
/data/oracle/19.0/lib/libclntsh.so.19.1

**Comment by Aliya55** [comment]
I copied the missing lib file to the pgsql lib location and now I get this. Also added this libnnz19.so before creating the extension. I don't know what I'm missing now.

ERROR:  could not load library "/usr/pgsql-12/lib/oracle_fdw.so": libnnz19.so: cannot open shared object file: No such file or directory

**Comment by laurenz** [comment]
Do not copy shared libraries around, it will mess up your system.
They should exist only once (that is the meaning of &ldquo;shared&rdquo;).

You must set `LD_LIBRARY_PATH` in the environment of the PostgreSQL server, not in your shell.

Alternatively, and better, add the path to `/etc/ld.co.conf` and run `ldconfig`, then restart PostgreSQL.

**Comment by Aliya55** [comment]
It's ld.so.conf right? I added the location and after running ldconfig I'm getting this 

ldconfig: /data/oracle/19.0/lib is not a known library type

Have I added the path correctly?

**Comment by laurenz** [comment]
Sorry for the type, it is `/etc/ld.so.conf`.

Can you show the contents of the file? Each directory should be on its own line.

**Comment by Aliya55** [comment]
include ld.so.conf.d/*.conf
LD_LIBRARY_PATH=/data/oracle/19.0/lib/libclntsh.so.19.1

**Comment by laurenz** [comment]
No; the file should just contain

    /data/oracle/19.0/lib

**Comment by Aliya55** [comment]
Now I'm getting this eventhough the libraries are present. Is it any issue or I can continue with restarting the postgres?

ldconfig: Input file /data/oracle/19.0/lib/libexpat.so.1.6.8 not found.

ldconfig: Input file /data/oracle/19.0/lib/libexpat.so not found.

ldconfig: Input file /data/oracle/19.0/lib/libexpat.so.1 not found.

**Comment by laurenz** [comment]
That's no problem, I think.

**Comment by Aliya55** [comment]
It worked. Thank you so much.

**Comment by MarcioRM78** [comment]
Hi guys, just sharing one important information:

My CentOS get errors during boot process after adding any configuration on **/etc/alternatives/pgsql-ld-conf** that is a link to **/etc/ld.so.conf.d/postgresql-pgdg-libs.conf**, to solve it I set the environment variables directly on the service configuration using **systemctl edit postgresql-12.service** and adding the lines below:

**[Service]
Environment=ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE
Environment=LD_LIBRARY_PATH=/opt/oracle/product/18c/dbhomeXE/lib**

after saving this content just do a **systemctl daemon-reload** and then **systemctl start postgresql-12.service** and check if its ok using.

**cat /proc/_PID_OF_POSTMASTER_PROCESS_/environ | xargs -0 -n1**

It should return something like:

LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/var/lib/pgsql
LOGNAME=postgres
USER=postgres
SHELL=/bin/bash
PGDATA=/var/lib/pgsql/13/data/
PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj
PG_OOM_ADJUST_VALUE=0
**ORACLE_HOME=/opt/oracle/product/18c/dbhomeXE
LD_LIBRARY_PATH=/opt/oracle/product/18c/dbhomeXE/lib**

Hope this helps who are using CentOS.

Regards

**Comment by Aliya55** [comment]
Hi Lauren,
 I created a foreign table and when selecting the table I'm getting this error.

ERROR:  error connecting to Oracle: OCIEnvCreate failed to create environment handle

I looked for the workarounds related to this error and tried some but not able to past this error. Can you please suggest any solution for this?

**Comment by Aliya55** [comment]
I followed the above steps. In the second step when I give this ps -p12345 -oppid= it doesn't show any output.

In PostgreSQL:
SELECT pg_backend_pid();

In a second session in the shell:
ps -p12345 -oppid=

As root or PostgreSQL OS user:
cat /proc/23456/environ | xargs -0 -n1

**Comment by laurenz** [comment]
Thanks for researching some on your own!

You need the process ID of the postmaster process, not of your current backend.
The postmaster is the parent process of all the PostgreSQL server processes.

But you are right, the problem is probably some Oracle environment variable missing there.

Try connecting with sqlplus as operating system user `postgres`; if that works, check what you need in your environment to make it work.

**Comment by Aliya55** [comment]
I'm not able to login as postgres. I can login only using the oracle user.

**Comment by Aliya55** [comment]
And now when I give this command cat /proc/23456/environ | xargs -0 -n1

It shows an empty output.

**Comment by laurenz** [comment]
Argh. When I say "connecting with sqlplus as operating system user `postgres`", I mean:

- become operating system user `postgres`

- start `sqlplus` and connect to the Oracle database with the same connection string, user and password as you are using in your foreign server and user mapping

This is the first thing that you must make happen, otherwise you cannot connect with oracle_fdw.

Ask your local Oracle DBA for help if you run into any problems there &ndash; I cannot help, since I don't know your Oracle setup.

Once you can connect with `sqlplus` like indicated above, we can continue here.

**Comment by Aliya55** [comment]
Ah I understood that actually, what I meant was I couldn't login by becoming a postgres user and I could login using the other user. That was a issue from my side here. It's fixed now and I can login as the postgres user.

I also checked for the environment variables to set in the path incase I'm missing anything, but they are good I assume. What else could be wrong? Need help urgently. 
Thanks in advance.

**Comment by laurenz** [comment]
Then I cannot help you.

You need to figure out what is different in the settings between the PostgreSQL server process and the shell session where sqlplus works. Unfortunately the Oracle error message is not very helpful. Look for the many previous issues with that error message, perhaps you find inspiration.

Among the problems that I remember leading to this error are:

- missing environment variables in the postmaster process environment

- more than one Oracle installation on the machine

- people copying shared libraries to other directories (which is pretty much the same as the previous point)

Good luck!

**Comment by Chunters** [comment]
@Aliya55 
Initially, we had problems, but now we have solved them. Since there was no step-by-step instruction, and the background is not enough. :)
There is a good manual here https://www.enterprisedb.com/postgres-tutorials/using-foreign-data-wrappers-access-remote-postgresql-and-oracle-databases. Maybe it will help you.

If you do not have access to the Internet, then there is such a step-by-step manual (for Oracle Linux). It describes all the steps and they should give understanding.
1. To get oracle_fdw
2. Download the current sources for oracle_fdw https://github.com/laurenz/oracle_fdw/releases
3. Downloading oracle-instantclient from http://yum.oracle.com/repo/OracleLinux/OL7/oracle/instantclient/x86_64/index.html
- Basic
- Devel
4. Install via
yum localinstall oracle-instantclient19.8-basic-19.8.0.0.0-1.x86_64.rpm oracle-instantclient19.8-devel-19.8.0.0.0-1.x86_64.rpm
export ORACLE_HOME = /usr/include/oracle/19.8/client64/
export LD_LIBRARY_PATH = /usr/lib/oracle/19.8/client64/lib/
echo $ ORACLE_HOME
echo $ LD_LIBRARY_PATH
The result should be:
/usr/include/oracle/19.8/client64/
/usr/lib/oracle/19.8/client64/lib/
5. Download packages and install them - > yum localinstall llvm-toolset-7-clang-5.0.1-4.el7.x86_64.rpm llvm-toolset-7-clang-libs-5.0.1-4.el7.x86_64.rpm llvm-toolset- 7-compiler-rt-5.0.1-2.el7.x86_64.rpm devtoolset-7-libstdc ++ - devel-7.3.1-5.15.el7.x86_64.rpm devtoolset-7-runtime-7.1-4.el7.x86_64. rpm llvm-toolset-7-libomp-5.0.1-2.el7.x86_64.rpm devtoolset-7-gcc-c ++ - 7.3.1-5.15.el7.x86_64.rpm devtoolset-7-gcc-7.3.1-5.15 .el7.x86_64.rpm devtoolset-7-binutils-2.28-11.el7.x86_64.rpm llvm-toolset-7-llvm-libs-5.0.1-8.el7.x86_64.rpm llvm-toolset-7-runtime- 5.0.1-4.el7.x86_64.rpm
6. Install via yum localinstall
7. If it doesn't work, then install something else postgresql11-devel (your version of the database)
8. Edit /etc/ld.so.conf.d/postgresql-pgdg-libs.conf, add the second line /usr/lib/oracle/19.8/client64/lib/, editing the version of the Oracle client, if required.
9. From the folder with oracle_fdw, do make and make install
10. Connect psql -p10110 -dpostgres;
Create FDW create extension oracle_fdw;

**Comment by laurenz** [comment]
Thanks you for that.
I don't include a step-by-step guide because there are so many different operating systems and so many different ways to install PostgreSQL and Oracle (Instant Client with ZIP or RPM, Universal Installer, ...).

If you solved the connection problem to Oracle, that's great.
Perhaps you can describe the problem briefly and how you overcame it, it might help others who hit the exact same obstacle.

**Comment by Aliya55** [comment]
Thanks for sharing @Chunters I did follow that link as a reference but it helped me only in a certain way.
 @laurenz I was able to able to solve the connection error which was basically the environment variables not set in the postmaster environment.

**Comment by Aliya55** [comment]
And I would like to know that after importing the schema from oracle, I could select the table to list the rows and columns, but when I check the size it shows 0 bytes which in oracle has 40 MB
Is there anything else to do after importing the schema?

**Comment by laurenz** [comment]
The size of a foreign table is always 0. It does not contain any data.

When you perform operations on a foreign table, the operations actually take place on the Oracle table.

It just looks like a table, somewhat like a view does.

**Comment by Aliya55** [comment]
Ah yeah I just read it in the documentation of foreign data. Is it possible to take the dump of the foreign table ?

**Comment by laurenz** [comment]
If you run a `pg_dump` on a foreign table, that will just copy the foreign table definition.
From PostgreSQL v14 on, you can use the `--include-foreign-data=server_name` to include the data from foreign tables for a certain foreign server in a `pg_dump`.

But of course you can `COPY` data from a foreign table, or you can create a materialized view on top of it.

Since your problem seems to be resolved, can we close the ticket?

**Comment by Aliya55** [comment]
Yeah sure. Thank you for the info.
