### ISSUE TITLE
ERROR:  connection for foreign table "test_enames" cannot be established

### ISSUE THREAD

**Issue by nraju-c** [laurenz/oracle_fdw#448]
Hi Laurenz,

I am getting below error while selecting the foreign table from Postgres & please help me on fixing the issue.

**ERROR**:  connection for foreign table "test_enames" cannot be established
DETAIL:  **ORA-12154**: TNS:could not resolve the connect identifier specified
SQL state: HV00N

**Details**
1.I am using Postgres 13 version on Windows 10 64 Bit machine.
2.I installed **oracle_fdw-2.3.0-pg13-win64** successfully in my Windows 10 6bit machine.
3.Created system variable for TNS_ADMIN=C:\Oracle\product\12.2.0x64\client_1\network\admin
4.Created below steps successfully. 

CREATE FOREIGN DATA WRAPPER oracle_fdw

CREATE SERVER foreign_oracle
    TYPE 'Oracle12'
    VERSION '12'
    FOREIGN DATA WRAPPER oracle_fdw
    OPTIONS (dbserver '//vms150.abc.com:1524/ABC00D70');

CREATE USER MAPPING FOR postgres SERVER foreign_oracle
    OPTIONS ("user" 'Test', password 'Test1');

CREATE FOREIGN TABLE test_enames(
    eno numeric NULL,
    ename character varying(100),
    eloc character varying(100)
) SERVER foreign_oracle
    OPTIONS (table 'TEST_ENAMES');

But still getting error while selecting table  , Please let me know incase if i missed any steps.

Thanks
Raju

**Comment by laurenz** [comment]
That seems like an Oracle configuration problem.
To debug this, try running the following as the operating system user that runs the PostgreSQL service:

```bash
sqlplus Test/Test1@//vms150.abc.com:1524/ABC00D70
```

If that doesn't work, start debugging that. That should be easier, since oracle_fdw is not part of the equation then.

If the `sqlplus` call above works as you intend it to, make sure that the PostgreSQL service has the `TNS_ADMIN` environment variable set (did you restart the service after setting it?). I am not sure how to check the environment for a running process on Windows, but "Process Explorer" might do the trick.

What is the reason for you to set `TNS_ADMIN`?

**Comment by nraju-c** [comment]
After fixing the connection string getting below error.
can you please advise.

**ERROR:  foreign-data wrapper "oracle_fdw" has no handler
SQL state: 55000**

**Comment by laurenz** [comment]
That is because you created the foreign data wrapper without the handler and validator functions.

You should follow the installation instructions and create the extension:

```
CREATE EXTENSION oracle_fdw;
```

That will automatically create the foreign data wrapper for you as part of the extension.

**Comment by nraju-c** [comment]
Finally fixed after below correction on connection.

**Before Fix**
CREATE SERVER foreign_oracle
TYPE 'Oracle12'
VERSION '12'
FOREIGN DATA WRAPPER oracle_fdw
**OPTIONS (dbserver '//vms150.abc.com:1524/ABC00D70');**

**After Fix**
CREATE SERVER foreign_oracle
TYPE 'Oracle12'
VERSION '12'
FOREIGN DATA WRAPPER oracle_fdw
**OPTIONS (dbserver 'ABC00D70');**

**Comment by nraju-c** [comment]
Thanks laurenz .

**Comment by nraju-c** [comment]
Issue has been resolved.
