### ISSUE TITLE
Oracle_FDW zip file for Red Hat Linux

### ISSUE THREAD

**Issue by nraju-c** [laurenz/oracle_fdw#449]
Please provide the Oracle_FDW zip file for Red Hat Linux OS.
I found only for Windows OS.

Please help me on finding the right zip file for the same.

**Comment by laurenz** [comment]
You have to download the source and build oracle_fdw yourself.

There are instructions in the documentation, and it is not difficult.

I don't provide binaries for Linux because there are so many distributions.
Also, building on Windows is more complicated, because not everybody has access to a C compiler.

**Comment by nraju-c** [comment]
Can i use below link as a right source ? please advise.

https://pgxn.org/dist/oracle_fdw/

**Comment by laurenz** [comment]
Yes, certainly.

Or you use this site:
https://github.com/laurenz/oracle_fdw/releases/tag/ORACLE_FDW_2_3_0

**Comment by nraju-c** [comment]
Thanks Laurenz.
