### ISSUE TITLE
Exception handling issue

### ISSUE THREAD

**Issue by IceGlance** [laurenz/oracle_fdw#479]
Hi, Laurenz,

SELECT oracle_diag('exatest_scan_1521');
oracle_fdw 2.4.0devel, PostgreSQL 13.3, Oracle client 19.3.0.0.0, Oracle server 19.0.0.0.0

On the oracle side we have a view with instead of insert/update/delete trigger. 
Trigger checks the data and raises custom exception if one of checks failed. 
Postgres inserts/updates/deletes data to oracle view (foreign table).

Short transactions (insert of ~500 rows) are ok - postgres client (pgAdmin) gets the exception message if one of check failed.
But there is a problem with long transactions (insert of ~15000 rows) - if trigger raises exception, 
transaction is rolled back, but postgres does not get exception message and shows "Query returned successfully in ..." without information about how many rows were inserted.

Using autonomous transaction we logged all trigger stages and found that "silent" rollback without error message occurs when trigger raise exception.

Is there a way to find out at what stage (oci-oracle_fdw-pgAdmin) the problem appears?

Thanks in advance.

**Comment by laurenz** [comment]
Sorry for the late reply, I was on vacation.

So you are saying that Oracle threw an error, but PostgreSQL did not receive that error? That should definitely not happen.

To investigate that, I would have to reproduce it. Can you provide SQL statements for Oracle and PostgreSQL so that I can reproduce the problem?

**Comment by laurenz** [comment]
Any new on this?
