### ISSUE TITLE
Postgresql inheritance and push down

### ISSUE THREAD

**Issue by brajwham** [laurenz/oracle_fdw#484]
Hi,

In case of table inheritance in Postgres, Oracle foreign table ( Oracle FDW ) is capable of applying optimization like push down where conditions, Aggregate, etc. at foreign server ?

Thanks
Braj

**Comment by laurenz** [comment]
Sorry for the late answer; I have been on vacation.
I guess that you are talking about a foreign table that is an inheritance child of another table, and that you select from that other table. If not, please tell me what exactly you mean.
Since selecting from a table with inheritance is the same as a `UNION` of queries on all inheritance children, the answer is "yes"; each of these queries will be planned independently.

**Comment by laurenz** [comment]
Does that answer your question? Can I close the issue?
