### ISSUE TITLE
write slow from postgres to oracle

### ISSUE THREAD

**Issue by sp1022** [laurenz/oracle_fdw#510]
When I use oracle_fdw to write data from postgres to oracle, it's very slow, writing at an average of 2000 entries per second

**Comment by laurenz** [comment]
That is indeed not very good performance. However, oracle_fdw can be expected to be slow with bulk data modifications, since each row modified on the Oracle side requires a round trip between PostgreSQL and Oracle. For the case of `INSERT`, PostgreSQL v14 has a new feature to support bulk inserts with foreign data wrappers more efficiently, but oracle_fdw has not implemented that.

**Comment by laurenz** [comment]
Do you need more information or shall we close the issue?
