### ISSUE TITLE
RPM package / repository for CentOS7/8

### ISSUE THREAD

**Issue by fcpimenta** [laurenz/oracle_fdw#546]
Hi,

Is there a repository for binary packages for CentOS 7/8?

If not, is there a rpm spec so that we can build and have more control over the installation?

**Comment by laurenz** [comment]
There is the PGDG repository. Devrim prepared spec files for oracle_fdw, but he doesn't build binaries, since non-free software is involved. You can find [spec files for various distributions][git] in the Git repository.

 [git]: https://git.postgresql.org/gitweb/?p=pgrpms.git;a=tree;f=rpm/redhat/main/non-free/oracle_fdw

**Comment by fcpimenta** [comment]
Thank you so much!!
