### ISSUE TITLE
oracle_fdw installation issue

### ISSUE THREAD

**Issue by tushar1311** [laurenz/oracle_fdw#550]
Hello Laurenz,

My env: 
PostgreSQL engine: 14.2 (No other Postgres and Oracle running on this server)
Oracle client: 21.3.0.0.0

I was able to successfully run:
make clean
make
make install

And see these created:
-rw-r--r--. 1 root root 863568 Sep 25 00:40 oracle_fdw.o
-rw-r--r--. 1 root root 270240 Sep 25 00:40 oracle_utils.o
-rw-r--r--. 1 root root 154064 Sep 25 00:40 oracle_gis.o
-rwxr-xr-x. 1 root root 649792 Sep 25 00:40 oracle_fdw.so

But when I try to create an extension, getting this:

**postgres=# create extension oracle_fdw ;
ERROR:  could not load library "/usr/pgsql-14/lib/oracle_fdw.so": /usr/pgsql-14/lib/oracle_fdw.so: undefined symbol: heap_open
postgres=#**

I do have oracle_fdw.so in place.

[root@host oracle_fdw-2.4.0]# ls -ltr /usr/pgsql-14/lib/oracle_fdw.so
-rwxr-xr-x. 1 root root 649792 Sep 25 00:50 /usr/pgsql-14/lib/oracle_fdw.so

Thanks in advance!
Tushar

**Comment by laurenz** [comment]
This must come from the following piece of code in `oracle_fdw.c`:

```c
/* "table_open" was "heap_open" before v12 */
#if PG_VERSION_NUM < 120000
#define table_open(x, y) heap_open(x, y)
#define table_close(x, y) heap_close(x, y)
#endif  /* PG_VERSION_NUM */
```

So the implication is that either oracle_fdw was built on a machine with PostgreSQL v11 or less, or you were using the oracle_fdw source from before commit 19a9ea163d602bb6ca22b6969aa5db88a1980569 in October 2019, which first appeared in oracle_fdw 2.3.0.

Since your prompt suggests that you were using oracle_fdw 2.4.0, that is an apparent mystery. You also said that you ran `make clean`, which should have got rid of any binaries built against an older version of PostgreSQL.

So I cannot say with certainty what is going on. Perhaps you accidentally used a different `oracle_fdw.so` than the one you installed with `make install`? Perhaps you can remove all `oracle_fdw.so` from the system before building and installing it again.
If you change into the oracle_fdw source directory and run the following on the binary you built:

```bash
nm -u oracle_fdw.so | grep heap_open
```

do you get a result?

I hope this discussion enables you to locate the problem, because to me it is not clear what went wrong.

**Comment by tushar1311** [comment]
Hi Laurenz,

Thanks for your reply. I do see below:

[root@host oracle_fdw-2.4.0]# nm -u oracle_fdw.so | grep heap_open
                 U heap_open
[root@host oracle_fdw-2.4.0]#
[root@host oracle_fdw-2.4.0]# cat oracle_fdw.c | grep -i heap_open
/* "table_open" was "heap_open" before v12 */
#define table_open(x, y) heap_open(x, y)
[root@host oracle_fdw-2.4.0]#

**Comment by laurenz** [comment]
That confirms that this binary must have been build with PostgreSQL v11 or less, even though you say that cannot be.
What do you get for

```
pg_config --version
```

**Comment by tushar1311** [comment]
I see this:

[root@host oracle_fdw-2.4.0]# pg_config --version
PostgreSQL 14.2

Thanks,
Tushar

**Comment by laurenz** [comment]
Then I am out of ideas. Everything points in the direction that you built the binary against an old PostgreSQL version.

Perhaps you could run

```bash
make clean
make
```

again and post the complete output. Then I can check if everything looks ok.
