### ISSUE TITLE
Issue returning CLOB column

### ISSUE THREAD

**Issue by mlazlo** [laurenz/oracle_fdw#551]
Working in Aurora-Postgresql:
oracle_fdw: version 1.2

I have a table that on the oracle side has a column of data type 'clob'. Table column gets created in Postgresql as data type 'text'. I can select every column individually or in combination with no issue, except if I run 'select * from local_fdw_table or I include the clob column. It hangs then I get this error:

SSL SYSCALL error: EOF detected
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
psql (12.12 (Ubuntu 12.12-1.pgdg18.04+1), server 12.8)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)

Any ideas on how to query this column?

**Comment by mlazlo** [comment]
I am not seeing the RDS instance (cluster) going down though. Are you saying the actual oracle_fdw server is going down or the actual Aurora Postgresql instance?

**Comment by laurenz** [comment]
"Server closed the connection unexpectedly".
If that is not a firewall or some other network component, it is the PostgreSQL server crashing. oracle_fdw is running inside the database server, so if one crashes, the other crashes too.
As i said, look at the PostgreSQL log file.

**Comment by mlazlo** [comment]
This seems to be related to the CLOB column on the source side. I can select from the ~50000 row table without issue if I select all columns except the CLOB. I see no failures in Postgresql error logs either.

feeds=> SELECT oracle_diag('asrs_fdw')
feeds-> ;
                                      oracle_diag
---------------------------------------------------------------------------------------
 oracle_fdw 2.3.0, PostgreSQL 12.8, Oracle client 21.1.0.0.0, Oracle server 19.0.0.0.0
(1 row)

From error log:
2022-10-07 01:12:52 UTC:xx(58567):asrs@feeds:[765]:LOG:  duration: 19560727.485 ms  statement: insert into asrs_ga_supplement.text
	select * from asrsgafdw.text;
2022-10-07 01:12:52 UTC:xx(58567):asrs@feeds:[765]:LOG:  could not send data to client: Connection timed out
2022-10-07 01:12:52 UTC:xx(58567):asrs@feeds:[765]:FATAL:  connection to client lost

Any idea's why this is happening for the CLOB column only?

**Comment by mlazlo** [comment]
Looking around your git repo, I find issues which could explain mine: 
[https://github.com/laurenz/oracle_fdw/issues/429]
Could this be my issue?

**Comment by laurenz** [comment]
Both the client and the server find the connection interrupted, so it must be some network connection that times out and breaks the connection.
A timeout may of course be due to the performance degradation caused by LOBs.

Try changing the [keepalive](https://www.cybertec-postgresql.com/en/tcp-keepalive-for-a-better-postgresql-experience/) idle time on the client and/or server.

**Comment by mlazlo** [comment]
I did try the keepalive flag on client side but did not help. 
AWS RDS extension states this version:
CREATE EXTENSION oracle_fdw
	SCHEMA "public"
	VERSION 1.2

Though your oracle_diag function returns 2.3.0.

I did see other issues here about LOB column performance and you potentially fixing that issue. Was it ever fixed? If so what version of the extension is it working in?

**Comment by laurenz** [comment]
The discrepancy between the extension version and the software version is intentional and documented.
I have no intention of speeding up LOB performance at present.
Anyway, that is not the problem here, even if it may trigger the actual problem.
Try to change the keepalive idle time on the server side. At any rate, this is a network problem.

**Comment by laurenz** [comment]
Did you have any success with changing `tcp_keepalives_idle`?

**Comment by mlazlo** [comment]
I was only able to try this on my side, aka client, but did not help. Had to have source dba convert column from clob to varchar2(4000) because no rows was larger than 4000 bytes. This fixed my performance issue. So the original issue was definitely related to how lobs are being brought across, it appears to me.

**Comment by laurenz** [comment]
Thanks for the feedback. I am sure that the performance issues with CLOBs caused the operation to take too long, so that you hit a timeout somewhere in the network. Good that you could solve it that way. I just wanted to make it clear that the error is not caused by PostgreSQL, the foreign data wrapper or Oracle, it is caused by the network.

**Comment by laurenz** [comment]
The performance problem with Oracle LOBs has been improved with commit d679a73d02057fd674fc78fe5f25183e5c9a172b.
You are welcome to test if the current development version works better for you.

**Comment by jonesnc** [comment]
I just wanted to add that adding `lob_prefetch '0'` to the `OPTIONS` section in the `CREATE FOREIGN TABLE` command is what fixed the NCLOB issue for me.

**Comment by laurenz** [comment]
@jonesnc Please open new issues for new problems. I have no idea what "the NCLOB issue" is in the context of this issue.
