### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by singingfish** [laurenz/oracle_fdw#587]
This is an issue in how terrible the oracle client libraries are.

I've found a situation where for three near identically configured databases on two hosts, connecting by SID succeeds on two of those hosts, and fails on the third one.

Configuring my server running oracle_fdw to have access to the connection details in its tnsnames.ora file eliminates the issue.  For example while this succeeded on two hosts it failed on the third:

    CREATE SERVER server_name_here FOREIGN DATA WRAPPER oracle_fdw 
        OPTIONS (dbserver '//[host]:[port]/[ORACLE_SID]')`;

Adding the tnsnames.ora entry and connecting with the below worked in all three cases:

    CREATE SERVER server_name_here FOREIGN DATA WRAPPER oracle_fdw OPTIONS (dbserver '[tns entry]');

It may be worth noting that using tnsnames.ora seems more reliable in the documentation as this was an entirely unexpected surprise.

**Comment by laurenz** [comment]
Did you just want to share that information, or do you need help with anything?
To see why the one connection attempt didn't work, you'd probably have to run an Oracle client trace.

**Comment by singingfish** [comment]
I just wanted to share that info. It may be worth mentioning tnsnames in
the docs

**Comment by laurenz** [comment]
The documentation already has

> The Oracle database connection string for the remote database.  
> This can be in any of the forms that Oracle supports as long as your
> Oracle client is configured accordingly.

To me, this includes `tnsnames.ora` (local naming) and all other naming methods, so I'd say it is sufficient. I feel reluctant to add a special recommendation for local naming, because I consider it a more complicated method than, for example, "easy connect", which didn't work for you.

My guess why it failed in one case for you is that the last component of the connection URL is *not* the SID, but the service name. Perhaps two of the databases were configured to have service name = SID, while the third didn't.

**Comment by singingfish** [comment]
yeah, possibly something like that.  At this point I got it over the line I
don't have to care any more!  However I thought I'd not the bear trap
somewhere appropriate for those who come after me.

**Comment by laurenz** [comment]
I see, and thanks for that!
