### ISSUE TITLE
postgresql to oracle database ssl configuration

### ISSUE THREAD

**Issue by domenico1982** [laurenz/oracle_fdw#598]
Can you please document the steps to configure a secure ssl connection from a postgresql database to an oracle database using oracle_fdw?

**Comment by laurenz** [comment]
That's outside the scope of the oracle_fdw documentation. Since oracle_fdw creates a normal database connection, you go about enabling TLS as usual.
A web search produced [this Oracle documentation][oradoc], and [this tutorial][tutorial] looks like it might be what you need.

 [oradoc]: https://docs.oracle.com/en/database/oracle/oracle-database/19/dbseg/configuring-secure-sockets-layer-authentication.html#GUID-F59CF401-2BE9-4ABC-89C5-0F261ABC3E75
 [tutorial]: https://oracle-base.com/articles/misc/configure-tcpip-with-ssl-and-tls-for-database-connections

**Comment by laurenz** [comment]
Does that help you?
Do you need more, or can we close this issue?
