### ISSUE TITLE
FDW 2.4 Database session hangs by TCP-HICCUPS or Network interruption

### ISSUE THREAD

**Issue by AdelM2023** [laurenz/oracle_fdw#603]
Hello Laurenz,

In my Windows PG version 13 and FDW 2.4 , I have a permanent problem with the foreign connection-sessions when there is a network error happening:
The database session stays active and open and all the known commands to kill that session doesn't help the only solution is to restart the database service.

Regards,
Adel

**Comment by laurenz** [comment]
Did you try running

```
SELECT oracle_close_connections();
```

That should close all Oracle connections in the current PostgreSQL session.

But perhaps I misunderstood your problem.
Can you describe it in some more detail?

**Comment by AdelM2023** [comment]
Hello Laurenz,

and thanks for the prompt reply.

The situation is like this:


   - A Java application is accessing the pg database 13 via jdbc and then
   uses FDW 2.4 to get or update data from the target oracle database.
   - All goes fine until a network interruption happens whereas that
   database session using the FDW hangs and there is no way to kill it even if
   the network problem was solved, I tried all commands including your
   suggested one but the connection hangs as active and not possible to close
   "will be displayed as red  in pgAdmin". All other database sessions woh are
   not using the FDW run normally.
   - The only thing that helps is to restart the database completely.

At the beginning I thought it could be an FDW bug so I upgraded from 2.3 to
2.4 but the same situation happens again.

Actually I am expecting the connection that is using the FDW to
abort immediately with an error message when the network connection is
interrupted but not hanging like this.

Thanks and regards,
Adel

Am Do., 31. Aug. 2023 um 00:50 Uhr schrieb Laurenz Albe <
***@***.***>:

**Comment by laurenz** [comment]
Hm, that sounds bad.

I have no Windows in reach to reproduce this exactly, but I can get the hang on Linux by stopping the network interface while the Oracle session is open.

With that, I observe the following:
- oracle_fdw hangs in a `read()` on the network socket, that is, it waits for a response from Oracle
- `pg_terminate_backend()` fails to terminate the session
- if I enable the network interface again while the session is hanging, it eventually comes alive again

Did you try to let a session hang for three hours? By that time, TCP keepalive should eventually kick in and make the `read()` fail. That is, unless Oracle disables TCP keepalive on its connections. I searched, but found no options to configure keepalive settings for Oracle connections. That is an unpleasant shortcoming, but there is nothing I can do about it.

Upon further investigation, I found an attribute `OCI_ATTR_RECEIVE_TIMEOUT` for the server handle; perhaps that could help. I played with this parameter and with `OCI_ATTR_BREAK_ON_NET_TIMEOUT` too, but the session kept hanging.

Sorry, but I am at the end of my wit with that. If you have a support contract with Oracle, perhaps they have an idea.

There is one trick how you can get rid of these sessions without restarting the server. It is described in [this article](https://www.cybertec-postgresql.com/en/cancel-hanging-postgresql-query/). The text is written for Linux, but it should work just the same with a Windows debugger that allows you to call functions.

**Comment by AdelM2023** [comment]
Hello Lorenz,

Oh thats very nice from you to spend that time to Investigate the issue.
OK I will read the article in the link and keep searching,,will Feedback as
soon as I find a solution.

Regards Adel

Laurenz Albe ***@***.***> schrieb am Fr., 1. Sept. 2023,
14:39:

**Comment by laurenz** [comment]
There is one thing you can do to at least reduce the likelihood of your network session going bad while it is idle: you could call `oracle_close_connections()` immediately after each access to a foreign table.

**Comment by AdelM2023** [comment]
Hello Laurenz,

am thinking about using the windows command taskkill or the pg command pg_kill to get rid of that hanging session. I have to test first.

**Comment by laurenz** [comment]
The problem is that killing the process like that will probably cause PostgreSQL to undergo crash recovery, including a certain down time.

**Comment by AdelM2023** [comment]
The restart of the database will undergow anyway manually or automatic!
The problem is that we can not change any thing on the oracle side, the issue should be resolved at pg side.

**Comment by laurenz** [comment]
I keep hearing that "we cannot change anything on the Oracle side", and I continue to doubt it.
Just because a couple of ageing Oracle DBAs engage in a power play... where there's a need, there is a way.

But I don't think that that is relevant here, and that any change on the Oracle side is needed. I just don't know what could be done on the client side to interrupt a hanging Oracle statement.

Did you read my recommendation above that you run `oracle_close_connections()` right after every access to a foreign table? That will probably reduce the problem drastically.

**Comment by philflorent** [comment]
Hi,

"All goes fine until a network interruption happens". This is the main problem, network interruptions should not happen (or at least not frequently !). 

If the hardware is not the issue perhaps some firewall kills the connection ? I strongly suggest to configure sqlnet.expire_time in sqlnet.ora at server side. The primary goal of this parameter is to cleanup dead sessions but its side effect is to work as a keep-alive. The RECOMMENDED value (10) is different from the DEFAULT value (0). I suggest to use the RECOMMENDED value. It sounds strange that DEFAULT <> RECOMMENDED but the idea is not to change the default behavior after a major db upgrade. X years ago the small probe packet could be an overhead. Now, it's clear it's a good idea to put this parameter to X with X > 0 (and < firewall timeout).

Extract from Oracle documentation :
5.2.50 SQLNET.EXPIRE_TIME

Use the sqlnet.ora parameter SQLNET.EXPIRE_TIME to specify how often, in minutes, to verify that client and server connections are active.

Purpose

To specify time intervals, in minutes, for how often to verify that client and server connections are active.

Usage Notes

Setting a value greater than 0 ensures that connections are not left open indefinitely, due to an unusual client termination. If the system supports TCP keepalive tuning, then Oracle Net Services automatically uses the enhanced detection model, and tunes the TCP keepalive parameters

If the probe finds a terminated connection, or a connection that is no longer in use, then it returns an error, causing the server process to exit.

This parameter is primarily intended for the database server, which typically handles multiple connections at any one time.

Limitations on using this terminated connection detection feature are:

    It is not allowed on bequeathed connections.

    Though very small, a probe packet generates additional traffic that may downgrade network performance.

    Depending on which operating system is in use, the server may need to perform additional processing to distinguish the connection probing event from other events that occur. This can also result in degraded network performance.

Default

0

Minimum Value

0

Recommended Value

10
 
Best regards,
Phil

**Comment by AdelM2023** [comment]
Hi Philflorent,

Thanks for the comment and the information.
As I have already explained it is not possible to update the target
database as it is serving many other client databases and also I can
understand the Admin there not to do so as the problem occurs initially on
our side not the host oracle database.

I will implement a manual pg_kill job that will fire when this situation
happens, hav no other choice.

Regards,
Adel
philflorent

Am Mi., 20. Sept. 2023 um 18:42 Uhr schrieb philflorent <
***@***.***>:

**Comment by laurenz** [comment]
Phil didn't suggest updating the Oracle database, but setting `SQLNET.EXPIRE_TIME = 10` in `sqlnet.ora`.

I tried that, and it had no effect on my test case where I disabled the network connection under an open Oracle connection.

**Comment by philflorent** [comment]
Hi Laurenz,
It was expected. Main goal of this parameter is to avoid network interruptions and to eliminate dead sessions at Oracle side. It is always possible to find workarounds but network and storage have to be reliable. 
Best regards,
Phil

**Comment by laurenz** [comment]
Ha. I just thought of a possible remedy: you could configure the operating system's keepalive settings on the PostgreSQL server machine. If that is an option, please tell me what operating system you are using there, then I can tell you how to do it.

**Comment by AdelM2023** [comment]
Hello Laurenz,

it is Windows 2019 Server,
thanks in advance.
Adel

Laurenz Albe ***@***.***> schrieb am Mo., 6. Nov. 2023, 09:23:

**Comment by laurenz** [comment]
You could use the advice from [my article][keepalive]:

> On Windows, you change the TCP keepalive settings by adding these registry keys:
>
> ```none
> HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\KeepAliveTime
> HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\KeepAliveInterval
> ```
>
> As noted above, there is no setting for the number of keepalive probes, which is hard-coded to 10. The registry keys must be of type `DWORD`, and the values are in milliseconds rather than in seconds.
>
> After changing these keys, restart Windows to activate them.

Set the values so that `KeepAliveTime` + 10 * `KeepAliveInterval` is shorter than the time after which the broken network component decides to abort the connection.

 [keepalive]: https://www.cybertec-postgresql.com/en/tcp-keepalive-for-a-better-postgresql-experience/#os

**Comment by AdelM2023** [comment]
Hi Laurenz,

Thanks a lot I will try that.

Regards,
Adel

Am Mi., 8. Nov. 2023 um 12:44 Uhr schrieb Laurenz Albe <
***@***.***>:

**Comment by laurenz** [comment]
Thanks for the reply.
I don't know how to improve that. I'll close the ticket and leave it "unsolved".
The ticket can be reopened if anybody has a good idea how to deal with that.

**Comment by AdelM2023** [comment]
Hallo Laurenz,

ein schönes neues Jahr wünsche ich dir erstmal.

Wie ich gesehen habe, gibt es neue Versionen von FDW 2.6.0 und 2.7.0 ,
hier finde ich aber kein Windows ZIP wie die vorherigen.

Könntest du mir bitte sagen, wie ich die Windows Version herunterladen kann?

Wir bei Dematic GmbH verwenden "wie du weißt" FDW bereits auf Windows für
PG-13.

Eine Frage hätte ich noch, wie man die kompatibilitäten zwischen fdw und
postgres versionen finden könnte.

Danke und Grüße,
Adel



Am Mi., 6. Dez. 2023 um 21:56 Uhr schrieb Laurenz Albe <
***@***.***>:

**Comment by laurenz** [comment]
You'll have to build oracle_fdw from source if you want to use it on Windows. The process is documented in the README. I don't have access to any Windows machines.

Please open new issues instead of commenting on a ticket about something else.
