### ISSUE TITLE
Rolling back a transaction in Postgres and Oracle

### ISSUE THREAD

**Issue by Asolvolga** [laurenz/oracle_fdw#616]
Good afternoon! I express my gratitude to you for the oracle_fdw extension. 
I want to clarify a small point in the work of the extension. The instructions say that if the transaction in Postgres closed normally, then you can guarantee that in Oracle as well. But there is a small chance that it will close in Oracle, but not in Postgres. In what situation is such a probability possible? Is it possible to use oracle_fdw as data synchronization from Postgres to Oracle? Thank you.

**Comment by laurenz** [comment]
- It could be that the `COMMIT` on the PostgreSQL side fails. This can be caused by a database problem (for example, a deferred constraint fails) or be hardware limits (you run out of disk space materializing a `WITH HOLD` cursor).
- PostgreSQL can crash before you get to commit. You might for example run out of disk space creating a WAL segment.
- The operating system can crash before you commit on the PostgreSQL side, for example because of a power outage.
- The network can break before you get to commit.

You can probably use oracle_fdw to synchronize data from PostgreSQL to Oracle. If you want everything to be 100% safe in the case of unexpected outages, you'd use an algorithm like this:

- If the PostgreSQL transaction that wrote data to Oracle commits successfully, you are good.
- If the commit on PostgreSQL fails, you have to check on Oracle if the transaction committed there or not. The simplest solution is to retry the work, and if it turns out that the data are already in Oracle, you catch the constraint violation, and move on.

**Comment by laurenz** [comment]
Does this answer your question? Shall we close the issue?

**Comment by Asolvolga** [comment]
Yes, thank you very mach for the answer.
