### ISSUE TITLE
Import foreign schema limit to is not passing table names to Oracle query

### ISSUE THREAD

**Issue by joaostorrer** [laurenz/oracle_fdw#634]
I'm using `import foreign schema` with a specific table like this:
```
import foreign schema "TEST" limit to (table_a) from server test_server into test;
```
And it is taking a long time to import.
I found out that the query that oracle_fdw uses to import is this:
https://github.com/laurenz/oracle_fdw/blob/6534f3ee6ae14be8a7388ae07d68373aa9dcd4f4/oracle_utils.c#L2522-L2533

So I found out that the dictionary views statistics is not updated in the Oracle database I'm using, and that is the reason it is taking too long to import.
But my question is why isn't the table name used in the `limit to` clause of `import foreign schema` passed in the query?
Because if the query is "filtered" with the table name that I'm importing it parses less blocks, becoming faster.

**Comment by laurenz** [comment]
I have had complaints about slow Oracle dictionary queries before, see #584. But you figured that problem out.

In principle, the query in Oracle could be restricted like you suggest. But there is a difficulty that is caused by the fact that Oracle folds identifiers to upper case, while PostgreSQL folds them to lower case. By default, oracle_fdw tries to be smart about converting names (see the `case` option to `IMPORT FOREIGN SCHEMA`). I cannot think of a good way to translate this to Oracle - or at least in the default case of `case = 'smart'`. So I don't restrict the Oracle query and let PostgreSQL filter the translated table names.

**Comment by joaostorrer** [comment]
Perhaps concatenating the tables listed in the `limit to` clause and passing as a bind variable (`tables_filters`) like `'table_a, table_b'` to a query like this could work:

```SQL
SELECT col.table_name, col.column_name, col.data_type, col.data_type_owner,
       col.char_length, col.data_precision, col.data_scale, col.nullable,
       CASE WHEN primkey_col.position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
FROM all_tab_columns col,
     (SELECT con.table_name, cons_col.column_name, cons_col.position
      FROM all_constraints con, all_cons_columns cons_col
      WHERE con.owner = cons_col.owner AND con.table_name = cons_col.table_name
        AND con.constraint_name = cons_col.constraint_name
        AND con.constraint_type = 'P' AND con.owner = :nsp) primkey_col
WHERE col.table_name = primkey_col.table_name(+) AND col.column_name = primkey_col.column_name(+)
  AND col.owner = :nsp
  AND UPPER(col.table_name) in (SELECT  regexp_substr(UPPER(:table_filters), '[^,]+', 1, LEVEL)
                                FROM    dual
                                CONNECT BY regexp_substr(UPPER(:table_filters), '[^,]+', 1, LEVEL) IS NOT NULL)
ORDER BY col.table_name, col.column_id
```

**Comment by laurenz** [comment]
I implemented support for this.
Could you test if the latest code works for you?
