### ISSUE TITLE
Empty CLOB in 2.7.0

### ISSUE THREAD

**Issue by NAP-prm** [laurenz/oracle_fdw#709]
Hello! 
After update 2.5.0 to 2.7.0 CLOB fields come empty and not NULL
We downgrade to 2.6.0, and CLOB it's OK, but wery slow.
How to get more diagnostic data? Tnx
![image](https://github.com/user-attachments/assets/e470c946-8854-47cb-82fb-09f00380d70b)

**Comment by philflorent** [comment]
Hi,

I see in the readme :

_Oracle bugs

This is a list of Oracle bugs that affect or have affected oracle_fdw.
...
Oracle client 21c is known not to work for CLOB columns (they appear empty). There is no ultimate proof that that is an Oracle bug, but other versions are working fine._

I see in the screen captures that it matches : your instant client is a 21c (innovation release) . I would avoid it to use 19c or 23ai (LTR versions ; better and longer support from Oracle).

Best regards,
Phil

**Comment by laurenz** [comment]
Right, this is a known issue; see #643.

If you have access to Oracle's bug database, I would be happy to known if that is a known bug and if they have a fix.

You'll have to use a different Oracle client version.

**Comment by philflorent** [comment]
Laurenz,

I did some research but it does not seem like an explicitly known bug. Some bugs are similar, notably a bug with clobs and database links involving 21c databases but the source bug is "unpublished" e.g  

"Ultimately, the problem was identified as unpublished RDBMS Bug 32049479 - OCI:TTC:NO VARIABLE SHOULD BE DECLARED AFTER SAVCSV IN TTCRS2C AND TTCRBUR
The length of the LOB was not being properly saved, corrupting the LOB length upon its transfer to the local database. This in turn resulted in the application-side error "Clob is too large to be stored in a Java String"

In this case it looked like the Java app had done something wrong but it was an OCI internal Oracle bug. Another SR would be necessary to make Oracle investigate further. 
OP can do it since my databases run on Power hardware and Oracle does not provide innovation releases on Power anymore. I can/will open a SR if it's reproducible with a LTR client/server combo only. 

Best,

**Comment by philflorent** [comment]
Hi,
I had written a message about the possibility to open a service request if you can reproduce the issue on your platforms but Oracle will likely not investigate that. Oracle Client 21c & Oracle Database 11.2.0.3 is NOT a valid combo according to MOS note 207303.1 (it's not not even WAS supported in the compatibility matrix it's a NO, it never was supported). 
In fact the 11.2 server version is not the problem here since issues were also reported with 19c databases, it's the 21c client that fails. But if you still have to access Oracle 11.2.0.3 databases from PostgreSQL the best choice is probably the 19c client anyway. 
Best regards,
Phil

**Comment by laurenz** [comment]
@philflorent Thanks for your research.
Yes, Oracle likes to be secretive about its bugs.
If you cannot find anything conclusive, one thing that could be done fairly easily is apply patch sets to a (non-instant) client and see if any of them gets rid of the problem. I'm not suggesting that you should do that, but someone who is suffering from the problem and has access to their patches could feel motivated.

**Comment by mkgrgis** [comment]
@laurenz, what about `ereport` in case of Oracle client 21.x + `CLOB`? This is not first discussion about the problem. Maybe, we can store [`oracleClientVersion`](https://github.com/laurenz/oracle_fdw/blob/d67c6b400270f32c06bda03701f85d7b28e3427b/oracle_fdw.c#L686) in FDW structures and fast compare it during column processing?

**Comment by darold** [comment]
FYI, with Ora2Pg I use the following workaround when retrieving data :
```
       if option empty_lob_null is true then
                 target_col = "CASE WHEN dbms_lob.getlength(colname) = 0 THEN NULL ELSE colname END,";
       end
```
So as you know the data type of the column in oracle_fdw you could do the same in the pushdown query.

**Comment by NAP-prm** [comment]
![image](https://github.com/user-attachments/assets/5ac521ff-6cfa-4bdc-b0a1-b8f0ee5e06a3)
2.7.0 + 19.24 + 11.2.0.3 = Ok. Thx!

**Comment by laurenz** [comment]
@mkgrgis Good idea; done in 26a7636762c3337a36e9e3398d7d7b442a46056a.

@darold Are we talking about the same problem? This is not about LOBs that are actually empty, but about CLOBs with content that appear empty when using Oracle 21.

**Comment by laurenz** [comment]
@darold No problem, thanks for the clarification.
