### ISSUE TITLE
Please provide oracle_fdw.dll file for postgres database and its version is 16.

### ISSUE THREAD

**Issue by ashokkumar164478** [laurenz/oracle_fdw#714]
could not access file "$libdir/oracle_fdw": No such file or directory 

Unable to extract oracle_fdw.dll from oracle_fdw.sln can you please provide here

**Comment by laurenz** [comment]
I cannot provide a Windows binary, because I don't have Windows.

You'll have to follow [the instructions][winbuild] to build oracle_fdw on Windows.
I know that's not totally simple, and you'll need a C compiler. Sorry.

 [winbuild]: https://github.com/laurenz/oracle_fdw?tab=readme-ov-file#building-oracle_fdw-on-windows
