### ISSUE TITLE
IMPORT FOREIGN SCHEMA "SYS" LIMIT TO (DBA_SEGMENTS) is slow

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#84]
this takes about 1 minute to finish (with a back network behind a VPN ...)
Maybe it is because the **LIMIT TO(...)** clause is not included into the generated query at Oracle side:

`SELECT col.table_name, col.column_name, col.data_type, col.data_type_owner,
        col.char_length, col.data_precision, col.data_scale, col.nullable,
        CASE WHEN primkey_col.column_position IS NOT NULL THEN 1 ELSE 0 END AS primary_key 
FROM all_tab_columns col,      
(SELECT con.table_name, ind.column_name, ind.column_position       
FROM all_constraints con, all_ind_columns ind       
WHERE con.owner = ind.table_owner AND con.table_name = ind.table_name         
AND con.index_owner = ind.index_owner AND con.index_name = ind.index_name         
AND con.constraint_type = 'P' AND con.owner = :nsp) primkey_col 
WHERE col.table_name = primkey_col.table_name(+) 
AND col.column_name = primkey_col.column_name(+)   
AND col.owner = :nsp
ORDER BY col.table_name, col.column_id`

**Comment by laurenz** [comment]
Are you talking about [`FETCH FIRST n ROWS ONLY`](http://docs.oracle.com/database/121/SQLRF/statements_10002.htm#SQLRF55636)?
That is only supported from Oracle 12.1 on, and how could it help?

I have also noticed that that query can take a long time to finish, but I'd say that's a problem with Oracle's catalog tables (which are complicated views on internal tables).
I couldn't come up with a simpler query, can you?

I admin that 1 minute is quite long, but then you probably don't `IMPORT FOREIGN SCHEMA` very often, right?

**Comment by legrandlegrand** [comment]
There is a missunderstanding ...
This query is for all columns of a schema, but the import if for only one table.

I suggest to add a where condition on the table_name (taken from the **LIMIT TO ()** clause) like
Select
...
AND col.column_name = primkey_col.column_name(+) 
AND col.owner = :nsp 
AND col.table_name= **:table_name**
ORDER BY col.table_name, col.column_id

**Comment by laurenz** [comment]
Oh, I understand.

I considered that when I added `IMPORT FOREIGN SCHEMA` support, but the problem is that a table name on Oracle is usually (but not always) upper case and in PostgreSQL lower case, so what should the condition for the Oracle query look like?
I'd have to take the different values of the "case" option into account&hellip;

I decided to give up on that, but can reconsider if you have a smart idea.

**Comment by legrandlegrand** [comment]
OK your choice works (thats the more important) even if its a little long (and It can stay like ...)

If I had to change it, I would treat table_names given in LIMIT TO (...)
exactly the same way as SCHEMA,** Coted** and **Case sensitive** like

IMPORT FOREIGN SCHEMA **"SYS"** LIMIT TO (**"DBA_SEGMENTS","V_$SQLAREA"**)

The query would be:
...
AND col.column_name = primkey_col.column_name(+)
AND col.owner =** 'SYS'**
AND col.table_name in (** 'DBA_SEGMENTS','V_$SQLAREA'**)
ORDER BY col.table_name, col.column_id 
 
Those Foreign table names should be lower case by default in Postgres.

**Comment by laurenz** [comment]
Sounds good at first sight, but consider this:

No matter if the FDW filters by `LIMIT TO` or not, PostgreSQL will always apply the filter again, but it will use it to filter the PostgreSQL table names. So in your example above, oracle_fdw would exclude everything except `DBA_SEGMENTS` and `V_$SQLAREA` and will come up with `CREATE FOREIGN TABLE dba_segments ... OPTIONS (table 'DBA_SEGMENTS')`, but then PostgreSQL will filter again and exclude this table because `'DBA_SEGMENTS' <> 'dba_segments'`. So you would end up importing nothing.

The names in `LIMIT TO` must always be PostgreSQL table names, so in order to use them in the Oracle query, I'd have to translate them. This would translation would have to depend on the "case" option, and for `OPTIONS (case 'smart')`, which is the default, this would look quite complicated.

See why I decided not to push the filters down to Oracle?

**Comment by legrandlegrand** [comment]
ok I understand
syntax should be

IMPORT FOREIGN SCHEMA "SYS" LIMIT TO (dba_segments, v_$sqlarea)

It seems that your query doen't allways brings back the PK flag [#83](https://github.com/laurenz/oracle_fdw/issues/83)
so maybe you can try this (join with ALL_CONS_COLUMNS in spite of ALL_IND_COLUMNS and case insensite filter to prevent sending all the schema's columns though the network but just the ones of the expected table)

`SELECT
	col.table_name,
	col.column_name,
	col.data_type,
	col.data_type_owner,
	col.char_length,
	col.data_precision,
	col.data_scale,
	col.nullable,
	CASE WHEN primkey_col.position IS NOT NULL THEN 1 ELSE 0 END AS primary_key
FROM
	ALL_TAB_COLUMNS col , 
  (SELECT
					con.owner,
					con.table_name,
					conc.column_name,
					conc.position
				 FROM
					ALL_CONSTRAINTS con 
					INNER JOIN SYS.ALL_CONS_COLUMNS conc 
					 ON con.owner = conc.owner
					  AND con.table_name = conc.table_name
					  AND con.constraint_name = conc.constraint_name
				 WHERE
					con.constraint_type = 'P') primkey_col 
WHERE col.table_name = primkey_col.table_name(+)
	AND col.column_name = primkey_col.column_name(+)
	AND col.owner = primkey_col.owner(+)
  AND	col.owner = 'SYS'
**AND upper(col.table_name) in  (upper('dba_segments'), upper('v_$session'))**
ORDER BY
	col.table_name ASC,
	col.column_id ASC`

**Comment by laurenz** [comment]
Hmm, using `upper` should work, that way I can get some false positives, but it should greatly reduce the search space.
I'm a bit worried that `upper` does not behave the same in Oracle and PostgreSQL (is `upper('Späße')` the same in PostgreSQL and Oracle?), but maybe I should not worry too much about people who use mixed case and non-ASCII letters in table names.

Thanks a lot for the idea concerning #83, I'll have to look into that!
It definitely seems better to use `ALL_CONS_COLUMNS` rather than `ALL_IND_COLUMNS`, but could it be that an index column that doesn't show up in the latter will show up in the former?

**Comment by legrandlegrand** [comment]
The modified query with `ALL_CONS_COLUMNS` fixes #83 (I didn' checked if it is a problem with the view content or the query/joins definition)

The upper() function could return different values on Oracle and PostgreSQL depending on respectiv encodings, but if you keep them in Oracle only with `upper(col.table_name) in (upper('dba_segments'), upper('v_$session'))` it should work even for 'Späße' or '使高兴'

**Comment by laurenz** [comment]
Do you have a reproducible example where `ALL_CONS_COLUMNS` returns rows that `ALL_IND_COLUMNS` doesn't?  I'll experiment myself, but any lead will help me.

The result of upper() depends on the collation.
In PostgreSQL:

    test=> SELECT upper('aämµ' COLLATE "C");
    ┌───────┐
    │ upper │
    ├───────┤
    │ AäMµ  │
    └───────┘
    (1 row)
    
    test=> SELECT upper('aämµ' COLLATE "en_US");
    ┌───────┐
    │ upper │
    ├───────┤
    │ AÄMΜ  │
    └───────┘
    (1 row)

In Oracle, the [documentation](http://docs.oracle.com/cd/E11882_01/server.112/e41084/functions226.htm#SQLRF06155) says:
> The database sets the case of the characters based on the binary mapping defined for the underlying character set.

I tried with a WE8ISO8859P1 10.2.0.5 database:

    SQL> SELECT upper('aämµ') FROM dual;
    
    UPPER('AÄMµ')
    ----------------
    AÄMµ

With AL32UTF8 and 12.1.0.2 I get:

    SQL> SELECT upper('aämµ') FROM dual;
    
    UPPER(
    ------
    AÄMΜ

So I'd tend not to touch this, it looks like a can of worms&hellip;

**Comment by legrandlegrand** [comment]
For the ALL_CONS_COLUMNS / ALL_IND_COLUMNS, I had one exemple (I will try to retreive it this evening), but if the PK INDEX is not created in the same schema as the table schema (it is possible in Oracle) it could be a reason ... 

Maybe this will also fix the performance ;o)

For the upper(), one Idea was to make them all in the Oracle Side like
 **AND upper(col.table_name) in (upper('dba_segments'), upper('v_$session'))**
but I understand your choice.

**Comment by laurenz** [comment]
You'll need another binary to test, right?

Of course I could only use Oracle's upper(), but it still could happen that somebody types

    IMPORT FOREIGN SCHEMA "ORAUSER" LIMIT TO ("ταβλε") INTO myschema;

and is surprised that her Oracle table `ΤΑΒΛΕ` is not imported.
Maybe I'm just paranoid though.
