### ISSUE TITLE
Little issue - incorrect version number

### ISSUE THREAD

**Issue by DavidMeteoFrance** [laurenz/oracle_fdw#92]
Hello Laurenz
With 1.3 and 1.4:

[@postgres-extension]$ more oracle_fdw.control
comment = 'foreign data wrapper for Oracle access'
default_version = '1.1'
module_pathname = '$libdir/oracle_fdw'
relocatable = true

**Comment by laurenz** [comment]
This question comes up regularly, maybe I should mention it in the README.

1.1 is the version of the extension, not the version of oracle_fdw.
The extension version only has to change if the object definitions in the extension change.
For example, the move from 1.0 to 1.1 was when I introduced the `oracle_diag` function.

There is no need to change the extension version if only the C code changes, and it would be annoying because then you would have to `ALTER EXTENSION oracle_fdw UPDATE` during every update and not just replace the binaries.

I admit it is a bit confusing.
