### ISSUE TITLE
How to fix "error executing query: OCIStmtExecute failed to execute remote query"?

### ISSUE THREAD

**Issue by sangli00** [laurenz/oracle_fdw#93]
what happen  this error?

I execute update statement 600 times is this error. 
I know this problem about oracle transaction .
/* use the correct SQLSTATE for serialization failures */  why?

how to fixed this problem.

ps:I used  pllua  extension prepare sql and execute.
maybe pllua & oracle_fdw get together running is error ?

**Comment by sangli00** [comment]
I see README.oracle_fdw about ora-8177 ,this is oracle Bug 2728408.
but,my database server is 10g

**Comment by laurenz** [comment]
It would be nice if you could describe the problems more clearly.

I guess that you are receiving an ORA-08177 while executing an UPDATE statement.
Is that correct?

You ask about the reason for the comment [here](https://github.com/laurenz/oracle_fdw/blob/master/oracle_utils.c#L2009).
The reason is that this Oracle error code means a serialization failure, that is an error a session usually gets when it is in a serializable transaction and attempts to modify a row that has been changed by a different session after the first session's snapshot was taken.
Such serialization failures do not mean that the session did something wrong, it just means that there was a concurrency problem with a different session.
The correct response is normally not to throw an error, but to retry the transaction that was interrupted by the serialization failure.
How can the appication tell if the error was a serialization failure? It can tell by the error code (= SQLSTATE in PostgreSQL). That is why I use a different error code for this specific error message.

But now to your problem. Can you answer a few questions:

- What are the versions reported by `oracle_diag`?
- Does the error happen each time you execute the UPDATE statement or only occasionally?
- Can you tell me the Oracle and PostgreSQL table definitions?
- Can you tell me the UPDATE statement?
- Is the UPDATE running inside an explicit transaction (`BEGIN` &hellip; `COMMIT` block)?  
  If yes, does this transaction take longer, and does it include other statements that modify Oracle data?

**Comment by sangli00** [comment]
YES,UPDATE statement is very correct .
I lookup oracle website find this bug detail info ,Maybe I need upgrade  server version .
But now ,my server version is 10.2.0.1,and 10.2.0.4 the bug is fix.
UPDATE statement is simple SQL:update table set columnA=1 where columnB = 2;

is not occasionally,every time execute is error.

**Comment by laurenz** [comment]
Can you tell me the Oracle bug number?

**Comment by sangli00** [comment]
postgres=# update t_uminfo set tmsi='0a47f3d5' where recno='201606021714219080407';
ERROR:  error fetching result: OCIStmtFetch2 failed to fetch next result row
DETAIL:  ORA-01002: fetch out of sequence

table t_uminfo is oracle fdw.

**Comment by sangli00** [comment]
@laurenz  what happen in this error?

**Comment by laurenz** [comment]
This error means that you are trying to fetch a result row from a SELECT statement after the transaction has been closed.

This should not happen with oracle_fdw.

Can you `SET client_min_messages = debug2`, run the statement again and send me the output?

What was the number of the Oracle bug you mentioned above?

**Comment by sangli00** [comment]
I used new release ,this problem is fixed.

**Comment by laurenz** [comment]
I'd still like to know the number of the bug that affected you; maybe I can add some documentation.

**Comment by sangli00** [comment]
Bug 2728408

**Comment by laurenz** [comment]
Hmm, it must have been some other problem, since this bug is fixed in 10g. Thanks anyway.

I'll close the issue.

**Comment by sangli00** [comment]
OK,this bug fixed in 10.2.4 ,but now,my client used version is 10.2.1,my god , this bug is still.but can't  fix .this is oracle problem .

**Comment by sangli00** [comment]
I advice my client  upgrade oracle database.

**Comment by laurenz** [comment]
Whatever the actual bug may have been, it is good to advise your client to upgrade to 10.2.0.5 if they *really* want to run old, unsupported 10.2.

**Comment by sangli00** [comment]
OK ，if I have other problem ,i will  call you in github.   Thanks for you @laurenz
