### ISSUE TITLE
fetches for VARCHAR2(4000) columns

### ISSUE THREAD

**Issue by legrandlegrand** [laurenz/oracle_fdw#99]
Hello,
I'm trying to import V$SQL_PLAN (sys.v_$sql_plan) data into PostgreSQL.
It works but is slow ... (Oracle client 10.2.0.5 / Server 11.2)

Are VARCHAR2(4000) columns considered as LONG and associated rows fetched One by One ?
What would be the best solution to improve this ?

Thanks in Advance
Regards
PAscal

**Comment by laurenz** [comment]
There is a column `OTHER_XML` of type `CLOB` in `V$SQL_PLAN`.

As mentioned in #68, Prefetching is not in effect if LOB columns are involved.

I'd assume that things speed up a little once you

    ALTER FOREIGN TABLE v_$sql_plan DROP other_xml, DROP con_id;

On my system it speeds things by a factor of two (from 100 seconds to 50 seconds).
There are a lot of data in this table, and I get similar results with sqlplus; here is a trace:

    SQL> SELECT * FROM v$sql_plan;
    
    93695 rows selected.
    
    Execution Plan
    ----------------------------------------------------------
    Plan hash value: 2657262937
    
    ------------------------------------------------------------------------------
    | Id  | Operation        | Name      | Rows  | Bytes | Cost (%CPU)| Time     |
    ------------------------------------------------------------------------------
    |   0 | SELECT STATEMENT |           | 12539 |    10M|     7 (100)| 00:00:01 |
    |*  1 |  FIXED TABLE FULL| X$KQLFXPL | 12539 |    10M|     7 (100)| 00:00:01 |
    ------------------------------------------------------------------------------
    
    Predicate Information (identified by operation id):
    ---------------------------------------------------
    
       1 - filter("INST_ID"=USERENV('INSTANCE'))
    
    Statistics
    ----------------------------------------------------------
              0  recursive calls
              0  db block gets
              0  consistent gets
              0  physical reads
              0  redo size
       48541578  bytes sent via SQL*Net to client
        9909775  bytes received via SQL*Net from client
         142642  SQL*Net roundtrips to/from client
              0  sorts (memory)
              0  sorts (disk)
          93695  rows processed

**Comment by legrandlegrand** [comment]
Yes , I was aware about LOB columns.

My Query doesn't take 'OTHER_XML' 	
SELECT 
		plan.sql_id,
		plan.plan_hash_value,
		plan.operation,
		plan.options,
		plan.object_node,
		plan."object#",
		plan.object_owner,
		plan.object_name,
		plan.object_alias,
		plan.object_type,
		plan.optimizer,
		plan.id,
		plan.parent_id,
		plan.depth,
		plan.position,
		plan.search_columns,
		plan.cost,
		plan.cardinality,
		plan.bytes,
		plan.other_tag,
		plan.partition_start,
		plan.partition_stop,
		plan.partition_id,
		plan.other, -- varchar(4000)
		plan.distribution,
		plan.cpu_cost,
		plan.io_cost,
		plan.temp_space,
		plan.access_predicates, -- varchar(4000)
		plan.filter_predicates, -- varchar(4000)
		plan.projection, -- varchar(4000)
		plan.time
	FROM
		v_$sql_plan plan
	where 	plan.sql_id=r.sql_id 
		and plan.plan_hash_value=r.plan_hash_value
		and plan.child_number=r.child_number;

It is probably that the total length of the row exceeds the FETCH MEMORY MAX SIZE ...
I will try removing 'projection' column (the longest one).

Is there a way to apply SUBSTRING function directly on Oracle side (maybe declaring a foreign table using a view) ?

**Comment by laurenz** [comment]
Reducing the row size should help.

You can use Oracle `SUBSTR` either with a view on the Oracle side or by defining the table based on a view: `... OPTIONS (table '(SELECT ...)')`

I tried increasing `PREFETCH_MEMORY`in `oracle_utils.c` to the tenfold value and got double speed (25 seconds).  Maybe I should increase the setting, or &ndash; even better &ndash; make it configurable.

**Comment by legrandlegrand** [comment]
Yes ;o)
I'm ready to test both

**Comment by 3kkani** [comment]
Hi Laurenz,

I have been testing this particular aspect a bit.

The particular query I was testing was executed with 1,177,445 fetches for 21,194,000 rows i.e. with 
a fetch size ~<=18. The estimated width showed by explain verbose (w/o statistics in place) was 1186. I though the estimated width was used for calculating the fetch size but after analyzing the foreign table the width went down to 121 but when re-executing the query the total number of fetches remained the same. The elapsed time was in a similar range both w/o stats 6:40 - 6:52 or w/ stats 6:45 - 7 min.

Running the same query between two oracle instances showed me a much larger fetch size/memory was used: only 648 fetches for 21,194,000 rows i.e. ~32,706 rows/fetch and resulted in a much better elapsed time (1:51, 2:13, 3:03 min).

In oracle I can see the avg_row_len for the table selected is 98 while the sum (data_length) is 1397. Unless I am wrong if the data_length was used to calc the fetch memory it should be around ~43MB otherwise ~3MB with the avg_row_len.

Do you know what row len is used to calc the actual fetch size/mem by OCI?

I am going to test again with larger PREFETCH values (32K rows and 3MB mem) and see how it goes but having this setting configurable at the default/table/query level would actually be a very good thing.

Thanks.
Maurizio.

**Comment by laurenz** [comment]
I just made an experiment and created an Oracle table with one `VARCHAR2(4000)` column and inserted a number of very short rows. If there were up to thirteen records in the table, a `SELECT *` required two fetches, but when I added a fourteenth row, it needed an additional third fetch.

There is no way that these fourteen rows consume 24576 bytes, so Oracle must calculate this in some different way. Now it does not square completely, because 24576 &times; 2 = 49152 and 4000 &times; 13 = 52000, but I get the definite impression that Oracle uses the maximum possible row size rather than the actual amount of data to etermine how many rows it will retrieve per fetch to not exceed the limit of bytes.

That is unfortunate, because it means that Oracle will often use way more fetches than necessary. There are two options:

1. do away with the memory limit completely and leave only the limit of 200 rows per fetch
2. make the memory limit configurable per table

Do you have an opinion what would be better?

**Comment by 3kkani** [comment]
I have the same impression and share your opinion about what row len is used to calc the fetch size but I think that having both params available and configurable at the table or even at the query level (in a query comment similar to the oracle hints?) is allowing developers to decide for both flexibility and robustness depending on their circumstances. I would prefer them not to be mandatory so keeping the current setting as the default perhaps a bit larger.

**Comment by legrandlegrand** [comment]
In real live, we have two situations:
- Transactionnal -> a few rows used at each time,
- Decisionnal -> transfert a big volume of data
So setting it at FDW **SERVER definition level** (at worst we can create 2 SERVERS for the same database) with **Memory Only** should be good

**Comment by 3kkani** [comment]
Memory only is good for controlling the max allocated memory at OCI level but I though that when dealing with smallish row len, you can end up with a quite large number of rows per fetch, that might be unexpectedly high?

**Comment by laurenz** [comment]
I have decided to make `prefetch_memory` an option on the table level.

I have created a branch `prefetch_memory` and committed dc7fb8cf5e56a97763be9369bc9610ac0fd45e51 that makes it configurable.

The code can be downloaded [here](https://github.com/laurenz/oracle_fdw/archive/prefetch_memory.zip) until I merge it.

Can you test and see if it works for you?
@legrandlegrand, do you need a 64-bit Windows binary for PG 9.5?

**Comment by legrandlegrand** [comment]
yes I'm ready to test,
but I use IMPORT SCHEMA to create my tables ...
will it be possible to ALTER them ?

**Comment by laurenz** [comment]
I have slept over it and come up with a different solution.

I have removed the memory limit completely since it seems to be pretty hard to get right anyway.
Instead I have committed c51cae58f9ad9f885c371623567098c1db26bf97 which makes the prefetch row count configurable as table option `prefetch`.

This should give you the freedom to configure how much is prefetched in a simpler way.
@legrandlegrand, I'll send you a binary if you want to test.

**Comment by legrandlegrand** [comment]
Thank you !
Installing the new version of oracle_fdw has greatly reduced the transfert time of my queries with VARCHAR2(4000) columns.
I also modified the remaining table where queries returns more that 200 rows using `alter foreign table oradb.v_$sysstat OPTIONS (prefetch '1000')`

**Comment by laurenz** [comment]
I'm still not 100% certain that it is the right choice to limit the number of lines rather than the amount of allocated memory.
But since it works for you, I'm inclined to leave it as it is until somebody complains&hellip;

**Comment by 3kkani** [comment]
I tested my queries with prefetch '10240' and the elapsed time was reduced dramatically (halved) w/o any side effect. 

I wonder if you see any problem with increasing the max allowed valued even more, 32000 for example, other than the growth of the memory allocated.

**Comment by laurenz** [comment]
I am worried that if I relax the limit too much, oracle_fdw might use so much memory that it causes errors.

Do you really get consistently faster results with `prefetch '10240'` than with &ndash; for example &ndash; `prefetch '5000'`?

**Comment by 3kkani** [comment]
I have tested a large CTAS of ~212M rows (few partitions of the original table) and a smaller one from the same table but through a view (no partition selected but rownum<=21194000). 

avg row len is ~100 in both cases and max row len ~1400.

large CTAS:
without the new prefetch option ~1h 30min with an observed fetch size ~18
40:17 with prefecth '200'
38:46 with prefetch '1000'
38:01 with prefetch '5000'
37:06 with prefetch '10240'
36:36 with prefetch '10240'
35:30 with prefetch '32000'
34:00 with prefetch '32000' 

smaller CTAS:
without the new prefetch option 6:45 - 7 with an observed fetch size ~18
3:48 w/ prefecth 200
3:29 w/ prefecth 1000
3:07 w/ prefecth 10240
3:07-3:11 w/ prefetch 32000

There is a big gain when going from 18 to 200-1000 in boths cases and still some marginal gain when using larger prefetch size like 32000 only with large/massive CTAS.

I had no memory issue when using 32000 but I do not know how much memory was actually used.

**Comment by laurenz** [comment]
Thanks for trying this out &ndash; it looks like there is little necessity to increase the limit beyond 10240.
